export type AlternativePage={slug:string;competitor:string;title:string;description:string;model:string;sourceUrl:string;bestFor:string;alternativeAngle:string;checks:readonly string[]};
const checks=['Confirm the employing or contracting entity and replacement terms','Run a role-specific assessment based on your actual stack','Document repository access, review ownership, work hours, and escalation'];
const page=(competitor:string,slug:string,model:string,sourceUrl:string,bestFor:string,alternativeAngle:string):AlternativePage=>({competitor,slug:`${slug}-alternatives`,title:`${competitor} Alternatives for Offshore Developer Staffing`,description:`Compare ${competitor} with Philippines-based offshore developer staffing for long-term software engineering capacity.`,model,sourceUrl,bestFor,alternativeAngle,checks});
export const alternativePages:readonly AlternativePage[]=[
page('Toptal','toptal','a curated freelance talent network that screens applicants and introduces matched professionals','https://www.toptal.com/faq','teams that want a curated global network and an individual trial','a location-focused recruiting lane and repeatable team routines matter more than network breadth'),
page('Turing','turing','an AI-assisted platform for sourcing, vetting, matching, and supporting remote technical professionals and teams','https://www.turing.com/hire-developers','teams seeking broad, platform-led matching across many technical skills','manager-led onboarding, consistent location, and long-term delivery routines are priorities'),
page('BairesDev','bairesdev','a nearshore provider offering staff augmentation, dedicated teams, and outsourced development','https://www.bairesdev.com/services/','organizations seeking a broad nearshore development provider','your engineering lead will own architecture and delivery while a partner recruits named roles'),
page('Andela','andela','a global talent marketplace connecting companies with technical professionals','https://www.andela.com/','companies that value a geographically broad technical talent marketplace','one labor market and a recruiting process tailored to a durable offshore team are important'),
page('Arc','arc','a remote talent platform offering freelance and full-time candidates and hiring support','https://arc.dev/','teams comparing freelance and permanent remote roles','you need sustained recruiting, onboarding controls, and team operations'),
page('Gun.io','gun-io','a developer talent network supporting contract and full-time hiring paths','https://gun.io/','teams seeking experienced developers through a developer-focused network','building a consistent offshore team and operating cadence is the primary goal'),
page('Lemon.io','lemon-io','a marketplace matching startups with vetted developers from several regions','https://lemon.io/','startups seeking fast access to individual developers from a curated network','you want to recruit for a stable seat and develop the person within your team'),
page('X-Team','x-team','a company providing long-term remote developers to engineering teams','https://x-team.com/developers','organizations that want remote developers supported by an established community','geographic focus and direct operating ownership are deciding factors'),
page('DistantJob','distantjob','a remote recruitment agency focused on full-time technology professionals','https://distantjob.com/','employers seeking recruiting help for full-time remote roles','recruiting, continuity, and operating support should sit in one engagement'),
page('Full Scale','full-scale','a software development company offering development teams and staff augmentation','https://fullscale.io/','companies seeking an established offshore team-building provider','you want a Philippines-specific hiring path and direct control of individual contributors'),
page('CloudDevs','clouddevs','a platform focused on vetted Latin American developers and designers','https://clouddevs.com/','North American teams prioritizing Latin American time-zone proximity','planned overlap works and you value an Asia-Pacific talent lane with documented handoffs'),
page('YouTeam','youteam','a marketplace connecting clients with developers employed by software agencies','https://youteam.io/','buyers comparing agency-employed developers through a marketplace','you prefer one accountable recruiting and operating relationship'),
page('Proxify','proxify','a global network matching companies with vetted technology professionals','https://proxify.io/','teams seeking access to a global pool of screened specialists','durable team design in one employment market matters more than global optionality'),
page('Index.dev','index-dev','a platform for hiring pre-vetted remote software developers and technical talent','https://www.index.dev/','teams that prefer a platform-led shortlist','your priority is a location-consistent team with documented client-side controls'),
page('Upwork','upwork','a broad work marketplace for contracting independent professionals and agencies','https://www.upwork.com/hire/developers/','teams prepared to source, screen, contract, and manage freelancers directly','you want support around recruiting, continuity, and role operations'),
page('Gigster','gigster','a managed software development service that assembles teams for technology work','https://gigster.com/','organizations seeking an externally managed project-delivery model','your company wants to own product, architecture, tickets, reviews, and releases'),
page('Accelerance','accelerance','an outsourcing advisory firm helping clients select software development partners','https://www.accelerance.com/','companies wanting advisory help to select an outsourcing firm','the target country and staff-augmentation model are already clear'),
page('Uplers','uplers','a hiring platform connecting companies with remote technology professionals','https://www.uplers.com/talent/hire-developers/','companies seeking curated remote technology talent','you want recruiting and staffing operations designed around the Philippines'),
page('Terminal','terminal-io','a service for building remote engineering teams in supported international markets','https://www.terminal.io/','growth teams building engineering groups in selected global markets','the Philippines fits your coverage plan and explicit client controls are required')
];
