import type { BlogPost, BlogSection } from './data';

type August13Record = {
  slug: string;
  title: string;
  reader: string;
  outcome: string;
  focus: string;
  evidence: string[];
  caution: string;
  datePublished: '2026-08-13';
};

const section = (heading: string, body: string[], bullets?: string[]): BlogSection => ({ heading, body, bullets });

const records: August13Record[] = [
  { slug: 'offshore-developer-react-server-components-brief-2026-08-13', title: 'How to brief an offshore developer on React Server Components', reader: 'product teams moving a route toward server-rendered React', outcome: 'a measured component boundary with client behavior preserved', focus: 'data fetching, client boundaries, loading states, and bundle impact', evidence: ['A route-level before-and-after build result', 'Tests for loading, error, and interactive states'], caution: 'moving code across the boundary without checking browser-only dependencies', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-tailwind-design-system-brief-2026-08-13', title: 'A practical brief for offshore Tailwind design-system work', reader: 'frontend leads consolidating repeated interface patterns', outcome: 'a reusable component that matches existing tokens and states', focus: 'token usage, responsive behavior, variants, and documentation', evidence: ['A component matrix covering every variant', 'Keyboard and viewport checks against the current system'], caution: 'creating a visually similar component that quietly adds a second design language', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-postgresql-query-tuning-brief-2026-08-13', title: 'How to scope PostgreSQL query-tuning work offshore', reader: 'backend teams investigating a slow production-shaped query', outcome: 'a measured query improvement with result correctness intact', focus: 'query plans, representative data, indexes, and regression checks', evidence: ['Plans and timings from the same dataset shape', 'A correctness test for edge cases and empty results'], caution: 'optimizing one sample query while increasing write cost or changing semantics', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-redis-cache-boundaries-2026-08-13', title: 'A safer offshore brief for Redis caching changes', reader: 'service owners adding a cache around an expensive read', outcome: 'a cache path with explicit freshness and failure behavior', focus: 'keys, invalidation, stampedes, fallback reads, and metrics', evidence: ['Hit, miss, stale, and Redis-unavailable tests', 'A documented invalidation owner and expiry rationale'], caution: 'serving stale or cross-tenant data because the key design was implicit', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-kubernetes-readiness-checks-2026-08-13', title: 'How to assign Kubernetes readiness-check work', reader: 'platform teams improving how services enter traffic', outcome: 'a readiness signal that reflects real dependency health', focus: 'startup, readiness, liveness, timeouts, and rollout behavior', evidence: ['Pod transition tests during dependency failure', 'A rollout record showing the signal protects traffic'], caution: 'using liveness to mask an application dependency or create restart loops', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-terraform-module-review-2026-08-13', title: 'A reviewable Terraform module assignment for an offshore developer', reader: 'infrastructure leads standardizing repeatable environments', outcome: 'a small module with safe defaults and clear ownership', focus: 'inputs, state, provider versions, plans, and destructive changes', evidence: ['A plan from a clean workspace', 'Validation of defaults and a reviewed change sequence'], caution: 'letting a reusable module hide broad permissions or irreversible actions', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-oauth-callback-integration-2026-08-13', title: 'How to scope OAuth callback integration work', reader: 'application teams connecting a new identity provider', outcome: 'a callback flow that handles state, errors, and account linking safely', focus: 'redirect validation, state, PKCE, sessions, and failure messaging', evidence: ['Valid, invalid, replayed, and cancelled-flow fixtures', 'A review of token handling and account-linking decisions'], caution: 'accepting a successful callback without proving the request belongs to the same browser flow', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-email-deliverability-review-2026-08-13', title: 'A focused email-deliverability review for offshore developers', reader: 'product teams responsible for transactional email', outcome: 'reliable delivery signals without exposing unnecessary customer data', focus: 'event taxonomy, retries, suppression, templates, and privacy', evidence: ['Test messages across success, bounce, and complaint paths', 'A redacted event record and owner for unresolved delivery failures'], caution: 'treating provider acceptance as proof that a message reached its recipient', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-csv-import-validation-2026-08-13', title: 'How to brief an offshore developer on CSV import validation', reader: 'operations teams importing structured data into an application', outcome: 'an import that rejects unsafe rows and explains corrections clearly', focus: 'encoding, headers, types, duplicates, partial failure, and rollback', evidence: ['Fixtures for valid, malformed, duplicate, and oversized files', 'A row-level error report and safe retry path'], caution: 'partially applying an import while leaving the operator unsure what changed', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-analytics-event-taxonomy-2026-08-13', title: 'A practical analytics-event taxonomy assignment', reader: 'product teams cleaning up inconsistent event instrumentation', outcome: 'a small event vocabulary with documented ownership and privacy limits', focus: 'names, properties, versioning, consent, and test coverage', evidence: ['An event dictionary tied to real user actions', 'Automated checks for required properties and prohibited values'], caution: 'collecting a convenient field without deciding why it is needed or how long it remains useful', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-feature-estimation-workshop-2026-08-13', title: 'How to use an offshore developer in feature estimation', reader: 'engineering managers breaking a feature into deliverable slices', outcome: 'an estimate grounded in dependencies, unknowns, and review capacity', focus: 'vertical slices, assumptions, discovery tasks, and confidence', evidence: ['A dependency map and smallest shippable slice', 'Explicit unknowns with owners and a revisit point'], caution: 'turning a number into a promise before the team has tested its assumptions', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-code-ownership-boundaries-2026-08-13', title: 'Setting code-ownership boundaries for offshore development', reader: 'teams sharing a repository across internal and external contributors', outcome: 'review ownership that protects sensitive paths without blocking delivery', focus: 'ownership files, escalation, protected paths, and reviewer capacity', evidence: ['A sample change mapped to the intended reviewers', 'A documented path for unavailable or conflicting owners'], caution: 'assigning ownership without ensuring reviewers can respond within the delivery window', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-browser-compatibility-matrix-2026-08-13', title: 'How to plan browser-compatibility checks offshore', reader: 'web teams supporting a defined set of customer browsers', outcome: 'a risk-based browser matrix tied to real journeys', focus: 'support policy, critical paths, layout differences, and defect severity', evidence: ['The same journey tested across the agreed matrix', 'Screenshots or recordings for behavior differences and a release decision'], caution: 'testing a long list of browsers while missing the journey that matters most', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-webhook-replay-protection-2026-08-13', title: 'A safer webhook replay-protection assignment', reader: 'backend teams receiving events from external systems', outcome: 'a webhook consumer that verifies origin and handles repeats safely', focus: 'signatures, timestamps, idempotency, retries, and logging', evidence: ['Valid, altered, delayed, and repeated-event fixtures', 'A bounded retry record without sensitive payload leakage'], caution: 'assuming delivery order or treating a duplicate event as a new business action', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-background-job-reliability-2026-08-13', title: 'How to scope background-job reliability work', reader: 'service teams maintaining asynchronous processing', outcome: 'a job path with clear retry, failure, and recovery behavior', focus: 'idempotency, visibility, dead letters, timeouts, and ownership', evidence: ['A repeat-run test proving duplicate safety', 'A failure record and documented recovery action'], caution: 'adding retries that multiply side effects or obscure the original failure', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-api-versioning-plan-2026-08-13', title: 'An API-versioning plan an offshore developer can deliver', reader: 'product teams changing a public or partner-facing API', outcome: 'a compatible transition with consumer communication and a removal rule', focus: 'contract inventory, compatibility, deprecation, and migration evidence', evidence: ['Consumer fixtures for old and new behavior', 'A migration note, deprecation owner, and review date'], caution: 'creating a version without knowing which clients still depend on the old contract', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-localization-ready-ui-2026-08-13', title: 'How to brief offshore developers on localization-ready UI', reader: 'frontend teams preparing a product for additional locales', outcome: 'a route that tolerates translated content and locale-specific formats', focus: 'message extraction, length, dates, numbers, direction, and fallback', evidence: ['Long-string and missing-translation fixtures', 'Screenshots or checks for the supported locale set'], caution: 'treating translation as a copy swap after layout assumptions have already shipped', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-load-test-scope-2026-08-13', title: 'A bounded load-test assignment for an offshore developer', reader: 'application teams checking a critical user journey before growth', outcome: 'a repeatable load result with a safe test environment and threshold', focus: 'workload shape, environment, saturation signals, and interpretation', evidence: ['A versioned workload and baseline run', 'A result tied to agreed thresholds and a named follow-up owner'], caution: 'running production-like traffic without an approved environment or an incident boundary', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-open-source-license-review-2026-08-13', title: 'How to assign open-source license review work', reader: 'engineering teams managing dependencies across several repositories', outcome: 'a dependency inventory with policy decisions recorded', focus: 'transitive packages, license evidence, notices, and exceptions', evidence: ['A generated inventory tied to the lockfile', 'A reviewer decision for every policy exception'], caution: 'relying on a package name or a stale dashboard instead of the actual shipped dependency', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-secret-rotation-plan-2026-08-13', title: 'A safe secret-rotation plan for offshore development work', reader: 'platform owners rotating credentials used by an application', outcome: 'a tested rotation with no unmanaged copy and a recovery path', focus: 'ownership, overlap windows, consumers, revocation, and verification', evidence: ['A staging rotation and application health check', 'Revocation confirmation plus an owner for any remaining consumer'], caution: 'revoking the old credential before every consumer has proved the new one works', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-monorepo-change-scope-2026-08-13', title: 'How to keep offshore monorepo changes reviewable', reader: 'engineering teams sharing packages and applications in one repository', outcome: 'a focused change with dependency impact visible to reviewers', focus: 'package boundaries, affected projects, ownership, and CI scope', evidence: ['An affected-project list and focused test result', 'A dependency graph note for any cross-package change'], caution: 'accepting a broad refactor because the repository made the blast radius hard to see', datePublished: '2026-08-13' },
  { slug: 'offshore-developer-backup-restore-exercise-2026-08-13', title: 'A practical backup-and-restore exercise for offshore developers', reader: 'small teams that need evidence their recovery path works', outcome: 'a documented restore of representative data in an approved environment', focus: 'recovery objectives, access, integrity checks, and runbook clarity', evidence: ['A timed restore with row or object verification', 'A short record of gaps, owners, and the next exercise date'], caution: 'calling a backup successful without proving that the restored system is usable', datePublished: '2026-08-13' },
];

function makePost(record: August13Record): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    excerpt: `${record.reader} can use this practical guide to reach ${record.outcome}. It covers ${record.focus} with a clear review boundary for a Philippines-based developer relationship.`,
    minutes: 9,
    datePublished: record.datePublished,
    dateModified: record.datePublished,
    revision: 'august-13-2026-blog-v1',
    keyTakeaways: [`Start with ${record.outcome}.`, `Make ${record.focus} visible before acceptance.`, 'Keep final technical and risk decisions with a named owner.'],
    sections: [
      section('Define the result before the assignment', [`A useful brief for ${record.reader} starts with an observable result: ${record.outcome}. Put the starting condition, affected users, acceptance check, and reviewer in the same ticket.`, 'State the first slice and what is out of scope. A narrow assignment gives the developer room to produce evidence and gives the buyer-side reviewer a fair basis for the decision.'], ['Name one reviewer.', 'Use representative or synthetic data where possible.', 'Set the review point before work begins.']),
      section(`Shape the work around ${record.focus}`, [`Break the assignment into a few connected checks rather than a broad request. The developer should be able to explain how each check supports the result and where the handoff occurs.`, `Ask for ${record.evidence[0].toLowerCase()} and ${record.evidence[1].toLowerCase()}. Record assumptions beside the change so a later reviewer does not have to reconstruct them.`]),
      section('Keep access and approval boundaries explicit', ['Use named accounts and the smallest repository, environment, and data scope required for the first slice. Architecture choices, production approval, security exceptions, and accepted risk remain with the named internal owner.', `The main caution is ${record.caution}. If the work reaches that boundary, pause, preserve the evidence, and ask the owner to decide the next safe action.`], ['Agree on the pull-request reviewer.', 'Write a stop rule for sensitive data or irreversible changes.', 'Record unresolved questions with an owner.']),
      section('Review evidence, then expand carefully', [`The evidence should show ${record.outcome}, not just activity. Review the changed path, focused checks, known limitation, and handoff in that order.`, 'If the first slice is sound, expand one related path at a time. Keep the same evidence standard so the relationship remains easy to manage across time zones.']),
    ],
    relatedLinks: [
      { label: 'Review the first-week onboarding guide', href: '/blog/offshore-developer-first-week-onboarding-checklist', note: 'Start with one safe contribution and only the access it needs.' },
      { label: 'Compare developer services', href: '/services', note: 'Match the technical lane with an internal reviewer.' },
      { label: 'Plan the role', href: '/contact-us', note: 'Bring the stack, first outcome, schedule, and review owner.' },
    ],
    faqs: [
      { question: 'Who accepts the result?', answer: 'The named internal reviewer accepts the outcome, evidence, and any documented limitation. The developer supplies the work and surfaces risks.' },
      { question: 'What belongs in the first assignment?', answer: 'One representative path, explicit acceptance criteria, the smallest safe access scope, and a review date. Add adjacent work only after the first result is understood.' },
    ],
    sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final', note: 'Used for evidence and ownership boundaries.' }, { name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/', note: 'Used for review framing.' }],
  };
}

export const august13BlogBatch: BlogPost[] = records.map(makePost);
