import type { ResearchPost } from './fleet-data';

type Spec = {
  slug: string;
  title: string;
  question: string;
  unit: string;
  evidence: string;
  decision: string;
  sources: { name: string; url: string }[];
};

const specs: Spec[] = [
  { slug: 'offshore-developer-estimation-calibration-research-2026-08-18', title: 'Estimation calibration for Philippines-based developer teams', question: 'When does an estimate become useful evidence rather than a promise?', unit: 'a software task moving from an initial estimate to an accepted outcome', evidence: 'assumptions, dependency wait time, review capacity, elapsed work, and the final delivery boundary', decision: 'whether to split the task, investigate an unknown, or accept the remaining uncertainty', sources: [{ name: 'Agile Manifesto', url: 'https://agilemanifesto.org/' }, { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'Google Engineering Practices: Code Review', url: 'https://google.github.io/eng-practices/review/' }] },
  { slug: 'offshore-developer-review-comment-research-2026-08-18', title: 'Code-review comment resolution across offshore development time zones', question: 'Which review comments represent release risk, and which represent optional improvement?', unit: 'a pull request and the comments that change, clarify, or leave its behavior unresolved', evidence: 'comment category, affected behavior, author response, reviewer agreement, and recheck result', decision: 'which comment blocks acceptance and who has authority to close a disagreement', sources: [{ name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/' }, { name: 'GitHub Pull Request Reviews', url: 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews' }, { name: 'Google Engineering Practices: Code Review', url: 'https://google.github.io/eng-practices/review/' }] },
  { slug: 'offshore-developer-release-note-accuracy-research-2026-08-18', title: 'Release-note accuracy for distributed software teams', question: 'Can a release note let a support or product owner predict the user-visible consequence of a change?', unit: 'one deployed change traced from code and acceptance evidence to a reader-facing note', evidence: 'changed behavior, affected audience, migration or action required, and post-release confirmation', decision: 'whether a change belongs in release communication, internal handoff, or neither', sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'CISA Secure by Design', url: 'https://www.cisa.gov/resources-tools/resources/secure-by-design' }, { name: 'Atlassian Release Notes Guide', url: 'https://www.atlassian.com/software/confluence/templates/release-notes' }] },
  { slug: 'offshore-developer-dependency-upgrade-research-2026-08-18', title: 'Dependency-upgrade evidence for offshore developer teams', question: 'What evidence shows that an upgrade reduces supply-chain risk without silently changing product behavior?', unit: 'one dependency upgrade from version inventory through compatibility verification', evidence: 'direct and transitive usage, advisory scope, lockfile change, test coverage, and runtime smoke results', decision: 'whether to upgrade, defer with an owner, replace the dependency, or escalate an incompatibility', sources: [{ name: 'GitHub Dependency Review', url: 'https://docs.github.com/en/code-security/concepts/supply-chain-security/dependency-review' }, { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'CISA Known Exploited Vulnerabilities Catalog', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog' }] },
  { slug: 'offshore-developer-dead-letter-queue-research-2026-08-18', title: 'Dead-letter queue recovery evidence in distributed application work', question: 'When does a dead-letter queue protect a system, and when does it merely hide failed work?', unit: 'one failed asynchronous job from initial attempt through inspection, replay, or disposal', evidence: 'failure class, retry history, payload safety, idempotency proof, queue age, and recovery outcome', decision: 'whether to replay, repair, quarantine, or permanently reject the job', sources: [{ name: 'Google SRE Workbook', url: 'https://sre.google/workbook/table-of-contents/' }, { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'OWASP Application Security Verification Standard', url: 'https://owasp.org/www-project-application-security-verification-standard/' }] },
  { slug: 'offshore-developer-log-redaction-research-2026-08-18', title: 'Log-redaction boundaries for Philippines-based development teams', question: 'Does an application log preserve enough diagnostic context without exposing secrets or personal data?', unit: 'one representative request and its logs across normal, denied, and failed paths', evidence: 'field inventory, sensitivity classification, correlation value, retention context, and redaction test', decision: 'which fields may be logged, transformed, restricted, or removed before troubleshooting', sources: [{ name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }, { name: 'OWASP Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' }, { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }] },
  { slug: 'offshore-developer-ci-cache-research-2026-08-18', title: 'CI cache correctness for distributed software delivery', question: 'Does a faster CI pipeline still prove the current change against the current dependency and toolchain?', unit: 'one cached pipeline job compared with a clean and invalidated execution', evidence: 'cache key inputs, hit and miss behavior, dependency revision, artifact provenance, and result agreement', decision: 'whether to retain, narrow, invalidate, or remove a cache boundary', sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'GitHub Actions Dependency Caching', url: 'https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows' }, { name: 'Google SRE Workbook', url: 'https://sre.google/workbook/table-of-contents/' }] },
  { slug: 'offshore-developer-responsive-regression-research-2026-08-18', title: 'Responsive regression evidence for offshore frontend development', question: 'Which viewport and input differences can change completion of a supported product journey?', unit: 'one high-value frontend journey exercised across declared viewport and input cohorts', evidence: 'layout state, keyboard path, touch behavior, content length, browser version, and screenshots', decision: 'which difference blocks release, needs a targeted fix, or lies outside the supported matrix', sources: [{ name: 'W3C WCAG 2.2', url: 'https://www.w3.org/TR/WCAG22/' }, { name: 'MDN Responsive Design', url: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design' }, { name: 'W3C Planning and Managing Web Accessibility', url: 'https://www.w3.org/WAI/planning/' }] },
  { slug: 'offshore-developer-import-reconciliation-research-2026-08-18', title: 'Import reconciliation evidence for distributed software teams', question: 'After an import reports success, can an owner prove what entered the system and what did not?', unit: 'one structured data import from source file through accepted, rejected, and reconciled records', evidence: 'source count, accepted count, rejected reasons, duplicate treatment, target totals, and correction trace', decision: 'whether to accept the batch, retry corrected rows, reverse it, or hold for owner review', sources: [{ name: 'NIST Data Integrity Guidance', url: 'https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final' }, { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'OWASP Input Validation Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html' }] },
  { slug: 'offshore-developer-service-handoff-research-2026-08-18', title: 'Service handoff completeness across Philippines-based engineering teams', question: 'What makes a technical handoff actionable when the next owner is offline or unfamiliar with the change?', unit: 'one completed development task transferred from implementer to the next operational or technical owner', evidence: 'current state, changed paths, verification, known limits, rollback or recovery, and next decision', decision: 'whether the receiving owner can accept the handoff, request evidence, or stop the change', sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'Google SRE Workbook', url: 'https://sre.google/workbook/table-of-contents/' }, { name: 'Atlassian Agile Ceremonies', url: 'https://www.atlassian.com/agile/scrum/ceremonies' }] },
];

const paragraph = (s: Spec, focus: string) => `${s.question} ${s.unit} is the boundary for this report, rather than an entire engineering organization or a claim about every offshore arrangement. The evidence is ${s.evidence}. This matters for DeveloperOffshore.com because a distributed developer should be judged on an observable software outcome, not on hours online or a confident status update. ${focus} The internal technical or product owner retains architecture, production approval, security exceptions, and accepted-risk decisions. A developer can collect the evidence, make a bounded change, and state what was not tested; that separation keeps a Philippines-based contributor useful without pretending that implementation ownership is the same as business accountability.`;

function makePost(s: Spec): ResearchPost {
  const sections = [
    { heading: 'Research question and evidence scope', body: [paragraph(s, 'The research question is deliberately practical: what can another reviewer verify after the handoff, and what remains an interpretation? Published guidance supplies principles, not a local success guarantee. The report therefore separates observed facts, assumptions about the product, and analysis about the next decision.') ] },
    { heading: 'Method and measurement design', body: [paragraph(s, `Measure the unit at its boundaries: before work, during the relevant failure or change, and after verification. Preserve the revision, environment, cohort, and denominator. For this topic, ${s.evidence} should be recorded with both successful and rejected cases. A clean example is useful, but a boundary trace is usually more revealing because it shows whether the control survives delay, interruption, malformed input, or an unavailable reviewer.`)] },
    { heading: 'What the sources support', body: [paragraph(s, 'The external sources support repeatable evidence, least privilege, explicit security behavior, and accountable review. They do not establish that a particular team, vendor, framework, or staffing model will deliver a fixed result. Their value is narrower: they give the reviewer language for asking whether a control exists, whether it is testable, and whether its limitations are visible. Vendor documentation can explain mechanics; standards and public guidance are stronger for framing responsibilities and risk.') ] },
    { heading: 'Niche-specific analysis', body: [paragraph(s, `For a Philippines-based development team, the time-zone question is not whether every decision happens synchronously. It is whether a written artifact lets the next owner continue safely. ${s.decision} should be decided from the recorded evidence, not from the number of tickets closed. A small overlap window is best reserved for unresolved choices, while normal implementation can proceed asynchronously when the brief, access boundary, acceptance check, and escalation route are explicit.`)] },
    { heading: 'Failure cases and counterevidence', body: [paragraph(s, 'A credible investigation looks for counterevidence. Check the path that times out, is retried, is denied, contains an unexpected version, or reaches a reviewer with less context than the author. Compare a normal case with a negative fixture and, where relevant, an interruption or recovery trace. If the result changes with data volume, browser, identity, dependency, or release revision, record that condition. A green aggregate or polished screenshot cannot prove behavior outside the observed boundary.') ] },
    { heading: 'Role boundary and operating implication', body: [paragraph(s, 'The developer role is to prepare a focused implementation or investigation, keep the source of truth current, and hand over reproducible evidence. The client-side owner decides whether the result meets the product threshold and whether residual risk is acceptable. This boundary is especially important when work crosses Philippine and buyer-team hours: written assumptions reduce waiting, while named escalation prevents silent decisions. The useful artifact is concise enough to review and complete enough to challenge.') ] },
    { heading: 'Limitations', body: [paragraph(s, 'This is a bounded synthesis, not a controlled experiment, certification, legal conclusion, or claim about a company’s private results. A small sample can miss rare failures; documented behavior can differ from deployed behavior; and external guidance may not fit an unusual architecture. The report cannot infer facts that were not measured. State the observation period, supported cohorts, excluded cases, and unresolved questions. If no baseline exists, say so instead of manufacturing a benchmark.') ] },
    { heading: 'Evidence-led conclusion', body: [paragraph(s, `The evidence-led conclusion is conditional: ${s.decision} only after the owner can inspect the stated unit, its normal and boundary behavior, and the limitations of the sample. The recommended next step is one representative slice with a named reviewer, explicit stop rule, and durable handoff. If the evidence is incomplete, the correct conclusion is not “safe” or “unsafe” in the abstract; it is that a specific decision remains open. That honesty is the practical advantage of research-led offshore development: it makes technical judgment reviewable across people, systems, and time zones.`)] },
  ];
  return { slug: s.slug, title: s.title, excerpt: `${s.title} examines ${s.question.toLowerCase()} using a bounded software unit, explicit evidence, and a named decision owner.`, published: '2026-08-18', sections, keyStats: ['3 claim-relevant external sources reviewed', '1 bounded unit with normal and boundary cases', 'Evidence separated from analysis and owner decision'], takeaways: [`Measure ${s.evidence}.`, 'Preserve the environment, revision, and denominator.', 'Keep production and accepted-risk decisions with the accountable owner.', 'Record limitations before expanding scope.'], faqs: [{ question: 'What should a reviewer request?', answer: `Request the source revision, the observed unit, normal and boundary evidence, and an explicit statement of what remains untested for ${s.title.toLowerCase()}.` }, { question: 'Does this research prove one staffing model is best?', answer: 'No. It provides a bounded evidence model for distributed software work; local architecture, reviewer capacity, and product risk still determine the decision.' }], related: [{ title: 'Research library', href: '/research' }, { title: 'Developer handoff guides', href: '/blog' }], sources: s.sources };
}

export const august18ResearchBatch: readonly ResearchPost[] = specs.map(makePost);
export const august18ResearchManifest = specs.map((s) => ({ slug: s.slug, route: `/research/${s.slug}`, sourcePath: 'app/aug18-research-batch.ts', sourceDate: '2026-08-18', sourceDateField: 'published' }));
