import type { BlogPost, BlogSection } from './data';

type August17Record = {
  slug: string;
  title: string;
  audience: string;
  decision: string;
  checks: string;
  failure: string;
  owner: string;
  datePublished: '2026-08-17';
};

const records: August17Record[] = [
  { slug: 'offshore-developer-backlog-refinement-2026-08-17', title: 'How an offshore developer can make backlog refinement more useful', audience: 'product and engineering leads with tickets that are not ready for distributed delivery', decision: 'which unknowns must be answered before a contributor starts', checks: 'acceptance examples, dependencies, data assumptions, and a named reviewer', failure: 'using refinement to hide unresolved product decisions', owner: 'product owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-pull-request-review-window-2026-08-17', title: 'Designing a pull-request review window for an offshore developer', audience: 'teams coordinating reviews across a Philippines and buyer-team schedule', decision: 'when a change is ready for review and what happens when the window is missed', checks: 'review SLA, escalation path, CI status, and handoff note', failure: 'leaving contributors blocked behind an informal reviewer queue', owner: 'engineering lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-bug-triage-boundary-2026-08-17', title: 'A practical bug-triage boundary for offshore developers', audience: 'support and engineering teams receiving customer-reported defects', decision: 'which reports can be reproduced and fixed versus escalated as product decisions', checks: 'reproduction steps, environment, severity, logs, and expected behavior', failure: 'treating every report as an implementation ticket', owner: 'support engineering lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-release-candidate-checklist-2026-08-17', title: 'What to include in an offshore developer release-candidate checklist', audience: 'release owners who need evidence before a distributed team change is approved', decision: 'whether the candidate is ready for the final internal approval', checks: 'changed paths, regression coverage, known limits, and rollback notes', failure: 'confusing a green build with a complete release review', owner: 'release owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-code-ownership-handoff-2026-08-17', title: 'How to transfer code ownership to an offshore developer safely', audience: 'engineering managers expanding a contributor’s responsibility in an existing codebase', decision: 'which boundaries can be owned now and which still require pairing', checks: 'module map, review rights, runbook, test coverage, and escalation contact', failure: 'assigning ownership without transferring context or authority', owner: 'technical lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-sprint-demo-evidence-2026-08-17', title: 'Make an offshore developer sprint demo prove the right thing', audience: 'product teams using demos to review work completed across time zones', decision: 'which user outcome and limitation the demo must make visible', checks: 'representative scenario, changed behavior, test evidence, and open decision', failure: 'rewarding a polished walkthrough that avoids edge cases', owner: 'product manager', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-technical-discovery-spike-2026-08-17', title: 'Scoping a technical discovery spike for an offshore developer', audience: 'teams facing an unfamiliar integration or code path before committing delivery work', decision: 'what the spike must learn and what it must explicitly not build', checks: 'question, experiment, evidence, constraints, and recommendation', failure: 'letting a discovery spike become an unreviewed prototype', owner: 'engineering manager', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-qa-defect-reproduction-2026-08-17', title: 'A better defect-reproduction handoff for offshore QA work', audience: 'QA leads whose developers lose time reconstructing intermittent failures', decision: 'what evidence is sufficient to move a defect into implementation', checks: 'fixture, browser or device, steps, observed result, and frequency', failure: 'sending a severity label without a reproducible case', owner: 'QA lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-documentation-freshness-2026-08-17', title: 'Keeping technical documentation fresh in an offshore delivery lane', audience: 'teams whose code changes faster than their setup and handoff documents', decision: 'which documentation must change with a code or workflow change', checks: 'owner, trigger, command output, last review, and stale-content rule', failure: 'measuring documentation by page count instead of usefulness', owner: 'documentation owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-async-decision-log-2026-08-17', title: 'Use an async decision log with an offshore developer', audience: 'distributed teams that need decisions to survive gaps in shared working hours', decision: 'what was decided, by whom, under which constraint, and when to revisit it', checks: 'options, consequence, owner, affected work, and revisit trigger', failure: 'burying architecture decisions in chat threads', owner: 'technical lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-incident-escalation-handoff-2026-08-17', title: 'Set an incident escalation handoff for offshore developers', audience: 'service teams that need contributors to surface operational risk without granting unsafe authority', decision: 'when a developer stops troubleshooting and transfers the incident', checks: 'impact, timeline, evidence, current action, and decision owner', failure: 'leaving an unfamiliar contributor alone with production ambiguity', owner: 'incident commander', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-acceptance-criteria-examples-2026-08-17', title: 'Write acceptance criteria an offshore developer can verify', audience: 'product owners translating user needs into reviewable engineering work', decision: 'what observable behavior counts as complete', checks: 'starting state, action, outcome, negative case, and evidence', failure: 'using adjectives such as fast, simple, or robust as acceptance criteria', owner: 'product owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-review-feedback-loop-2026-08-17', title: 'Build a useful review-feedback loop with an offshore developer', audience: 'engineering leads who want review comments to improve the next change', decision: 'which feedback is blocking, which is follow-up, and who resolves ambiguity', checks: 'severity, rationale, example, response, and final confirmation', failure: 'turning review into a pile of preferences with no priority', owner: 'review owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-test-failure-triage-2026-08-17', title: 'Triage failing tests without making offshore developers guess', audience: 'teams with noisy CI results and contributors working in a different time zone', decision: 'whether a failure is a code defect, environment issue, or test-maintenance task', checks: 'failure history, reproducibility, changed path, fixture, and owner', failure: 'asking someone to rerun a red build without classifying it', owner: 'CI owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-legacy-code-orientation-2026-08-17', title: 'Orient an offshore developer in a legacy codebase', audience: 'managers assigning work in systems with implicit conventions and fragile paths', decision: 'which small area can be changed safely first', checks: 'runtime map, invariants, known traps, local test, and rollback boundary', failure: 'starting with a rewrite because the system is difficult to explain', owner: 'system owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-estimation-assumptions-2026-08-17', title: 'Make offshore developer estimates expose their assumptions', audience: 'planning leads comparing delivery options for uncertain technical work', decision: 'which unknowns can change sequence, effort, or acceptance', checks: 'thin slice, dependencies, confidence, evidence needed, and review point', failure: 'treating a single number as a commitment before discovery', owner: 'planning owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-accessible-handoff-notes-2026-08-17', title: 'Write accessible handoff notes for distributed developer work', audience: 'teams that need another engineer to continue work without a live meeting', decision: 'what context must be explicit for the next person to act', checks: 'plain-language summary, links, commands, expected output, and open risk', failure: 'assuming the reader can infer context from a ticket title', owner: 'delivery lead', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-small-change-release-2026-08-17', title: 'When a small change still needs an offshore developer release plan', audience: 'teams tempted to bypass review because a code change looks minor', decision: 'which surface, dependency, and recovery checks still apply', checks: 'blast radius, test path, observability, approval, and rollback', failure: 'using line count as a proxy for release risk', owner: 'release owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-scope-change-escalation-2026-08-17', title: 'Handle scope changes before they derail offshore developer work', audience: 'product and engineering managers managing requests that appear during implementation', decision: 'whether to accept, defer, split, or reject the new request', checks: 'original outcome, impact, dependency, approval, and revised handoff', failure: 'adding work informally until the original acceptance test no longer matters', owner: 'delivery manager', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-code-review-evidence-2026-08-17', title: 'Choose code-review evidence for an offshore developer change', audience: 'reviewers who need a compact way to assess behavior beyond the diff', decision: 'which proof is proportional to the changed risk', checks: 'focused tests, screenshots, logs, fixture, and known limitation', failure: 'demanding generic evidence that does not exercise the changed path', owner: 'code reviewer', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-knowledge-transfer-plan-2026-08-17', title: 'Plan knowledge transfer when an offshore developer joins a new lane', audience: 'engineering managers introducing a contributor to a specialized product area', decision: 'what knowledge should be demonstrated, documented, or paired', checks: 'workflow map, representative task, questions, owner, and sign-off', failure: 'calling a single orientation meeting a complete transfer', owner: 'onboarding owner', datePublished: '2026-08-17' },
  { slug: 'offshore-developer-weekly-delivery-report-2026-08-17', title: 'A useful weekly delivery report for offshore developer work', audience: 'managers who need a concise view of outcomes, quality, blockers, and next decisions', decision: 'what the team should continue, change, or escalate next week', checks: 'completed outcomes, review status, defects, blockers, and ownership', failure: 'reporting hours or ticket counts without explaining delivery risk', owner: 'delivery manager', datePublished: '2026-08-17' },
];

const section = (heading: string, body: string[], bullets?: string[]): BlogSection => ({ heading, body, bullets });

function makePost(record: August17Record): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    excerpt: `${record.audience} can use this guide to make ${record.decision} explicit. It turns ${record.checks} into a practical review boundary for an offshore developer relationship.`,
    minutes: 9,
    datePublished: record.datePublished,
    dateModified: record.datePublished,
    revision: 'august-17-2026-blog-v1',
    keyTakeaways: [`Decide ${record.decision} before work begins.`, `Collect ${record.checks}.`, `Keep ${record.owner} accountable for the final decision.`],
    sections: [
      section('Define the decision before assigning work', [`Start with the decision this article addresses: ${record.decision}. Put the user or system context, the starting state, and the expected handoff beside the first ticket. The contributor should be able to explain what evidence would change the recommendation.`, 'Keep the first slice narrow. State what is out of scope, which assumptions are provisional, and when the internal owner will review the result.'], ['Name one decision owner.', 'Use representative or synthetic data.', 'Write the stop condition before implementation.']),
      section('Make the evidence proportional to the risk', [`Ask for ${record.checks}. Each item should exercise the changed path and be easy for another reviewer to inspect. A short, reproducible proof is more useful than an activity log.`, `Choose a check that distinguishes a complete result from a plausible-looking result. For this lane, the review should answer whether ${record.decision} is now supported by evidence.`]),
      section('Keep the role boundary visible', [`The main failure mode is ${record.failure}. An offshore developer can investigate, implement, document, and surface risk; ${record.owner} retains accepted-risk, priority, and product decisions.`, 'If the work reaches credentials, customer data, an incident, an irreversible migration, or an unapproved architecture choice, pause and transfer the decision through the approved private path.']),
      section('Close with a durable handoff', [`End with what changed, what was checked, what remains uncertain, and who owns the next action. Link the relevant code, fixture, ticket, or record so the next person can continue without reconstructing the conversation.`, 'If the first slice is sound, expand one adjacent path at a time. Keep the same owner, evidence standard, and written boundary as scope grows.']),
    ],
    relatedLinks: [
      { label: 'Review the first-week onboarding checklist', href: '/blog/offshore-developer-first-week-onboarding-checklist', note: 'Start with one safe contribution and only the access it requires.' },
      { label: 'Explore developer services', href: '/services', note: 'Match the work lane with an internal reviewer.' },
      { label: 'Plan the role', href: '/contact-us', note: 'Bring the stack, outcome, schedule, and review owner.' },
    ],
    faqs: [
      { question: 'Who accepts the result?', answer: `The named ${record.owner} accepts the outcome, evidence, and any exception. The contributor supplies the work and surfaces limitations.` },
      { question: 'What belongs in the first slice?', answer: 'One representative path, explicit acceptance criteria, the smallest safe access scope, and a scheduled review.' },
    ],
    sources: [
      { name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final', note: 'Used for evidence and ownership boundaries.' },
      { name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/', note: 'Used for review framing.' },
    ],
  };
}

export const august17BlogBatch: BlogPost[] = records.map(makePost);
