import type { BlogPost, BlogSection } from './data';

type August14Record = {
  slug: string;
  title: string;
  audience: string;
  result: string;
  craft: string;
  proof: string;
  boundary: string;
  datePublished: '2026-08-14';
};

const section = (heading: string, body: string[], bullets?: string[]): BlogSection => ({ heading, body, bullets });

const records: August14Record[] = [
  { slug: 'offshore-developer-react-native-release-brief-2026-08-14', title: 'How to brief an offshore developer on a React Native release', audience: 'mobile teams preparing a React Native change for both major platforms', result: 'a release candidate whose platform differences are known before approval', craft: 'native modules, permissions, deep links, offline states, and store-ready behavior', proof: 'a device matrix with build notes and a tested recovery path for interrupted updates', boundary: 'treating one simulator run as evidence for every supported device', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-graphql-schema-evolution-2026-08-14', title: 'A practical brief for GraphQL schema evolution', audience: 'product teams changing a GraphQL contract used by several clients', result: 'a compatible schema change with consumer impact made visible', craft: 'nullability, field ownership, resolver behavior, deprecation, and generated types', proof: 'old-client and new-client fixtures plus a clear removal condition', boundary: 'renaming or tightening a field before finding every consumer', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-frontend-state-management-2026-08-14', title: 'How to scope frontend state-management work offshore', audience: 'frontend leads reducing tangled state in a growing application', result: 'a smaller state boundary that preserves loading, error, and refresh behavior', craft: 'server state, local state, cache ownership, optimistic updates, and reset rules', proof: 'a state transition map and tests for stale, failed, and repeated actions', boundary: 'moving data into a global store because local ownership is inconvenient', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-microfrontend-boundaries-2026-08-14', title: 'A reviewable microfrontend boundary assignment', audience: 'web platform teams deciding whether a product needs independently delivered UI', result: 'an explicit boundary with shared dependencies and failure behavior documented', craft: 'runtime loading, routing, design tokens, ownership, and version compatibility', proof: 'a small integration in a representative shell with an isolation fallback', boundary: 'adding runtime complexity without a team or release reason that justifies it', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-event-driven-contracts-2026-08-14', title: 'How to assign event-driven integration work', audience: 'backend teams introducing events between independently owned services', result: 'an event contract that handles duplicates, delays, and schema changes', craft: 'envelopes, ownership, ordering, idempotency, retention, and consumer recovery', proof: 'contract fixtures for old and new payloads with duplicate-delivery tests', boundary: 'assuming an event bus makes delivery order or business correctness automatic', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-search-relevance-tuning-2026-08-14', title: 'How to scope search-relevance tuning with an offshore developer', audience: 'product teams improving search without losing trust in results', result: 'a measured relevance change tied to real queries and a rollback signal', craft: 'query classes, ranking signals, synonyms, empty results, and evaluation sets', proof: 'a labeled query sample with before-and-after judgments and failure examples', boundary: 'optimizing a handful of impressive queries while degrading common searches', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-file-upload-security-2026-08-14', title: 'A safer file-upload security assignment', audience: 'application teams accepting customer documents or media', result: 'an upload path with bounded files, isolated processing, and clear rejection states', craft: 'content checks, size limits, storage keys, malware scanning, and access control', proof: 'fixtures for type spoofing, oversized files, private objects, and failed scans', boundary: 'trusting a filename or browser-provided content type as a security decision', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-billing-integration-boundaries-2026-08-14', title: 'How to brief an offshore developer on billing integration boundaries', audience: 'product teams connecting subscription or invoicing behavior to an application', result: 'a tested billing handoff that keeps financial decisions with the product owner', craft: 'webhook reconciliation, entitlement state, retries, refunds, and audit records', proof: 'fixtures for delayed, repeated, and disputed events with an operator review path', boundary: 'letting a payment callback silently become the sole source of customer access truth', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-multi-tenant-isolation-review-2026-08-14', title: 'A practical multi-tenant isolation review for offshore developers', audience: 'SaaS teams checking that one customer cannot cross into another customer’s data', result: 'tenant boundaries that are enforced and tested at the right layers', craft: 'request context, query scoping, background jobs, caches, and administrative paths', proof: 'cross-tenant denial fixtures plus a review of asynchronous and export flows', boundary: 'relying on a UI filter when the data layer does not enforce ownership', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-feature-flag-cleanup-2026-08-14', title: 'How to scope feature-flag cleanup work', audience: 'engineering teams carrying old release switches in production code', result: 'retired flags with behavior preserved and obsolete configuration removed', craft: 'flag inventory, exposure paths, default behavior, migration order, and tests', proof: 'a flag-to-code map and checks for every supported state before deletion', boundary: 'deleting a flag because it looks old without confirming its owner and audience', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-graphql-cache-policy-2026-08-14', title: 'A bounded GraphQL caching assignment', audience: 'client teams improving perceived speed in a GraphQL application', result: 'cache behavior that is fast without showing the wrong entity or stale permission', craft: 'identity keys, normalization, invalidation, pagination, and logout behavior', proof: 'tests for edits, account changes, pagination, and a cold-cache fallback', boundary: 'treating a cache hit as correct without checking identity and freshness', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-websocket-reconnection-2026-08-14', title: 'How to brief an offshore developer on WebSocket reconnection', audience: 'product teams supporting live updates in a browser application', result: 'a reconnecting client that does not duplicate actions or lose important state', craft: 'connection states, backoff, authentication refresh, replay, and user feedback', proof: 'network interruption fixtures with a message sequence that can be inspected', boundary: 'hiding a broken connection behind an endless spinner or aggressive retries', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-legacy-api-modernization-2026-08-14', title: 'A reviewable legacy-API modernization plan', audience: 'teams improving an older API while existing clients still depend on it', result: 'one modernized path with compatibility and retirement evidence', craft: 'contract inventory, adapters, observability, migration slices, and fallbacks', proof: 'captured old-client behavior and a side-by-side result for the selected slice', boundary: 'rewriting the service before understanding the clients and operational behavior', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-orm-query-review-2026-08-14', title: 'How to assign an ORM query review', audience: 'backend teams investigating slow or surprising database access in application code', result: 'query behavior that is correct, explainable, and measured on representative data', craft: 'eager loading, joins, pagination, transactions, indexes, and query counts', proof: 'generated SQL, plan output, fixture sizes, and a regression guard for the original issue', boundary: 'adding eager loading everywhere and moving the performance problem elsewhere', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-design-to-code-handoff-2026-08-14', title: 'A useful design-to-code handoff for offshore frontend work', audience: 'design and engineering teams turning a chosen interface into maintainable UI', result: 'a coded flow that reflects intended states without inventing product decisions', craft: 'responsive rules, content states, tokens, empty states, and interaction details', proof: 'annotated screens matched to a component and state checklist', boundary: 'treating a screenshot as complete specification for behavior and accessibility', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-technical-decision-records-2026-08-14', title: 'How to use an offshore developer to improve technical decision records', audience: 'engineering leads whose important choices are scattered across tickets and chat', result: 'short decision records that preserve context, alternatives, and ownership', craft: 'problem framing, constraints, options, consequences, status, and revisit triggers', proof: 'one decision rewritten from a live project with links to the affected code and owner', boundary: 'turning a decision record into a substitute for approval or an unreviewed architecture mandate', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-error-handling-consistency-2026-08-14', title: 'A practical error-handling consistency review', audience: 'application teams trying to make failures understandable across several routes or services', result: 'consistent failure behavior that helps users and preserves diagnostic context', craft: 'error taxonomy, safe messages, correlation IDs, retries, and boundary logging', proof: 'a matrix covering validation, authorization, dependency, and unexpected failures', boundary: 'showing internal exceptions to customers or flattening every failure into one status', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-progressive-web-app-offline-2026-08-14', title: 'How to scope progressive-web-app offline behavior', audience: 'web teams deciding which user journeys should work through a temporary connection loss', result: 'an offline boundary users can understand with safe synchronization behavior', craft: 'service-worker scope, cached assets, queued actions, conflict handling, and recovery', proof: 'offline and reconnect scenarios for the one journey selected for the first slice', boundary: 'promising a fully offline product when the data and conflict model cannot support it', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-data-export-compliance-2026-08-14', title: 'A bounded data-export implementation brief', audience: 'product teams adding a customer-facing export of account data', result: 'an export that is complete enough for its stated purpose and protected in transit and storage', craft: 'field inventory, authorization, asynchronous jobs, expiry, audit events, and format choices', proof: 'an account fixture with included, excluded, and expired-download cases', boundary: 'including every database field simply because it is technically available', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-observability-dashboard-design-2026-08-14', title: 'How to brief an offshore developer on an observability dashboard', audience: 'service owners who need a dashboard that supports an actual operating decision', result: 'a small dashboard that distinguishes user impact from infrastructure noise', craft: 'service indicators, dimensions, time windows, annotations, and alert context', proof: 'a dashboard walkthrough using a known incident-shaped scenario and a false-positive review', boundary: 'adding charts without a question, threshold, or person responsible for acting', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-frontend-form-state-2026-08-14', title: 'A focused frontend form-state assignment', audience: 'product teams with complex forms that lose user input or explain errors poorly', result: 'a form that preserves intent across validation, retries, and partial failure', craft: 'field ownership, touched state, async validation, draft recovery, and accessible errors', proof: 'fixtures for invalid input, refresh, duplicate submit, and server-side rejection', boundary: 'disabling the whole form when only one field or one request needs attention', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-test-data-management-2026-08-14', title: 'How to assign test-data management work', audience: 'engineering teams whose tests are slow, coupled, or difficult to reproduce', result: 'representative test data that is isolated, explainable, and safe to refresh', craft: 'fixtures, factories, anonymization, cleanup, ownership, and environment parity', proof: 'a repeatable setup from a clean state with a documented data dependency map', boundary: 'copying customer records into a test environment because they are convenient', datePublished: '2026-08-14' },
  { slug: 'offshore-developer-frontend-bundle-analysis-2026-08-14', title: 'A useful frontend bundle-analysis assignment', audience: 'web teams looking for a concrete reduction in the cost of a critical route', result: 'a smaller route payload with behavior and cache assumptions still intact', craft: 'dependency graph, code splitting, asset formats, import boundaries, and measurement', proof: 'before-and-after reports from the same route, device profile, and build mode', boundary: 'chasing a bundle number while moving work into a slower runtime path', datePublished: '2026-08-14' },
];

function makePost(record: August14Record): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    excerpt: `${record.audience} can use this guide to reach ${record.result}. It explains ${record.craft} and keeps the review boundary visible for a Philippines-based developer relationship.`,
    minutes: 10,
    datePublished: record.datePublished,
    dateModified: record.datePublished,
    revision: 'august-14-2026-blog-v1',
    keyTakeaways: [`Define ${record.result} before implementation.`, `Make ${record.proof} part of acceptance.`, `Keep final technical and risk decisions with the named internal owner.`],
    sections: [
      section('Start with an observable result', [`A sound brief for ${record.audience} names the behavior that should be different when the work is complete: ${record.result}. Write the affected users, starting condition, acceptance check, and reviewer beside the first ticket.`, 'Keep the first slice narrow enough that another engineer can understand the change in one review. State what is deliberately out of scope so a useful implementation does not quietly become an architecture project.'], ['Name the internal reviewer.', 'Use representative or synthetic data.', 'Set the review point before the work begins.']),
      section(`Shape the assignment around ${record.craft}`, [`Break the work into checks that support the result rather than a list of technologies. For this lane, the important questions are how ${record.craft} affect behavior, ownership, and the next handoff.`, `Ask the developer to produce ${record.proof}. That evidence should be tied to the changed path, not presented as a generic activity report.`]),
      section('Make access and decisions explicit', ['Begin with named accounts and the smallest repository, environment, and data scope needed for the first slice. Architecture choices, production approval, security exceptions, and accepted risk remain with the buyer-side owner.', `The main caution is ${record.boundary}. If the work reaches that boundary, pause the normal implementation and ask the named owner to decide the safe next action.`], ['Write one stop rule for sensitive or irreversible changes.', 'Record assumptions beside the pull request.', 'Keep unresolved questions assigned to a person.']),
      section('Review evidence before widening scope', [`Review the changed behavior, the evidence, the known limitation, and the handoff in that order. The goal is to confirm ${record.result}, not merely to confirm that code or configuration changed.`, 'If the first slice is sound, expand one related path at a time and keep the same evidence standard. That makes a distributed working relationship easier to manage across time zones and easier for the internal team to own.']),
    ],
    relatedLinks: [
      { label: 'Read the first-week onboarding guide', href: '/blog/offshore-developer-first-week-onboarding-checklist', note: 'Start with one safe contribution and only the access it needs.' },
      { label: 'Review developer services', href: '/services', note: 'Match the technical lane with an internal reviewer.' },
      { label: 'Plan the role', href: '/contact-us', note: 'Bring the stack, first outcome, schedule, and review owner.' },
    ],
    faqs: [
      { question: 'Who accepts the result?', answer: 'The named internal reviewer accepts the outcome, evidence, and documented limitation. The developer supplies the work and surfaces risks.' },
      { question: 'What belongs in the first slice?', answer: 'One representative path, explicit acceptance criteria, the smallest safe access scope, and a review date. Add adjacent work only after the first result is understood.' },
    ],
    sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final', note: 'Used for evidence and ownership boundaries.' }, { name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/', note: 'Used for review framing.' }],
  };
}

export const august14BlogBatch: BlogPost[] = records.map(makePost);
