import type { BlogPost, BlogSection } from './data';

type Entry = { slug: string; title: string; excerpt: string; decision: string; audience: string; stack: string; beats: string[] };

const entries: Omit<Entry, 'datePublished'>[] = [
  { slug: 'offshore-developer-acceptance-criteria-workshop-2026-08-23', title: 'How an offshore developer can turn vague tickets into acceptance criteria', excerpt: 'A practical workshop for converting ambiguous backlog language into reviewable software work.', decision: 'what “done” means for the first implementation slice', audience: 'product and engineering leads with tickets that need repeated clarification', stack: 'the backlog, repository, design references, test harness, and decision log', beats: ['Separate the requested outcome from the proposed solution.', 'Ask for observable behavior before discussing implementation.', 'Write examples for normal, empty, denied, and failed states.', 'Mark assumptions that need a product owner rather than a developer.', 'Use a small example to expose missing vocabulary.', 'Check whether the acceptance case can be tested without hidden context.', 'Keep non-goals beside the ticket so scope does not expand silently.', 'Let the developer propose questions while the owner chooses product meaning.', 'Review the first completed slice against the original examples.', 'Turn recurring clarification into a reusable intake prompt.'] },
  { slug: 'offshore-developer-frontend-accessibility-audit-2026-08-23', title: 'A reviewable accessibility audit brief for an offshore frontend developer', excerpt: 'How to scope keyboard, semantic, focus, and assistive-technology checks around one real product flow.', decision: 'which accessibility risks the selected user journey must address before review', audience: 'frontend leads improving a customer-facing flow without making unsupported compliance claims', stack: 'the component library, browser matrix, automated checks, and representative states', beats: ['Choose a journey rather than auditing an entire application at once.', 'Record the intended interaction order before inspecting markup.', 'Check names, roles, values, and visible focus on the actual states.', 'Include keyboard-only paths and a meaningful failure state.', 'Treat automated output as a signal that needs human interpretation.', 'Test responsive and zoomed views where layout changes interaction.', 'Keep content, design, and engineering decisions distinguishable.', 'Give the contributor a safe fix boundary and a review owner.', 'Capture skipped checks and unavailable assistive technology explicitly.', 'Schedule a focused regression check when the component changes again.'] },
  { slug: 'offshore-developer-cache-invalidation-review-2026-08-23', title: 'How to assign an offshore developer a cache-invalidation review', excerpt: 'A bounded way to investigate stale data, identity boundaries, and safe freshness behavior.', decision: 'where cached data may be reused and what event makes it untrustworthy', audience: 'application teams seeing stale reads after edits, permission changes, or deploys', stack: 'the application, cache layer, API contract, fixtures, and observability tools', beats: ['Name the user-visible symptom instead of starting with cache settings.', 'Map producers, readers, keys, expiry, and invalidation events.', 'Compare a cold read with a warm read using the same fixture.', 'Test edits, logout, tenant changes, and permission changes separately.', 'Record whether freshness or latency is the actual decision.', 'Avoid clearing every key when a narrower boundary is available.', 'Make duplicate invalidation and delayed events observable.', 'Keep data ownership and authorization decisions with the internal owner.', 'Add a regression case for the stale result that started the review.', 'Document the recovery action when freshness cannot be proven.'] },
  { slug: 'offshore-developer-background-job-retry-policy-2026-08-23', title: 'A safe background-job retry policy assignment for an offshore developer', excerpt: 'How to reason about duplicate work, poison messages, backoff, and operator ownership before changing a worker.', decision: 'when a failed job should retry, pause, or become an explicit operator decision', audience: 'backend teams maintaining queues that touch customer or financial workflows', stack: 'the worker, queue, datastore, dead-letter path, metrics, and fixture suite', beats: ['Classify failures as temporary, permanent, or unknown.', 'Trace the side effect before changing the retry count.', 'Give every job an idempotency story or a deliberate stop point.', 'Use delayed and duplicate deliveries in the test fixture.', 'Make backoff visible to the person watching the queue.', 'Separate a safe retry from replaying an irreversible external action.', 'Define poison-message handling without hiding the original payload.', 'Keep production replay approval with the service owner.', 'Measure queue age and completion semantics, not only attempt totals.', 'Write the handoff so another shift can resume without guessing.'] },
  { slug: 'offshore-developer-logging-privacy-redaction-2026-08-23', title: 'How to brief an offshore developer on privacy-aware log redaction', excerpt: 'A concrete review boundary for reducing sensitive data in logs while preserving useful diagnostics.', decision: 'which fields can be recorded, transformed, or removed at each logging boundary', audience: 'security-conscious product teams cleaning application and support logs', stack: 'application logs, error tracking, test fixtures, access controls, and retention settings', beats: ['Inventory fields at the source rather than trusting a dashboard filter.', 'Classify values by diagnostic need and sensitivity.', 'Use synthetic records to test redaction without copying customer data.', 'Check structured fields, exception messages, and nested payloads.', 'Verify that redaction happens before transport and indexing.', 'Preserve correlation without preserving the sensitive value.', 'Give security or privacy owners the exception decisions.', 'Test denied and malformed input because errors often leak more context.', 'Inspect old and new records separately when retention is involved.', 'Record the residual risk and the trigger for reopening the review.'] },
  { slug: 'offshore-developer-release-rollback-drill-2026-08-23', title: 'A practical rollback-drill brief for an offshore developer', excerpt: 'How to rehearse recovery evidence without granting a contributor authority to release or reverse production changes.', decision: 'whether the team can recognize a bad change and recover within its stated boundary', audience: 'delivery teams that want release confidence grounded in a repeatable drill', stack: 'the build pipeline, staging environment, health signals, change record, and runbook', beats: ['Define the failure signal before beginning the exercise.', 'Choose a representative change with a safe recovery path.', 'Separate revert, forward fix, and configuration recovery.', 'Record who may stop a release and who approves the action.', 'Exercise the handoff when the original author is unavailable.', 'Check data compatibility rather than treating code reversal as universal.', 'Capture timestamps and observations without turning them into promises.', 'Keep the developer focused on preparation, evidence, and bounded execution.', 'Review what the drill could not simulate honestly.', 'Assign one runbook correction with a concrete reopen condition.'] },
  { slug: 'offshore-developer-graphql-nullability-change-2026-08-23', title: 'How to scope a GraphQL nullability change with an offshore developer', excerpt: 'A consumer-aware process for changing a GraphQL field without surprising clients or hiding partial data.', decision: 'whether a schema change preserves the contract for every known consumer', audience: 'API teams changing GraphQL types used by web, mobile, and internal clients', stack: 'the schema, generated types, consumer fixtures, gateway, and deprecation record', beats: ['List consumers before choosing a stronger type.', 'Distinguish missing data from an unavailable resolver.', 'Capture old and new responses for representative queries.', 'Check fragments, persisted queries, and generated clients.', 'Use deprecation and migration notes as compatibility tools.', 'Do not infer product fallback behavior from a type signature.', 'Keep schema ownership and release sequencing explicit.', 'Test partial errors, authorization, and resolver timeouts.', 'Name the removal condition instead of leaving deprecation indefinite.', 'Preserve a consumer-facing handoff that can be read asynchronously.'] },
  { slug: 'offshore-developer-tenant-data-export-review-2026-08-23', title: 'A bounded tenant data-export review for an offshore developer', excerpt: 'How to check completeness, authorization, expiry, and audit behavior for a multi-tenant export flow.', decision: 'what an authorized tenant export includes and how the result stays protected', audience: 'SaaS teams adding or repairing customer-facing data exports', stack: 'tenant context, export worker, object storage, audit trail, and synthetic accounts', beats: ['Define the export purpose before listing database tables.', 'Map tenant context through synchronous and asynchronous paths.', 'Use two synthetic tenants to prove separation.', 'Check authorization at request, job, download, and expiry stages.', 'Make incomplete exports distinguishable from empty exports.', 'Treat generated archives as protected data with their own lifecycle.', 'Keep legal and policy interpretation with the accountable internal owner.', 'Test repeated requests and cancelled jobs for leakage or duplication.', 'Record audit events that explain who requested and retrieved the file.', 'Write a renewal or removal trigger for the export contract.'] },
  { slug: 'offshore-developer-mobile-release-device-matrix-2026-08-23', title: 'How to build a mobile release device matrix with an offshore developer', excerpt: 'A focused testing assignment for platform differences, permissions, interrupted updates, and evidence.', decision: 'which devices and states are sufficient to support the next mobile release decision', audience: 'mobile teams that need coverage without pretending every device was tested', stack: 'the app build, supported OS list, device lab, release notes, and crash evidence', beats: ['Tie device selection to user risk and changed code paths.', 'Include permissions, deep links, offline transitions, and upgrade states.', 'Record physical and simulated coverage separately.', 'Use the same fixture and workflow across selected devices.', 'Treat platform divergence as a product question when behavior is unclear.', 'Capture screenshots, logs, build identity, and reset conditions.', 'Keep store submission and release approval outside the contributor role.', 'Test an interrupted update instead of only a clean install.', 'State uncovered device classes and the reason for the gap.', 'Turn new failures into matrix updates rather than one-off notes.'] },
  { slug: 'offshore-developer-incident-timeline-reconstruction-2026-08-23', title: 'An evidence-led incident timeline assignment for an offshore developer', excerpt: 'How to reconstruct what happened from logs, changes, and handoffs without inventing certainty.', decision: 'which events are established, inferred, or still unknown in an incident record', audience: 'engineering teams improving post-incident learning and cross-shift response', stack: 'logs, deploy records, alerts, tickets, chat exports, and the incident timeline', beats: ['Start with the user or system impact and its time reference.', 'Normalize timestamps before comparing records from different systems.', 'Separate direct observation from a plausible explanation.', 'Use change history to test rather than assume causality.', 'Mark missing telemetry as a finding, not a blank to fill.', 'Protect sensitive incident details and restrict the working record.', 'Let the contributor assemble evidence while the incident owner sets conclusions.', 'Check recovery actions and side effects after the apparent fix.', 'Write unresolved questions with an owner and a next query.', 'Use the final timeline to improve one detection or handoff routine.'] },
  { slug: 'offshore-developer-feature-estimation-range-2026-08-23', title: 'How an offshore developer can improve a feature-estimation range', excerpt: 'A disciplined way to expose dependencies, unknowns, and review capacity without turning an estimate into a promise.', decision: 'what is known enough to plan and what needs a discovery slice first', audience: 'product and engineering leads planning work across a distributed team', stack: 'the backlog, repository history, design notes, dependencies, and review calendar', beats: ['Estimate the boundary and evidence needed, not an imagined perfect solution.', 'Split unknown architecture or integration work from implementation.', 'Use repository evidence to identify hidden consumers and ownership.', 'Include review, testing, handoff, and decision latency in the range.', 'Show assumptions that would move the lower or upper bound.', 'Avoid converting a contributor’s uncertainty into a commitment.', 'Choose a spike when information has more value than another guess.', 'Keep scope authority with the product and technical owners.', 'Revisit the range when a dependency or acceptance case changes.', 'Record what the range deliberately excludes.'] },
  { slug: 'offshore-developer-secret-rotation-handoff-2026-08-23', title: 'A secure secret-rotation handoff for an offshore developer', excerpt: 'How to prepare code and verification around credential rotation while keeping secret custody and approval explicit.', decision: 'which application behavior must remain safe while a credential changes', audience: 'platform and application leads maintaining integrations with expiring credentials', stack: 'secret manager, application configuration, rotation runbook, staging, and audit logs', beats: ['Describe the integration behavior without exposing the secret.', 'Map readers, caches, workers, and restart requirements.', 'Test old, new, missing, and invalid credential states safely.', 'Check whether dual-read or overlap is required for a clean cutover.', 'Keep actual secret issuance and retrieval under the approved owner.', 'Make failed authentication distinguishable from downstream outage.', 'Record the exact non-secret identifiers and revision under test.', 'Prepare a recovery step that does not paste credentials into chat.', 'Verify removal and audit evidence after the change.', 'Write a handoff that tells the next shift when to stop.'] },
];

const datedEntries: Entry[] = entries.map((entry, index) => ({ ...entry, datePublished: (['2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23', '2026-08-23'][index] ?? '2026-08-23') as '2026-08-23' }));

const closing = (entry: Entry, beat: string, index: number) => `For ${entry.decision}, this matters because ${beat.toLowerCase()} In a Philippines-based offshore developer lane, the contributor can inspect the approved repository, create synthetic fixtures, implement the bounded technical change, and package evidence for review. The buyer-side owner retains product meaning, protected data decisions, architecture exceptions, customer impact, and release acceptance. Record the starting revision, changed paths, environment, command or interaction, expected result, observed result, skipped checks, and next authorized action. Distinguish observation, inference, recommendation, and approval. If evidence is missing, state the limitation and choose a safe independent slice instead of filling the gap with confidence. Revisit the note when the interface, dependency, workflow, ownership, or risk boundary changes.`;

function makePost(entry: Entry, index: number): BlogPost {
  const sections: BlogSection[] = entry.beats.map((beat, beatIndex) => ({
    heading: beat,
    body: [
      `${beat} Start with ${entry.decision}. ${entry.audience} should name the affected journey, current behavior, intended outcome, and the person accountable for the consequence. The offshore developer needs a bounded question and an approved working surface, not a vague request to “make it better.” Use ${entry.stack} to establish what can be inspected and what remains outside the assignment.`,
      closing(entry, beat, beatIndex),
    ],
  }));
  sections.push({ heading: 'Close with evidence and ownership', body: [
    `A useful handoff for ${entry.title.toLowerCase()} is short enough to read across a time-zone change but precise enough to repeat. List the selected case, fixture identity, revision, changed paths, checks that passed, checks that failed, and dependencies that were unavailable. Include a safe fallback for the next person. Do not turn a proposed technical option into a product decision.`,
    `Review the result against the original question, then preserve the selected option, rejected alternatives, known limits, approval owner, and condition for reopening. This is how developer offshore staffing becomes dependable delivery support: the contributor advances code, tests, measurement, and documentation while the internal team keeps authority over risk and meaning.`,
  ] });
  return { slug: entry.slug, title: entry.title, excerpt: entry.excerpt, minutes: 12, datePublished: '2026-08-23', dateModified: '2026-08-23', revision: `august-23-2026-blog-${index + 1}`, keyTakeaways: [entry.decision, 'Use representative evidence and name its limits.', 'Keep approval with the accountable owner.'], sections, relatedLinks: [{ label: 'Explore developer services', href: '/services', note: 'Match the work lane with review capacity.' }, { label: 'Discuss the role', href: '/contact-us', note: 'Bring the stack, first outcome, schedule, and reviewer.' }], faqs: [{ question: 'What can the offshore developer own?', answer: 'The developer can prepare a bounded implementation, verification, and handoff. The buyer-side owner decides the product, data, security, and release questions.' }, { question: 'What belongs in the handoff?', answer: 'Include the revision, changed paths, fixtures, expected and observed results, limits, reviewer, and next authorized action.' }], sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final', note: 'Used for evidence-led software work.' }, { name: 'OWASP Code Review Guide', url: 'https://owasp.org/www-project-code-review-guide/', note: 'Used for risk-based review boundaries.' }] };
}

export const august23BlogBatch: BlogPost[] = datedEntries.map(makePost);
