import type {BlogPost} from './data';import type {ResearchPost} from './fleet-data';const date='2026-10-08';type Spec={slug:string;title:string;excerpt:string;work:string;owner:string;decision:string};
const specs:Spec[]=[
 {slug:'offshore-developer-feature-flag-owner-conflict',title:'Resolve Feature-Flag Ownership in an Offshore Development Team',excerpt:'Preserve configuration, approval, rollout, and rollback evidence when two teams appear to own a flag.',work:'a production feature flag with conflicting owners',owner:'the product, platform, and release owners',decision:'who controls the flag and which rollout or rollback action is authorized'},
 {slug:'philippines-developer-api-contract-version-handoff',title:'Handoff an API Contract Version to a Philippines Developer',excerpt:'Connect schema, generated client, tests, deployment, and consumer acknowledgement before changing an interface.',work:'an API change whose contract version differs across producer and consumers',owner:'the API and consuming-product owners',decision:'which version becomes authoritative and how compatibility is verified'},
 {slug:'offshore-pull-request-reviewer-transfer',title:'Transfer a Pull Request Reviewer Without Losing Context',excerpt:'Keep scope, risks, unresolved comments, test evidence, and approval authority intact during reassignment.',work:'a pull request moving to a new reviewer mid-review',owner:'the code, security, and release owners',decision:'which findings remain open and who can approve the final merge'},
 {slug:'philippines-developer-secret-rotation-evidence',title:'Prepare Secret-Rotation Evidence with a Philippines Developer',excerpt:'Inventory consumers, versions, rollout state, revocation, and verification without exposing secret material.',work:'a credential rotation spanning several services and environments',owner:'security, platform, and application owners',decision:'when the new credential is verified and the old one may be revoked'},
 {slug:'offshore-database-migration-cutover-check',title:'Review an Offshore Database Migration Cutover',excerpt:'Connect schema, backfill, compatibility, monitoring, rollback, and owner decisions before production cutover.',work:'a database migration with application and data versions changing at different times',owner:'database, application, and release owners',decision:'whether cutover criteria are met and which rollback threshold applies'},
 {slug:'philippines-qa-flaky-test-quarantine-review',title:'Review Flaky-Test Quarantine with Philippines QA Support',excerpt:'Preserve failure evidence, scope, expiry, coverage risk, and owner approval before excluding an unstable test.',work:'an automated test proposed for quarantine after intermittent failures',owner:'QA, code, and release owners',decision:'whether quarantine is allowed, for how long, and what compensating check applies'},
 {slug:'offshore-observability-alert-owner-transfer',title:'Transfer an Observability Alert Owner Across Offshore Shifts',excerpt:'Preserve signal, threshold, investigation, mitigation, and current responsibility through shift change.',work:'an active alert moving between distributed engineering shifts',owner:'incident, service, and platform owners',decision:'who owns the next action and when the alert may be resolved'},
 {slug:'philippines-frontend-accessibility-regression-packet',title:'Build an Accessibility Regression Packet with a Philippines Developer',excerpt:'Capture the blocked journey, environment, assistive behavior, code change, retest, and exception owner.',work:'a frontend change that may have introduced an accessibility regression',owner:'accessibility, design-system, product, and release owners',decision:'which repair and release priority are authorized'},
 {slug:'offshore-dependency-update-transitive-risk',title:'Review Transitive Risk in an Offshore Dependency Update',excerpt:'Trace direct and transitive changes, licenses, advisories, runtime effects, tests, and rollback evidence.',work:'a package update that changes transitive dependencies and runtime behavior',owner:'application, security, legal, and release owners',decision:'whether the dependency set is acceptable for release'},
 {slug:'philippines-developer-environment-drift-check',title:'Check Environment Drift with a Philippines Developer',excerpt:'Compare configuration, image, schema, feature, and runtime versions without copying production secrets.',work:'a defect reproduced in one environment but not another',owner:'platform, application, security, and release owners',decision:'which difference explains the behavior and what correction is approved'},
 {slug:'offshore-job-retry-idempotency-review',title:'Review Job-Retry Idempotency with an Offshore Developer',excerpt:'Map duplicate delivery, state transitions, external effects, deduplication, and repair before enabling retries.',work:'a background job that may execute more than once after failure',owner:'application, data, product, and operations owners',decision:'which effects must be idempotent and how duplicates are reconciled'},
 {slug:'philippines-mobile-release-signing-handoff',title:'Handoff Mobile Release Signing to a Philippines Development Team',excerpt:'Keep artifact identity, signing authority, store configuration, approval, and published-build verification connected.',work:'a mobile release whose artifact and signing workflow cross teams',owner:'mobile, security, and release owners',decision:'which artifact is authorized for signing and publication'}
];
for(const spec of specs) spec.excerpt+=` Published October 8, 2026.`;
const paras=(s:Spec)=>[
 `Distributed software work becomes unreliable when ${s.work} is handled through memory or private chat. Open one controlled engineering record and capture repository, service, environment, issue, commit or artifact identifiers, observed state, dates, and exact unresolved question. Preserve logs, configuration references, test output, and source versions before rerunning or editing. A screenshot can support review, but a reproducible command, immutable artifact, event ID, or versioned record is stronger. The objective is not a neat ticket; it is evidence of what the developer observed and what the systems contained at that time.`,
 `State authority at intake. ${s.owner} must decide ${s.decision}. A Philippines-based developer may reproduce behavior, prepare code, tests, diffs, runbooks, and rollback evidence, then route the bounded decision. The developer should not broaden production access, expose secrets, waive security or accessibility findings, change a public contract, approve their own high-risk exception, or deploy outside the release rule. Naming the owner prevents technical preparation from becoming unauthorized product or risk acceptance.`,
 `Build a source register for requirements, architecture decisions, issue history, code commit, dependency lockfile, schema, configuration, deployment artifact, logs, tests, approvals, and documentation. Record owner, identifier, version, environment, retrieval time, and permitted use. Keep observed and normalized values separate. Similar filenames, tags, test names, or image labels are comparison signals, not proof that artifacts are identical. Mark generated or mutable evidence that can change after the review.`,
 `Protect credentials and customer data. Reference secret versions, vault paths, masked tokens, synthetic fixtures, and controlled logs instead of copying values into tickets. Minimize production data in debugging and use approved redaction. If reproduction requires a customer record, privileged log, signing key, or production mutation, stop and involve the security or system owner. Evidence collection does not authorize broader access, and a successful workaround does not justify leaving temporary permissions active.`,
 `Reconstruct chronology across request, branch, review, test, build, deploy, runtime, alert, rollback, and verification events. Retain original timestamps and timezones, then normalize UTC for comparison. Identify actor or automation and resulting state. Current main branch, latest image, or final dashboard cannot prove what existed during an earlier decision. Preserve failed builds, superseded commits, rejected deployments, and reversals because they explain why state changed and which evidence reviewers had.`,
 `Create a comparison matrix for requirement, code version, API or schema version, configuration, dependency set, environment, test result, artifact digest, approval, and runtime observation. Cite every value. Classify rows as aligned, different, missing, superseded, not applicable, or owner interpretation required. Do not edit evidence to make systems agree. Formatting can be normalized, but a different contract, artifact, permission, customer effect, release scope, or risk decision needs the named owner.`,
 `Define stop conditions before implementation continues. Stop for uncertain artifact identity, missing rollback, production-only access without approval, secret exposure, unresolved destructive migration, unknown external effect, incompatible contract, failed security control, or absent release authority. Record affected scope, evidence checked, owner, temporary safeguard, and next review. “Blocked” without this detail wastes overlap time and encourages unsafe improvisation by the next shift.`,
 `Prepare one bounded handoff. Summarize what reproduces, what differs, tests run, limitations, open risks, rollback state, and requested decision. Ask ${s.owner}: ${s.decision}? Link commits, artifacts, logs, test runs, source register, chronology, and comparison. Include operational urgency without treating it as approval. A backup reviewer should reproduce the technical facts from retained evidence, and the owner should decide without asking the original developer to reconstruct private context.`,
 `Use precise states such as reproduction pending, evidence missing, contract conflict, test failing, security review pending, owner decision pending, implementation ready, deployment pending, verification pending, or disposition recorded. If ownership transfers, retain old and new owners, time, current hypothesis, open actions, artifacts, and acknowledgement. A reassigned issue is not complete. Transfer is an engineering event that needs evidence, especially when work crosses timezones or repositories.`,
 `After an authorized decision, verify the implemented outcome against the intended commit, artifact, environment, and user-visible behavior. Capture approver, time, reason, deployment identifier, configuration version, checks, monitoring window, and rollback readiness. A green pipeline alone is not proof when it may test or deploy the wrong artifact. Preserve before-and-after evidence and append corrections rather than rewriting the record used by earlier reviewers.`,
 `Close only when the original question has an attributable disposition and every residual risk has an owner. Check old branches, queued builds, feature flags, stale credentials, duplicate jobs, temporary permissions, alerts, documentation, and downstream consumers. Communicate external impact only with approved wording. If production behavior is not yet confirmed, state what was verified and what remains monitored instead of turning deployment success into a promise of business outcome.`,
 `Measure quality without rewarding risky speed. Useful measures include reproducibility, source completeness, review agreement, escaped regression, rollback readiness, reopened work, repeated failure cause, and verification mismatch. Do not rank developers by merges or closed tickets alone. A controlled stop can be correct. Publish definitions, denominators, exclusions, and observation windows so leaders distinguish process evidence from a polished but unstable velocity number.`,
 `Test the workflow with an ordinary change, missing evidence, environment conflict, urgent defect, owner transfer, and post-approval source change. Give a backup reviewer only retained materials and ask for scope, chronology, comparison, stop condition, decision, and result. Repair the runbook wherever private memory or local state was required. A process is not repeatable merely because its original developer remembers the terminal commands.`,
 `Run calibration with the same normal, ambiguous, security-sensitive, and rollback cases. Compare evidence and reasoning, not only conclusions. Apparent agreement can hide different assumptions. Record disagreement, adjudication, and approved examples. If a rule changes, retain the old version and identify open work requiring reconsideration instead of applying new interpretation backward. Review the workflow after platform, product, staffing, or release-policy changes.`,
 `Finish with an action register linking recurring defects to mechanism, owner, evidence, target date, acceptance test, and post-change observation. Logging gaps, unclear ownership, mutable artifacts, missing fixtures, and inconsistent release rules need different remedies. Training is not the default when interfaces or authority maps are unclear. Developers prepare reproducible evidence; accountable technical and business owners approve scope, production change, exceptions, and risk.`
 ,`A daily engineering handoff should remain concise and decision-ready: commits and artifacts reviewed, checks passed, failures by evidence state, oldest blocked item, owner decisions needed, deployments paused, monitoring in progress, and next verification. Counts must reconcile to the actual queue and link to controlled evidence. Avoid narrative that assigns blame or includes secrets and customer data. The useful outcome is continuity: another authorized developer can reproduce the current state, understand why work stopped, contact the correct owner, execute an approved next step, and verify the result without asking the original engineer to reconstruct a private terminal session.`
];
export const october08BlogBatch:readonly BlogPost[]=specs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:12,datePublished:date,revision:`daily-blog-${date}-${s.slug}`,keyTakeaways:['Preserve versioned technical evidence and chronology.','Route risk and production decisions to the accountable owner.','Verify the intended artifact and behavior after implementation.'],sections:[{heading:'Frame the evidence and authority',body:paras(s).slice(0,4)},{heading:'Reconstruct the technical state',body:paras(s).slice(4,7)},{heading:'Route and verify the decision',body:paras(s).slice(7,11)},{heading:'Make the distributed workflow repeatable',body:paras(s).slice(11)}],sources:[{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final',note:'Secure software development practices and roles.'},{name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Access, audit, configuration, and change-control guidance.'},{name:'OWASP Application Security Verification Standard',url:'https://owasp.org/www-project-application-security-verification-standard/',note:'Application security verification requirements.'}]}));

type RS={slug:string;title:string;excerpt:string;question:string;population:string;signals:string[]};const rss:RS[]=[
 {slug:'offshore-developer-review-latency-study-2026-10-08',title:'Offshore code-review decision latency research',excerpt:'A time-aware study of review-ready evidence, owner acknowledgement, requested changes, and merge decisions.',question:'how long review-ready changes wait for an accountable technical decision and which evidence gaps explain delay',population:'pull requests, configuration changes, migrations, security fixes, and release requests',signals:['ready event','reviewer identity','first review','evidence request','decision event','merge or closure']},
 {slug:'philippines-developer-artifact-lineage-study-2026-10-08',title:'Philippines build-artifact lineage research',excerpt:'Test whether deployed artifacts trace to the commit, dependencies, build, approval, and environment actually intended.',question:'whether a deployed artifact can be reconstructed from its source, build, approval, and runtime evidence',population:'successful, failed, cancelled, rolled-back, and superseded builds and deployments',signals:['source commit','dependency lock','build identity','artifact digest','approval','runtime version']},
 {slug:'offshore-developer-reviewer-agreement-study-2026-10-08',title:'Offshore engineering reviewer agreement research',excerpt:'A blinded study of whether independent reviewers identify the same defect, risk, owner, and stop condition.',question:'whether independent reviewers reach the same factual classification and routing decision',population:'representative frontend, API, data, infrastructure, security, and QA changes',signals:['scope','observed behavior','source version','risk flag','stop condition','decision owner']},
 {slug:'philippines-developer-access-removal-study-2026-10-08',title:'Philippines developer access-removal evidence research',excerpt:'A least-privilege protocol for accounts, sessions, keys, tokens, automations, and ownership transfer.',question:'whether development access and reusable artifacts are removed or reassigned at the authorized time',population:'departing developers, contractors, service accounts, sessions, keys, tokens, and automations',signals:['identity inventory','role removal','session revocation','key rotation','artifact ownership','post-removal test']},
 {slug:'offshore-regression-recurrence-study-2026-10-08',title:'Offshore regression recurrence research',excerpt:'Distinguish incomplete repair, new evidence, and recurring architecture or workflow defects.',question:'why closed engineering defects recur and which patterns identify evidence, ownership, code, test, or release gaps',population:'defects reopened after recorded repair across applications and infrastructure',signals:['original cause','repair version','new trigger','same-path recurrence','owner transfer','corrective action']}
];
for(const spec of rss) spec.excerpt+=` Published October 8, 2026.`;
const rbody=(s:RS)=>[
 `Research question. This study asks ${s.question}. It examines ${s.population}. The output is a reproducible evidence register and owner packet, not a claim that a system is secure, correct, compliant, or ready for release. NIST SSDF supplies a primary framework for software-development roles and practices; NIST SP 800-53 supports access, audit, configuration, and change-control evidence; OWASP ASVS supplies application verification context. Company architecture, product, security, and release owners determine actual treatment.`,
 `Population. Include successful, failed, cancelled, superseded, rolled-back, transferred, and reopened items. Each row retains repository, service, environment, stable issue ID, source commit, artifact or configuration version, intake time, queue state, reviewer, decision event, implementation, and final disposition. Primary observations are ${s.signals.join(', ')}. Freeze selection before outcomes and record every exclusion. Secrets, personal data, customer records, and restricted logs remain in approved systems with masked references.`,
 `Chronology. Retain original timestamp, timezone, actor or automation, system, and stable event ID for request, commit, review, test, build, deploy, alert, rollback, and verification. Add UTC without replacing originals. Review-ready, reviewer acknowledgement, evidence request, response, decision, implementation, and verification are distinct. This prevents missing-evidence time from being attributed to a reviewer and deployment time from being attributed to the developer. Clock or log gaps remain explicit limitations.`,
 `Source preservation. Original requirements, architecture decisions, issue history, commits, lockfiles, schemas, configurations, test outputs, build records, artifacts, approvals, and runtime evidence receive stable identifiers or hashes where permitted. Extracted fields link to source and version. Current main, latest image, or final dashboard cannot prove what existed earlier. Superseded artifacts remain connected through explicit change events rather than being overwritten by the successful result.`,
 `Classification. Review ${s.signals.join(', ')} as aligned, different, missing, superseded, not applicable, or owner interpretation required. Calculations show inputs, denominators, exclusions, precision, and result. Matching tags, green status, familiar filenames, or prior behavior are not proof. Those observations guide review but cannot resolve contract compatibility, customer impact, production authority, security acceptance, release scope, or business risk.`,
 `Independent review. Two reviewers receive the same frozen evidence and independently record signals, missing evidence, defect classification, current owner, stop condition, and bounded decision request. Agreement is measured separately for facts, risk flags, routing, and closure. Disagreements are adjudicated against sources and definitions, not by choosing the faster answer. Original reviewer responses remain retained so later taxonomy improvement does not erase earlier ambiguity.`,
 `Challenge cases include similar artifact names, rebuilt tags, timestamps near cutoff, approval followed by a commit change, automation without attributable actor, overlapping reviewers, transferred incident, rotated secret, rejected deployment retried, and closure followed by new evidence. The method passes when reviewers reconstruct the same sources, chronology, differences, and decision point. It fails when current state replaces historical evidence or a developer accepts a controlled exception to improve a metric.`,
 `Authority. Offshore developers may reproduce behavior, prepare code, tests, comparisons, runbooks, and evidence queues. They may not broaden privileged access, disclose secrets, change public contracts, approve their own high-risk exceptions, accept security or accessibility risk, or deploy outside release authority. Application, platform, data, product, security, accessibility, and release owners retain assigned decisions. A missing owner is reported as a design defect rather than absorbed by the preparer.`,
 `Measures include population completeness, artifact lineage, test evidence, review acknowledgement, decision time, implementation time, reviewer agreement, rollback readiness, reopened defects, repeated causes, and verified closure. Report distributions and denominators, not only averages. Stratify by change type, service, risk, owner role, and workflow when samples permit. Do not rank individuals by raw speed, commits, merges, or tickets. A correct controlled stop can take longer.`,
 `Sampling reflects the decision. Include every predefined high-consequence case, then select ordinary work reproducibly. Do not replace inaccessible logs or artifacts with convenient records while preserving sample size. Keep selected, available, reviewed, excluded, unscorable, replaced, and unresolved counts separate. Compare original and final samples by risk, service, age, change type, and outcome. Publish concentrated missingness rather than letting a clean subset represent the engineering population.`,
 `Limitations include overwritten logs, inaccessible SaaS systems, shared identities, clock drift, nondeterministic builds, mutable dependencies, policy ambiguity, informal decisions, and small samples. The study cannot prove absence of defects, security, legal compliance, causation, or future reliability. Its conclusion is narrower: ${s.question} can be examined when population, versions, chronology, roles, classifications, decisions, implementation, and limitations remain visible.`,
 `Pilot a normal change, missing-source path, environment conflict, urgent defect, and post-approval change. Ask an independent reviewer to reconstruct the same signals and owner question. Dependence on private chat, local state, memory, or undocumented tools becomes a gap. The owner decides whether to change repository controls, CI, runbook, access, or review cadence. A pilot tests workflow; it does not prove every future change behaves the same.`,
 `Actions link recurring findings to mechanism, owner, evidence, target date, acceptance test, and post-change observation. Missing timestamps may call for logging; mutable artifacts for digest enforcement; ownership ambiguity for code-owner rules; inconsistent decisions for approved examples. Training is not the default when tooling, test data, interfaces, or authority maps are unclear. Retest changed and unaffected cases and preserve the old measurement.`,
 `Reporting separates observations, interpretations, recommendations, and decisions. Observations cite records; interpretations state assumptions; recommendations name mechanisms; decisions identify authorized people and times. Negative findings identify tests because “no issue” without method is not evidence. Retain extraction time, query version, reviewer, population, denominators, unavailable evidence, unresolved high-risk cases, and next verification point.`,
 `Access and separation of duties are tested alongside code and artifacts. Reviewers receive minimum read permissions for frozen evidence; preparation does not require authority to merge, deploy, change configuration, rotate production credentials, approve exceptions, or alter customer data. Record individual identities for material actions and set expiry for temporary access. When evidence cannot be obtained safely, route the gap to the platform or security owner. Broader permission granted merely to finish a study can introduce more risk than the research question justifies and make later reproduction depend on exceptional access.`,
 `The final decision brief states what evidence supports and cannot support. It names population and period, shows denominators, describes unavailable artifacts or logs, distinguishes association from causation, and identifies unresolved high-risk changes under controlled access. It does not generalize one offshore engineering lane to all developers, providers, systems, or future releases. Management may expand, retain, narrow, pause, or repair the lane. The chosen action records owner, rationale, effective time, affected repositories and environments, rollback considerations, and next verification so research ends with accountable use instead of a detached percentage.`,
 `Continuity testing gives a backup reviewer only retained study materials and asks that person to reproduce selection, classifications, measures, and owner questions. Missing query logic, local fixtures, private dashboards, timezone assumptions, or undocumented exclusions become explicit defects. Repair them before repeating analysis. Store the approved method beside the output and preserve superseded versions. A later reviewer should explain why corrected evidence, a larger population, or revised definition changed a result without suggesting either period was manipulated.`,
 `Primary sources checked October 8, 2026: NIST Secure Software Development Framework, https://csrc.nist.gov/pubs/sp/800/218/final; NIST SP 800-53 Rev. 5, https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final; OWASP Application Security Verification Standard, https://owasp.org/www-project-application-security-verification-standard/. These sources inform evidence design. They do not certify a team, codebase, product, deployment, or provider.`
];
export const october8ResearchBatch:readonly ResearchPost[]=rss.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:date,sections:[{heading:'Research protocol',body:rbody(s)}],sources:[{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'},{name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},{name:'OWASP ASVS',url:'https://owasp.org/www-project-application-security-verification-standard/'}],keyStats:[`Six evidence signals: ${s.signals.join(', ')}`,'One frozen population and observation window','Two independent reviewers for a planned subset'],takeaways:['Preserve versioned evidence and chronology.','Separate preparation from technical risk acceptance.','Verify the intended artifact and runtime result.'],faqs:[{question:'What does this research measure?',answer:s.question+'.'},{question:'What remains with the technical owner?',answer:'Architecture, production change, security acceptance, release scope, exceptions, and business risk.'}],related:[]}));
