import type { BlogPost } from './data';

const topics = [
  ['offshore-developer-service-worker-update-recovery-2026-09-09','Stop an old service worker from serving the wrong release','web teams shipping an updated offline-capable application','prove when a waiting worker takes control and which cached shell each tab receives','worker state, controller URL, cache name, tab lifecycle, network requests, and build revision','one tab stays open through two deployments'],
  ['offshore-developer-postgresql-advisory-lock-audit-2026-09-09','Find the PostgreSQL advisory lock nobody released','backend teams coordinating work with application-level locks','trace every lock acquisition to its session, transaction, release path, and timeout','lock keys, session IDs, transaction state, wait duration, cancellation, and pool reuse','a pooled connection returns while it still owns a session lock'],
  ['offshore-developer-webhook-signature-key-rotation-2026-09-09','Rotate webhook signing keys without losing deliveries','integration teams changing shared verification secrets','define an overlap window in which old and new signatures are handled deliberately','key identifiers, signature versions, delivery times, verification outcomes, retries, and retirement time','a delayed retry was signed before rotation but arrives afterward'],
  ['offshore-developer-react-streaming-error-boundary-2026-09-09','Test a React streaming failure after the response begins','Next.js teams rendering data-dependent server components','observe what the browser receives when a late component fails after headers are committed','chunk order, response status, server error ID, boundary output, client console, and retry result','the page shell arrives before a nested data request rejects'],
  ['offshore-developer-s3-multipart-orphan-cleanup-2026-09-09','Clean up abandoned multipart uploads without touching active work','platform teams controlling object-storage cost','distinguish abandoned upload sessions from slow but active clients','upload ID, initiation time, last part time, part count, object key, and abort result','a large upload pauses longer than the proposed cleanup threshold'],
  ['offshore-developer-jwt-audience-migration-2026-09-09','Change a JWT audience without locking out an older client','API teams moving callers between resource identifiers','map which issuers, client versions, and endpoints accept each audience during migration','issuer, subject, audience set, client version, endpoint, validation result, and rejection reason','a token contains both the old and new audience values'],
  ['offshore-developer-dns-cutover-negative-cache-2026-09-09','Plan for negative DNS caching during a hostname cutover','teams moving an API to a newly published hostname','measure how resolvers retain an earlier nonexistent-domain answer','query name, resolver, response code, negative TTL, authoritative serial, and recovery time','a client queried the new hostname just before its record was published'],
  ['offshore-developer-kafka-consumer-rebalance-handoff-2026-09-09','Keep in-flight work safe during a Kafka consumer rebalance','event-processing teams scaling or restarting consumers','show what happens between partition revocation, completed side effects, and committed offsets','group generation, partition assignment, record offset, side-effect ID, commit, and redelivery','revocation begins after an external write but before the offset commit'],
  ['offshore-developer-graphql-dataloader-tenant-leak-2026-09-09','Check a GraphQL DataLoader cache for tenant bleed','multi-tenant API teams batching resolver reads','prove that request and tenant boundaries are part of every loader cache decision','request ID, tenant ID, loader instance, cache key, database predicate, and returned entity','two tenants request the same numeric record ID concurrently'],
  ['offshore-developer-stripe-idempotency-scope-review-2026-09-09','Scope payment idempotency keys to the operation you mean','billing teams retrying payment-provider requests','verify how an idempotency key is generated, stored, reused, and retired','business operation ID, request parameters, key, provider response, retry count, and final state','the same key is accidentally reused with changed request parameters'],
  ['offshore-developer-csp-nonce-cache-review-2026-09-09','Keep a cached HTML page from reusing the wrong CSP nonce','web teams combining strict Content Security Policy with edge caching','follow nonce generation into both the response header and every permitted script','cache key, response age, nonce values, CSP header, script attributes, and browser violations','an edge serves HTML generated for a previous response nonce'],
  ['offshore-developer-redis-expiry-replication-check-2026-09-09','Verify a Redis expiry survives failover the way you expect','application teams relying on short-lived Redis state','observe the remaining lifetime before and after replication and role change','key value, TTL, server role, replication offset, failover time, and post-failover read','failover happens within one second of the key deadline'],
] as const;

export const september9BlogBatch: readonly BlogPost[] = topics.map(([slug,title,audience,decision,evidence,edge], index) => ({
  slug, title,
  excerpt: `A field guide for ${audience}. It uses a narrow test, one troublesome case, and a handoff a reviewer can replay.`,
  minutes: 9 + (index % 4), datePublished: '2026-09-09', dateModified: '2026-09-09', revision: `daily-blog-2026-09-09-${slug}`,
  keyTakeaways: [`Write down how you will ${decision}.`, `Retain ${evidence}.`, `Test the awkward case where ${edge}.`],
  sections: [
    {heading:'Start with the disputed behavior',body:[`This job fits ${audience}. Before touching code, write the behavior under review: ${decision}. Include the repository revision, environment, representative fixture, reviewer, and a clear stop point.`]},
    {heading:'Record a plain baseline',body:[`Run one ordinary case first and save ${evidence}. Keep the input small enough that another developer can inspect it without special production access. The baseline tells you whether the test setup itself is trustworthy.`]},
    {heading:'Recreate the case people tend to miss',body:[`The useful stress case is simple to state: ${edge}. Change only one condition at a time. Note the request or event, prior state, observed transition, final state, and the clock used for every timestamp.`]},
    {heading:'Put the correction beside the failure',body:[`Trace the result to the narrowest responsible boundary. Put the regression check close to that boundary, make the smallest defensible correction, and rerun both the ordinary and troublesome cases. Record nearby behavior that remains outside the brief.`]},
    {heading:'Keep authority with the system owner',body:[`An offshore developer may prepare fixtures, investigate the failure, implement a reviewed patch, and collect proof. Internal owners retain protected credentials, architecture exceptions, irreversible data work, incident disclosure, and the production release decision.`]},
    {heading:'Write a handoff that survives a time-zone change',body:[`The handoff should name the starting and ending revisions, changed files, fixture data, commands, passed and skipped checks, remaining uncertainty, rollback approach, and reviewer. It should answer the original question about how to ${decision}.`]},
  ],
  table:{title:'Review record',columns:['Moment','Evidence','Owner'],rows:[['Baseline',evidence,'Assigned developer'],['Boundary case',edge,'Developer and reviewer'],['Release','Test result, limits, and rollback note','Internal release owner']]},
  relatedLinks:[{label:'Developer services',href:'/services',note:'Choose a bounded engineering lane.'},{label:'Research library',href:'/research',note:'Pair the guide with a measured study.'},{label:'Contact',href:'/contact',note:'Define the first outcome and review owner.'}],
  faqs:[{question:'Can an offshore developer own this check?',answer:'Yes. Give the developer synthetic data, scoped access, a fixed revision, and a named reviewer.'},{question:'Who accepts the production risk?',answer:'The internal system owner reviews the evidence and approves or rejects the release.'}],
  sources:index % 3 === 0 ? [{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'},{name:'OWASP Web Security Testing Guide',url:'https://owasp.org/www-project-web-security-testing-guide/'}] : index % 3 === 1 ? [{name:'Google Site Reliability Engineering',url:'https://sre.google/sre-book/table-of-contents/'},{name:'OpenTelemetry documentation',url:'https://opentelemetry.io/docs/'}] : [{name:'MDN Web Docs',url:'https://developer.mozilla.org/en-US/docs/Web'},{name:'Google Engineering Practices',url:'https://google.github.io/eng-practices/review/'}],
}));
