import type { BlogPost } from './data';

const topics = [
  ['offshore-developer-api-version-sunset-2026-09-04','Plan an API version sunset with an offshore developer','API owners retiring a public contract','which consumers are ready to move before the old version closes','gateway logs, client identifiers, contract tests, and deprecation headers','a low-volume client that only runs at month end'],
  ['offshore-developer-message-queue-poison-record-2026-09-04','Handle a poison queue record without hiding the failure','backend teams operating asynchronous workers','when a repeatedly failing message should leave the normal retry lane','attempt histories, redacted payload shape, exception class, and dead-letter events','a deterministic validation failure retried like a transient outage'],
  ['offshore-developer-multipart-upload-recovery-2026-09-04','Test multipart-upload recovery with an offshore developer','platform teams receiving large files','how an interrupted upload resumes or expires without assembling corrupt data','part checksums, upload IDs, controlled disconnects, and completion manifests','the final part succeeds after an earlier part was replaced'],
  ['offshore-developer-search-index-cutover-2026-09-04','Run a search-index cutover with a reversible handoff','product teams rebuilding a live search index','what proves the replacement index is complete enough to receive reads','document counts, sampled queries, lag markers, aliases, and rollback timings','writes continue while the final indexing pass is running'],
  ['offshore-developer-mobile-deep-link-routing-2026-09-04','Review mobile deep-link routing across install states','mobile leads sharing app links from email and web','which screen and fallback should open for each authentication and install state','signed links, device fixtures, navigation logs, and fallback captures','an authenticated link opens after the session expires'],
  ['offshore-developer-database-read-replica-lag-2026-09-04','Set a read-replica lag boundary before routing traffic','application teams separating database reads and writes','which reads require fresh primary state and which tolerate delay','commit markers, replica timestamps, user journeys, and consistency tests','a user saves a setting and immediately reads the old value'],
  ['offshore-developer-csp-report-triage-2026-09-04','Turn CSP reports into a focused offshore investigation','frontend security owners tightening browser policy','which blocked resource represents a defect, an attack, or harmless noise','report samples, directive names, release revisions, and browser fixtures','an extension-generated violation resembles first-party script breakage'],
  ['offshore-developer-cache-key-tenant-isolation-2026-09-04','Audit tenant isolation in application cache keys','SaaS teams caching account-specific responses','whether every cached value is partitioned by the authorization context that shaped it','synthetic tenants, cache traces, key templates, and denied cross-account cases','a privileged response is reused after switching organizations'],
  ['offshore-developer-feature-flag-percentage-rollout-2026-09-04','Verify percentage rollouts without relying on dashboard labels','product engineers staging a risky feature','whether assignment is stable, eligible, and observable for the intended cohort','synthetic identities, rule revisions, exposure events, and distribution counts','a user changes cohorts while retaining an old assignment'],
  ['offshore-developer-password-reset-race-2026-09-04','Test password-reset races with an offshore developer','identity teams maintaining account recovery','which reset request remains valid when a user asks twice','synthetic accounts, token hashes, controlled clocks, and session invalidation records','two reset links are redeemed nearly simultaneously'],
  ['offshore-developer-serverless-cold-start-2026-09-04','Measure serverless cold starts in the user journey','teams moving request handlers to on-demand compute','when initialization delay changes the product outcome rather than only a metric','invocation state, dependency timings, end-to-end latency, and timeout responses','several instances initialize together after a traffic burst'],
  ['offshore-developer-audit-event-schema-evolution-2026-09-04','Evolve an audit-event schema without losing meaning','compliance and platform teams changing accountable events','how old and new event versions preserve actor, action, target, and outcome','versioned fixtures, consumers, replay checks, and rendered audit views','a new optional field changes how an older consumer interprets success'],
] as const;

export const september4BlogBatch: readonly BlogPost[] = topics.map(([slug,title,audience,decision,evidence,edge], i) => ({
  slug, title, excerpt: `A field guide for ${audience}: define the decision, reproduce the awkward case, and leave evidence another working window can verify.`, minutes: 10,
  datePublished: '2026-09-04', dateModified: '2026-09-04', revision: `daily-blog-2026-09-04-${slug}`,
  keyTakeaways: [`Decide ${decision}.`, `Preserve ${evidence}.`, 'Keep production acceptance with the accountable internal owner.'],
  sections: [
    { heading: 'Begin with the decision, not the ticket', body: [`This assignment is for ${audience}. Write down ${decision} before anyone changes code. Fix the repository revision, safe environment, reviewer, and stop condition. That gives a Philippines-based developer room to investigate without quietly inheriting product or production authority.`] },
    { heading: 'Trace the state that matters', body: [`Follow the user action through every relevant boundary. Collect ${evidence}; note where identity, time, retries, permissions, or persistence change the result. Keep observations separate from assumptions so the next reviewer can challenge the explanation.`] },
    { heading: 'Build a small but adversarial fixture set', body: [`Use synthetic normal, invalid, repeated, interrupted, and recovery cases. The case most likely to expose a false sense of safety is ${edge}. Change one condition at a time and record expected and observed behavior with the exact revision.`] },
    { heading: 'Make the correction reversible', body: [`Prefer the narrowest change that explains the failure and adds a regression check. Confirm cleanup, monitoring, and rollback. A passing unit test is useful, but it cannot stand in for a boundary the test never exercised.`] },
    { heading: 'Keep approval boundaries visible', body: [`The offshore developer may reproduce, implement, test, and document this lane. Internal owners retain protected data access, architecture exceptions, irreversible operations, incident communication, and release acceptance. Escalate rather than improvising when the evidence crosses those boundaries.`] },
    { heading: 'Close with a handoff someone can replay', body: [`Record starting and ending revisions, fixtures, commands, passed and skipped checks, screenshots or logs, limitations, rollback notes, reviewer, and next authorized action. For this topic, explicitly state what the evidence proves about ${decision} and what remains untested.`] },
  ],
  table: { title: 'Review record', columns: ['Gate','Evidence','Decision owner'], rows: [['Scope',decision,'Product or system owner'],['Boundary case',edge,'Developer and reviewer'],['Release','Regression result and rollback','Internal release owner']] },
  relatedLinks: [{label:'Developer services',href:'/services',note:'Review supported delivery lanes.'},{label:'Research library',href:'/research',note:'Read evidence-led reports.'},{label:'Contact',href:'/contact-us',note:'Discuss a bounded role.'}],
  faqs: [{question:'What can the offshore developer own?',answer:'Reproduction, a bounded implementation, focused verification, and a replayable handoff.'},{question:'What stays internal?',answer:'Sensitive access, exceptions, irreversible actions, production approval, and accepted residual risk.'}],
  sources: i % 2 === 0 ? [{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'},{name:'OWASP Web Security Testing Guide',url:'https://owasp.org/www-project-web-security-testing-guide/'}] : [{name:'Google Engineering Practices',url:'https://google.github.io/eng-practices/review/'},{name:'Google Site Reliability Engineering',url:'https://sre.google/sre-book/table-of-contents/'}],
}));
