import type { BlogPost } from './data';

const topics = [
  ['offshore-developer-openapi-breaking-change-review-2026-09-08','Catch an OpenAPI breaking change before a client does','API teams changing a published contract','compare the proposed schema with the last released document','operation IDs, request fields, response shapes, generated-client output, and compatibility test results','an optional response field becomes required in a generated client'],
  ['offshore-developer-database-deadlock-reproduction-2026-09-08','Turn a database deadlock into a repeatable test','backend teams investigating intermittent transaction failures','recreate the lock order with two controlled sessions','transaction steps, lock waits, deadlock reports, retry behavior, and final row values','the retry succeeds but repeats an external side effect'],
  ['offshore-developer-signed-url-expiry-boundary-2026-09-08','Test signed URLs at the exact expiry boundary','teams delivering private downloads','define how clock difference and cache behavior affect access','issuer time, verifier time, expiry value, response status, cache headers, and audit events','a cached response remains available after the origin would reject the URL'],
  ['offshore-developer-message-ordering-partition-check-2026-09-08','Check message ordering where the partition key changes','event-driven teams relying on ordered updates','prove which events share an ordering boundary','event IDs, entity keys, partition assignments, publish times, and consumer state','an entity identifier changes during a migration'],
  ['offshore-developer-graphql-persisted-query-rollout-2026-09-08','Roll out persisted GraphQL queries without stranding old clients','mobile and web teams reducing arbitrary query traffic','coordinate the query registry with multiple client versions','query hashes, registry revisions, client versions, rejection responses, and rollback results','a mobile release remains active after its query is removed'],
  ['offshore-developer-oauth-state-validation-review-2026-09-08','Trace OAuth state validation through the whole callback','product teams maintaining third-party sign-in','show where state is created, bound to a session, checked, and retired','state values, session identifiers, redirect targets, expiry, and rejection logs','two login attempts are open in separate browser tabs'],
  ['offshore-developer-cache-revalidation-race-2026-09-08','Reproduce a cache revalidation race under real timing','Next.js teams debugging stale pages after publication','observe which request refreshes data and what concurrent readers receive','cache keys, timestamps, response headers, content revisions, and origin calls','two regions revalidate the same entry at nearly the same time'],
  ['offshore-developer-worker-visibility-timeout-2026-09-08','Set a queue visibility timeout from measured job behavior','teams running jobs whose duration varies','compare processing time with redelivery and heartbeat behavior','job duration, lease extensions, delivery count, side effects, and acknowledgement time','a worker pauses after the side effect but before acknowledgement'],
  ['offshore-developer-schema-migration-dual-write-2026-09-08','Audit a dual-write migration before the old field disappears','application teams moving data between schemas','measure whether both representations stay equivalent during the transition','write paths, backfill checkpoints, mismatches, read selection, and rollback state','an older worker writes only the legacy field'],
  ['offshore-developer-cors-preflight-cache-2026-09-08','Debug CORS failures with the preflight cache in view','frontend teams calling APIs across origins','separate server policy from browser-cached preflight results','Origin values, requested methods and headers, response policy, max age, and browser version','the server policy changes while a failed preflight is still cached'],
  ['offshore-developer-websocket-backpressure-review-2026-09-08','Keep a slow WebSocket client from exhausting the server','real-time product teams broadcasting frequent updates','decide how much unsent data one connection may retain','buffer size, send latency, dropped messages, connection state, and memory use','a backgrounded browser stops reading while the server keeps publishing'],
  ['offshore-developer-feature-entitlement-downgrade-2026-09-08','Make a subscription downgrade revoke the right features','SaaS teams translating billing state into product access','follow an entitlement change from billing event to every authorization check','plan version, event ID, entitlement snapshot, cache invalidation, and denied actions','a delayed upgrade event arrives after the downgrade'],
] as const;

export const september8BlogBatch: readonly BlogPost[] = topics.map(([slug,title,audience,decision,evidence,edge], index) => ({
  slug, title,
  excerpt: `A field guide for ${audience}. It uses a narrow test, one troublesome case, and a handoff a reviewer can replay.`,
  minutes: 9 + (index % 4), datePublished: '2026-09-08', dateModified: '2026-09-08', revision: `daily-blog-2026-09-08-${slug}`,
  keyTakeaways: [`Write down how you will ${decision}.`, `Retain ${evidence}.`, `Test the awkward case where ${edge}.`],
  sections: [
    {heading:'Start with the disputed behavior',body:[`This job fits ${audience}. Before touching code, write the behavior under review: ${decision}. Include the repository revision, environment, representative fixture, reviewer, and a clear stop point.`]},
    {heading:'Record a plain baseline',body:[`Run one ordinary case first and save ${evidence}. Keep the input small enough that another developer can inspect it without special production access. The baseline tells you whether the test setup itself is trustworthy.`]},
    {heading:'Recreate the case people tend to miss',body:[`The useful stress case is simple to state: ${edge}. Change only one condition at a time. Note the request or event, prior state, observed transition, final state, and the clock used for every timestamp.`]},
    {heading:'Put the correction beside the failure',body:[`Trace the result to the narrowest responsible boundary. Put the regression check close to that boundary, make the smallest defensible correction, and rerun both the ordinary and troublesome cases. Record nearby behavior that remains outside the brief.`]},
    {heading:'Keep authority with the system owner',body:[`An offshore developer may prepare fixtures, investigate the failure, implement a reviewed patch, and collect proof. Internal owners retain protected credentials, architecture exceptions, irreversible data work, incident disclosure, and the production release decision.`]},
    {heading:'Write a handoff that survives a time-zone change',body:[`The handoff should name the starting and ending revisions, changed files, fixture data, commands, passed and skipped checks, remaining uncertainty, rollback approach, and reviewer. It should answer the original question about how to ${decision}.`]},
  ],
  table:{title:'Review record',columns:['Moment','Evidence','Owner'],rows:[['Baseline',evidence,'Assigned developer'],['Boundary case',edge,'Developer and reviewer'],['Release','Test result, limits, and rollback note','Internal release owner']]},
  relatedLinks:[{label:'Developer services',href:'/services',note:'Choose a bounded engineering lane.'},{label:'Research library',href:'/research',note:'Pair the guide with a measured study.'},{label:'Contact',href:'/contact-us',note:'Define the first outcome and review owner.'}],
  faqs:[{question:'Can an offshore developer own this check?',answer:'Yes. Give the developer synthetic data, scoped access, a fixed revision, and a named reviewer.'},{question:'Who accepts the production risk?',answer:'The internal system owner reviews the evidence and approves or rejects the release.'}],
  sources:index % 3 === 0 ? [{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'},{name:'OWASP Web Security Testing Guide',url:'https://owasp.org/www-project-web-security-testing-guide/'}] : index % 3 === 1 ? [{name:'Google Site Reliability Engineering',url:'https://sre.google/sre-book/table-of-contents/'},{name:'OpenTelemetry documentation',url:'https://opentelemetry.io/docs/'}] : [{name:'MDN Web Docs',url:'https://developer.mozilla.org/en-US/docs/Web'},{name:'Google Engineering Practices',url:'https://google.github.io/eng-practices/review/'}],
}));
