import type { BlogPost } from './data';

type Topic = { slug: string; title: string; audience: string; decision: string; system: string; evidence: string; failure: string; owner: string; sections: readonly string[] };

const topics: readonly Topic[] = [
  { slug: 'offshore-developer-api-timeout-budget-2026-09-03', title: 'Set an API timeout budget before assigning offshore implementation', audience: 'backend leads responsible for request chains that cross several services', decision: 'how much time each dependency may consume before the caller stops waiting', system: 'gateway, application service, database, and external API', evidence: 'monotonic timing traces, controlled latency fixtures, cancellation logs, and client-visible responses', failure: 'the upstream caller disconnects while a downstream write is still running', owner: 'backend owner', sections: ['Draw the request chain before choosing a number', 'Measure latency by hop, not only at the browser', 'Propagate cancellation without losing completed work', 'Separate timeout behavior from retry behavior', 'Test the write that finishes after its caller leaves', 'Give the next working window a timing ledger'] },
  { slug: 'offshore-developer-database-lock-contention-2026-09-03', title: 'A database lock-contention investigation for an offshore developer', audience: 'application teams seeing slow or stalled transactions under ordinary load', decision: 'which transaction holds a lock too broadly and what smaller boundary preserves correctness', system: 'application transactions, database sessions, queues, and worker concurrency', evidence: 'synthetic concurrent requests, lock graphs, query plans, transaction timestamps, and rollback results', failure: 'two individually valid updates acquire shared resources in opposite order', owner: 'database owner', sections: ['Start from the blocked user action', 'Capture the waiter and the holder together', 'Reproduce with synthetic rows and bounded concurrency', 'Shorten work inside the transaction cautiously', 'Prove deadlock recovery and data consistency', 'Hand back a lock graph, not a guess'] },
  { slug: 'offshore-developer-react-hydration-mismatch-2026-09-03', title: 'How to brief an offshore React developer on a hydration mismatch', audience: 'frontend leads maintaining server-rendered React interfaces', decision: 'which value differs between server output and the first client render', system: 'server components, client components, browser state, and rendering cache', evidence: 'captured server HTML, console output, controlled clocks, viewport fixtures, and component tests', failure: 'locale or browser-only state changes text before hydration completes', owner: 'frontend owner', sections: ['Preserve the server output before editing code', 'Find the first unstable value', 'Control clocks, locale, random values, and browser state', 'Choose a client boundary deliberately', 'Test navigation as well as a cold document load', 'Package screenshots with the rendering conditions'] },
  { slug: 'offshore-developer-email-bounce-webhook-2026-09-03', title: 'Review email-bounce webhooks with an offshore developer', audience: 'product teams that send transactional email through an external provider', decision: 'how provider events change suppression state without blocking legitimate mail', system: 'email provider, webhook receiver, event store, suppression rules, and support tools', evidence: 'signed event fixtures, provider identifiers, duplicate deliveries, ordering tests, and state transitions', failure: 'a delayed temporary-bounce event arrives after a later successful delivery', owner: 'messaging owner', sections: ['Name the suppression decision first', 'Normalize provider events without erasing evidence', 'Make duplicate delivery harmless', 'Test events that arrive out of order', 'Keep manual overrides accountable', 'Write a replayable event handoff'] },
  { slug: 'offshore-developer-cron-timezone-boundary-2026-09-03', title: 'A timezone-safe cron review for offshore development', audience: 'platform and product leads responsible for scheduled business processes', decision: 'whether a job follows elapsed time, UTC, or a named local civil time', system: 'scheduler, worker, timezone database, job ledger, and downstream service', evidence: 'controlled clock cases, timezone identifiers, skipped and repeated local times, and execution keys', failure: 'the same local clock label occurs twice during a daylight-saving transition', owner: 'product and platform owner', sections: ['Classify the schedule before touching cron syntax', 'Store a named timezone when civil time matters', 'Define behavior for missing and repeated local times', 'Give every intended run a stable identity', 'Test catch-up after scheduler downtime', 'Record the next occurrence beside the rule'] },
  { slug: 'offshore-developer-object-storage-lifecycle-2026-09-03', title: 'Scope an object-storage lifecycle review for an offshore developer', audience: 'engineering teams retaining uploads, exports, and generated artifacts', decision: 'when each object becomes eligible for transition or deletion and which records must remain linked', system: 'application database, object bucket, lifecycle rules, background jobs, and restore workflow', evidence: 'synthetic object inventories, tags, version states, lifecycle simulations, and restore checks', failure: 'a database record is restored after its referenced object became eligible for deletion', owner: 'data owner', sections: ['Inventory object purpose before age', 'Trace references outside the bucket', 'Distinguish current versions from retained versions', 'Model transition and deletion separately', 'Exercise a restore across the lifecycle boundary', 'Hand off exceptions with named owners'] },
  { slug: 'offshore-developer-dependency-canary-update-2026-09-03', title: 'Use a canary lane for an offshore dependency update', audience: 'maintainers upgrading a library shared across several product paths', decision: 'which smallest representative consumer can reveal compatibility trouble first', system: 'package manager, application build, test suite, runtime telemetry, and release controls', evidence: 'lockfile diff, changelog references, representative consumer tests, bundle changes, and rollback steps', failure: 'the package compiles but changes a runtime default used by only one consumer', owner: 'application owner', sections: ['Explain why the dependency must move', 'Read the lockfile as part of the change', 'Choose a consumer with diagnostic value', 'Test changed defaults and peer boundaries', 'Keep expansion separate from canary acceptance', 'Leave a rollback that restores the dependency graph'] },
  { slug: 'offshore-developer-websocket-reconnect-state-2026-09-03', title: 'Test WebSocket reconnect state with an offshore developer', audience: 'teams operating live dashboards, collaboration tools, or streaming interfaces', decision: 'what state the client must rebuild after transport loss', system: 'browser client, connection gateway, subscription service, event cursor, and state store', evidence: 'controlled disconnects, event cursors, duplicate messages, gap detection, and UI snapshots', failure: 'events arrive between the last acknowledged cursor and the new subscription', owner: 'realtime feature owner', sections: ['Separate transport recovery from state recovery', 'Record the last trustworthy cursor', 'Bound reconnect delay and jitter', 'Detect gaps instead of hiding them', 'Make duplicate events safe at the reducer', 'Describe the recovered state in the handoff'] },
  { slug: 'offshore-developer-csv-formula-injection-2026-09-03', title: 'A CSV formula-injection review for offshore export work', audience: 'application owners whose users open exported data in spreadsheet software', decision: 'which untrusted values must be encoded so a spreadsheet treats them as data', system: 'export query, serialization layer, download route, and representative spreadsheet tools', evidence: 'dangerous-prefix fixtures, delimiter and quote cases, encoded files, and round-trip checks', failure: 'a value begins with whitespace before a formula-triggering character', owner: 'security and product owner', sections: ['Treat the spreadsheet as an execution surface', 'Locate every untrusted export column', 'Preserve data while neutralizing formulas', 'Test whitespace, quoting, and alternate delimiters', 'Document compatibility limits honestly', 'Give reviewers the exact fixture file'] },
  { slug: 'offshore-developer-session-fixation-defense-2026-09-03', title: 'Review session-fixation defenses with an offshore developer', audience: 'application teams maintaining password, SSO, or step-up authentication', decision: 'when the application must replace a session identifier as trust changes', system: 'browser cookies, authentication service, session store, and authorization middleware', evidence: 'pre-login and post-login cookie captures, synthetic accounts, privilege changes, and invalidation tests', failure: 'a session established before login remains valid after authentication', owner: 'security owner', sections: ['Map every trust transition', 'Capture identifiers without exposing live secrets', 'Rotate on authentication and privilege change', 'Invalidate the earlier session deterministically', 'Test concurrent tabs and logout boundaries', 'Write evidence the security owner can reproduce'] },
  { slug: 'offshore-developer-browser-storage-migration-2026-09-03', title: 'Plan a browser-storage migration with an offshore frontend developer', audience: 'frontend teams changing persisted client preferences or offline state', decision: 'how old stored values become valid new state or fail safely', system: 'browser storage, client schema, startup path, synchronization logic, and reset controls', evidence: 'versioned fixtures, interrupted migrations, quota failures, multi-tab behavior, and recovery screenshots', failure: 'one tab writes the new schema while another still runs the old client', owner: 'frontend product owner', sections: ['Version the stored shape explicitly', 'Migrate from real historical fixtures', 'Keep startup usable after malformed state', 'Handle quota and interrupted writes', 'Exercise two tabs on different versions', 'Document reset behavior for support'] },
  { slug: 'offshore-developer-graphql-query-cost-2026-09-03', title: 'Define GraphQL query-cost controls before offshore implementation', audience: 'API owners exposing flexible nested queries to product clients', decision: 'which combination of depth, list size, and field work exceeds safe service capacity', system: 'GraphQL schema, resolver graph, data loaders, authorization layer, and observability', evidence: 'versioned query fixtures, resolver counts, database calls, timing traces, and rejection responses', failure: 'a shallow query fans out through several expensive list fields', owner: 'API owner', sections: ['Model resolver work instead of depth alone', 'Use representative expensive fields', 'Account for authorization and data loading', 'Reject before avoidable work begins', 'Return an actionable bounded error', 'Review thresholds with production ownership'] },
] as const;

function article(topic: Topic): BlogPost {
  const shared = [
    `This guide is for ${topic.audience}. The practical decision is ${topic.decision}. A Philippines-based offshore developer can investigate and implement a bounded slice, but ${topic.owner} retains approval over production risk, protected data, and exceptions. Begin with a fixed revision, a synthetic fixture, an approved environment, and one observable outcome.`,
    `Trace the full path through ${topic.system}. Mark where data enters, changes shape, crosses an ownership boundary, persists, retries, or becomes visible. Collect ${topic.evidence}. A successful happy path proves only that case, so record assumptions and unavailable dependencies beside the evidence.`,
    `Build a compact test matrix with a normal case, a denied or invalid case, a repeated action, an interrupted action, and a recovery case. Record fixture identity, setup, expected result, observed result, revision, time reference, and cleanup. Do not copy customer records or production credentials into a general handoff.`,
    `The boundary case for this assignment is: ${topic.failure}. Hold the nearest passing case constant and change one condition at a time. Capture the first divergence, its user or system consequence, and the evidence that distinguishes a code defect from an environmental limit.`,
    `Keep implementation authority narrow. The developer may reproduce behavior, prepare a focused correction, add regression coverage, and explain tradeoffs. The internal owner decides product meaning, access expansion, architecture exceptions, irreversible data actions, public communication, and release acceptance. Escalate when the result crosses those boundaries.`,
    `Close the working window with starting and ending revisions, changed paths, commands, fixtures, passed and skipped checks, screenshots or logs, known limitations, rollback notes, reviewer, and next authorized action. The next person should be able to repeat the check without guessing which environment or state produced it.`,
  ];
  const sections = topic.sections.map((heading, index) => ({ heading, body: [shared[index], `${heading} matters specifically because the team must resolve ${topic.decision}. Use ${topic.evidence} to compare the intended behavior with the observed one. For the difficult case, test ${topic.failure}. State what the evidence establishes, what it merely suggests, and what remains unknown. Prefer a small reversible change and a focused regression test over a broad rewrite. Recheck permissions, state transitions, cleanup, and the user-visible result after the change. The offshore developer should finish with a concrete recommendation; ${topic.owner} makes the final risk decision.`] }));
  sections.push({ heading: 'Review the result against the original decision', body: [`Return to the question: ${topic.decision}. Compare the normal, invalid, repeated, interrupted, and recovery cases. Confirm that the result holds across the relevant parts of ${topic.system}, and identify any consumer or environment that was not exercised. A green build is useful evidence, but it does not stand in for the runtime conditions that the test never reached.`, `A strong final note separates observation, inference, recommendation, and approval. It names the accepted behavior, rejected alternatives, residual risk, accountable reviewer, and condition that should reopen the work. This lets a distributed developer advance implementation and verification across working hours while the internal team keeps control of product and production decisions.`] });
  return { slug: topic.slug, title: topic.title, excerpt: `A practical operating guide for ${topic.audience}, with a bounded decision, difficult failure case, and reviewable evidence.`, minutes: 9, datePublished: '2026-09-03', dateModified: '2026-09-03', revision: `daily-blog-2026-09-03-${topic.slug}`, keyTakeaways: [`Resolve ${topic.decision}.`, `Collect ${topic.evidence}.`, `Keep final approval with ${topic.owner}.`], sections, relatedLinks: [{ label: 'Developer services', href: '/services', note: 'Review supported software delivery lanes.' }, { label: 'Research library', href: '/research', note: 'Read evidence-led operating reports.' }, { label: 'Discuss the role', href: '/contact-us', note: 'Bring the stack, first outcome, schedule, and reviewer.' }], faqs: [{ question: 'What can the offshore developer own?', answer: 'The developer can reproduce the issue, implement the approved slice, add focused tests, and package evidence. Internal owners retain protected access, production acceptance, and residual risk.' }, { question: 'What should the handoff contain?', answer: `Include ${topic.evidence}, the revisions and changed paths, passed and skipped checks, limitations, reviewer, and next authorized action.` }], sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'OWASP Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' }, { name: 'Google Engineering Practices', url: 'https://google.github.io/eng-practices/review/' }] };
}

export const september3BlogBatch: readonly BlogPost[] = topics.map(article);
