import type { ResearchPost } from './fleet-data';

const studies = [
  ['offshore-developer-http-early-hints-study-2026-09-09','Do HTTP 103 Early Hints improve this page’s load path?','one static page tested through a declared browser, origin, and CDN path','interim and final status lines, hinted resources, request start times, connection reuse, transfer sizes, and visual milestones','a faster repeat visit may come from the browser cache rather than Early Hints',['RFC 8297: An HTTP Status Code for Indicating Hints','https://www.rfc-editor.org/rfc/rfc8297.html'],['MDN: 103 Early Hints','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/103']],
  ['offshore-developer-postgresql-autovacuum-lag-study-2026-09-09','When does autovacuum fall behind on a busy PostgreSQL table?','one synthetic table under a fixed update workload and server configuration','live and dead tuple estimates, vacuum timestamps, thresholds, worker activity, transaction age, and query latency','long-lived transactions may retain dead tuples even when autovacuum runs',['PostgreSQL: Routine Vacuuming','https://www.postgresql.org/docs/current/routine-vacuuming.html'],['PostgreSQL: Autovacuum Configuration','https://www.postgresql.org/docs/current/runtime-config-autovacuum.html']],
  ['offshore-developer-kubernetes-readiness-propagation-study-2026-09-09','How quickly does a failed readiness probe leave the request path?','one Kubernetes deployment and Service tested in a controlled cluster','probe results, Pod conditions, EndpointSlice updates, proxy observations, request timestamps, and response origin','client keep-alive connections may outlive endpoint removal',['Kubernetes: Configure Liveness, Readiness and Startup Probes','https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/'],['Kubernetes: EndpointSlices','https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/']],
  ['offshore-developer-web-crypto-key-clone-study-2026-09-09','What happens to a Web Crypto key across browser workers?','one browser-origin test matrix using declared key algorithms, extractability settings, and worker types','algorithm, extractable flag, usages, clone result, operation result, exception name, and browser version','successful structured cloning does not imply that raw key material became exportable',['W3C Web Cryptography API','https://www.w3.org/TR/WebCryptoAPI/'],['MDN: CryptoKey','https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey']],
  ['offshore-developer-opentelemetry-baggage-cost-study-2026-09-09','How much overhead does OpenTelemetry baggage add to one request chain?','one synthetic request chain with fixed hops and declared baggage sizes','header bytes, hop count, request latency, span attributes, rejection behavior, and sampling state','latency variation from connection setup may be larger than the baggage effect',['OpenTelemetry: Baggage','https://opentelemetry.io/docs/concepts/signals/baggage/'],['W3C Baggage','https://www.w3.org/TR/baggage/']],
] as const;
const related = [{title:'Research library',href:'/research'},{title:'Developer services',href:'/services'},{title:'Daily developer guides',href:'/blog'}] as const;
export const september9ResearchBatch: readonly ResearchPost[] = studies.map(([slug,title,scope,signals,rival,sourceOne,sourceTwo], index) => ({
  slug, title, published:'2026-09-09', excerpt:`A small, reproducible study of ${scope}. The report separates observed behavior from inference and records what the test cannot establish.`,
  keyStats:['1 declared unit of analysis',`${6 + (index % 2)} recorded signal classes`,'2 mechanism-specific primary references'],
  takeaways:[`Capture ${signals}.`,`Check the competing explanation that ${rival}.`,'Treat the finding as local to the recorded revision, workload, environment, and observation window.'],
  sections:[
    {heading:'Research question and scope',body:[`The question is: ${title} The unit of analysis is ${scope}. The protocol fixes the code revision, configuration, workload, identities, and observation window before a run begins.`]},
    {heading:'Method',body:[`Create baseline, boundary, repeated, interrupted, and recovery runs with synthetic data. Record ${signals}. Preserve raw output before adding notes, identify the clock behind each timestamp, and repeat the closest passing run after every isolated change.`]},
    {heading:'How the sources inform the protocol',body:[`${sourceOne[0]} defines the main mechanism used in the test. ${sourceTwo[0]} provides a second standards or implementation view. They determine what the fixtures should exercise, but neither source proves how this particular system behaves.`]},
    {heading:'Counterevidence and inference limits',body:[`Try to overturn the first explanation by testing whether ${rival}. Change identity, timing, failure state, and load separately. A correlation between two signals is not a causal result unless the controlled runs exclude the credible alternatives recorded here.`]},
    {heading:'Ownership and review',body:[`A Philippines-based offshore developer may build fixtures, run approved experiments, add focused instrumentation, and prepare a reversible patch. Internal data, security, platform, and release owners control sensitive access, production action, exceptions, and acceptance of remaining risk.`]},
    {heading:'Limitations',body:[`This study covers only ${scope}. It does not represent every client version, dependency delay, historical record, regional path, or future workload. The report must list missing cases, measurement uncertainty, failed runs, and the observation that would change the conclusion.`]},
  ],
  sources:[{name:sourceOne[0],url:sourceOne[1]},{name:sourceTwo[0],url:sourceTwo[1]},{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],
  faqs:[{question:'Does the result apply to the whole platform?',answer:'No. It applies to the declared unit, revision, workload, environment, and observation window.'},{question:'Who approves a production change based on this study?',answer:'The accountable internal owner reviews the raw evidence, inference limits, and remaining risk before authorizing production action.'}], related,
}));
