import type { BlogPost } from './data';

const entries = [
  { slug: 'offshore-developer-database-connection-pool-review-2026-09-01', title: 'How to review database connection pools with an offshore developer', audience: 'backend leads investigating saturation during traffic bursts', decision: 'which callers consume connections, how long they hold them, and where waiting becomes user-visible', evidence: 'pool metrics, query traces, timeout settings, and synthetic concurrency', edge: 'a cancelled request that releases its connection late' },
  { slug: 'offshore-developer-csp-rollout-checklist-2026-09-01', title: 'A Content Security Policy rollout checklist for offshore frontend work', audience: 'security and frontend owners tightening browser controls', decision: 'which resource classes can be blocked now and which need a measured migration', evidence: 'report-only violations, page templates, third-party inventory, and browser tests', edge: 'a required checkout script loaded from an undocumented host' },
  { slug: 'offshore-developer-pdf-generation-debugging-2026-09-01', title: 'How to brief PDF generation debugging across time zones', audience: 'product teams fixing inconsistent invoices and reports', decision: 'whether the defect begins in source data, layout rules, fonts, or the renderer', evidence: 'sanitized inputs, renderer versions, output diffs, and page-level checks', edge: 'a long translated address that forces an extra page' },
  { slug: 'offshore-developer-session-expiry-testing-2026-09-01', title: 'A session-expiry testing routine for an offshore developer', audience: 'application owners reviewing authentication behavior', decision: 'what the user sees when browser, server, and identity-provider sessions expire at different times', evidence: 'synthetic accounts, cookie metadata, controlled clocks, and redirect traces', edge: 'an expired session during an unsaved form submission' },
  { slug: 'offshore-developer-data-retention-job-review-2026-09-01', title: 'How to review a data-retention job with an offshore developer', audience: 'platform teams preparing a bounded deletion workflow', decision: 'which records qualify, which holds override deletion, and how completion is proven', evidence: 'synthetic records, policy mappings, dry-run output, and audit events', edge: 'a parent record whose child remains under an approved hold' },
  { slug: 'offshore-developer-feature-permission-matrix-2026-09-01', title: 'Build a feature-permission matrix before assigning offshore implementation', audience: 'product leads changing role-based application access', decision: 'which role can view, attempt, complete, and administer each action', evidence: 'role definitions, route guards, API checks, and deny-case fixtures', edge: 'a user whose role changes while a browser tab remains open' },
  { slug: 'offshore-developer-websocket-reconnect-review-2026-09-01', title: 'A WebSocket reconnect review for an offshore developer', audience: 'real-time product teams diagnosing missed or repeated updates', decision: 'how clients recover sequence and state after a broken connection', evidence: 'connection logs, sequence identifiers, replay fixtures, and network interruption tests', edge: 'two reconnect attempts racing after a device wakes' },
  { slug: 'offshore-developer-csv-import-mapping-2026-09-01', title: 'How to scope CSV import mapping for an offshore developer', audience: 'operations software teams accepting customer-supplied files', decision: 'how headers, types, locale rules, and rejected rows map into product records', evidence: 'synthetic files, mapping definitions, row errors, and reconciliation totals', edge: 'a spreadsheet-formatted identifier with a lost leading zero' },
  { slug: 'offshore-developer-mobile-deep-link-testing-2026-09-01', title: 'A mobile deep-link testing brief for an offshore developer', audience: 'mobile teams validating campaign and notification routes', decision: 'which destination opens for installed, signed-out, outdated, and first-install states', evidence: 'link definitions, device matrix, navigation traces, and fallback pages', edge: 'a valid link opened while an upgrade prompt is active' },
  { slug: 'offshore-developer-graphql-query-cost-review-2026-09-01', title: 'How to review GraphQL query cost with an offshore developer', audience: 'API owners protecting shared graph capacity', decision: 'which query shapes create disproportionate work and how clients receive a predictable limit', evidence: 'operation samples, resolver traces, depth and breadth measures, and rejection responses', edge: 'aliases that repeat an individually inexpensive resolver' },
  { slug: 'offshore-developer-email-bounce-handling-2026-09-01', title: 'An email-bounce handling checklist for offshore backend work', audience: 'growth and platform teams protecting transactional delivery', decision: 'how temporary, permanent, and policy failures change future send behavior', evidence: 'provider event fixtures, address state, retry schedules, and suppression logs', edge: 'a delayed bounce arriving after a newer successful delivery' },
  { slug: 'offshore-developer-accessibility-focus-order-2026-09-01', title: 'How to audit focus order with an offshore frontend developer', audience: 'frontend teams correcting keyboard navigation defects', decision: 'whether focus follows the visible task sequence through dynamic interface states', evidence: 'keyboard walkthroughs, DOM order, focus events, and component states', edge: 'a modal closing after its trigger has been removed' },
] as const;

const headings = ['Define the review decision', 'Map the operating surface', 'Prepare representative evidence', 'Test the uncomfortable case', 'Separate implementation from authority', 'Make the handoff reproducible'];

export const september1BlogBatch: readonly BlogPost[] = entries.map((entry) => {
  const paragraphs = [
    `Start with one decision: ${entry.decision}. This guide is for ${entry.audience}. Give the Philippines-based offshore developer a known revision, approved environment, observable expected result, and named reviewer. That boundary turns a broad concern into work another person can inspect and accept.`,
    `Trace the relevant path using ${entry.evidence}. Mark inputs, transformations, stored state, external dependencies, permissions, and user-visible outputs. Record facts separately from assumptions. A passing check supports only the path, data, and environment it actually exercised.`,
    `Create a compact evidence pack with a normal case, a denied or invalid case, a repeated action, and a recovery case. For every fixture, record setup, expected behavior, observed behavior, timestamps, and cleanup. Use synthetic values and approved access; do not copy customer data into a debugging artifact.`,
    `Include this topic-specific boundary case: ${entry.edge}. Compare it with the nearest passing case and change one condition at a time. Preserve the first point where behavior diverges. That point is more useful to a reviewer than a large collection of unrelated screenshots or logs.`,
    `The offshore developer can reproduce behavior, prepare a focused change, add regression coverage, and document limitations. Internal owners retain authority over architecture exceptions, production access, protected data, customer communication, irreversible operations, and accepted risk. Escalate when the investigation crosses those lines.`,
    `Close with starting and ending revisions, changed paths, fixtures, commands, passed and skipped checks, evidence links, known gaps, rollback notes, reviewer, and next authorized action. A useful cross-time-zone handoff lets the next work window review or continue without reconstructing the investigation.`
  ];
  return {
    slug: entry.slug,
    title: entry.title,
    excerpt: `A practical operating guide for ${entry.audience}, with scoped evidence, edge cases, and explicit review ownership.`,
    minutes: 7,
    datePublished: '2026-09-01',
    dateModified: '2026-09-01',
    revision: `daily-batch-2026-09-01-${entry.slug}`,
    keyTakeaways: [`Decide ${entry.decision}.`, `Inspect ${entry.evidence}.`, `Keep approval and accepted risk with the named internal owner.`],
    sections: paragraphs.map((body, index) => ({ heading: headings[index], body: [body] })),
    table: { title: 'Review evidence record', columns: ['Review point', 'Required evidence', 'Owner'], rows: [['Behavior', 'Expected and observed result', 'Developer'], ['Boundary', entry.edge, 'Internal reviewer'], ['Handoff', 'Limits and next authorized action', 'Named next owner']] },
    quote: { text: 'A distributed change is ready for review when its behavior, limits, and next decision are visible.', by: 'Developer Offshore editorial team', role: 'Operational guidance', sourceUrl: 'https://developeroffshore.com/services' },
    relatedLinks: [{ label: 'Developer services', href: '/services', note: 'Review supported development lanes.' }, { label: 'Research library', href: '/research', note: 'Read evidence-led reports.' }, { label: 'Contact', href: '/contact-us', note: 'Discuss a bounded role.' }],
    faqs: [{ question: 'What can the offshore developer own?', answer: 'The developer can inspect, reproduce, implement, test, and document the approved technical slice. Internal owners retain protected access, exceptions, release approval, and accepted risk.' }, { question: 'What makes the handoff reviewable?', answer: `Include revisions, fixtures, checks, limitations, and evidence for ${entry.edge}, plus a named reviewer and next action.` }],
    sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'OWASP Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' }, { name: 'Google Engineering Practices', url: 'https://google.github.io/eng-practices/review/' }],
  };
});
