import type { BlogPost } from './data';

const entries = [
  { slug: 'offshore-developer-webhook-signature-review-2026-09-02', title: 'How to review webhook signatures with an offshore developer', audience: 'integration teams receiving external events', decision: 'where authenticity, freshness, and replay protection are enforced', evidence: 'signed fixtures, raw request bytes, timestamp tolerances, and replay attempts', edge: 'a valid signature delivered again after the accepted time window' },
  { slug: 'offshore-developer-oauth-consent-flow-checklist-2026-09-02', title: 'An OAuth consent-flow checklist for offshore implementation', audience: 'product teams adding third-party authorization', decision: 'which scopes are requested and how state is bound to the initiating browser', evidence: 'scope inventory, redirect traces, state checks, and denied-consent fixtures', edge: 'a callback opened in a different browser session' },
  { slug: 'offshore-developer-bulk-export-memory-review-2026-09-02', title: 'How to review bulk-export memory use with an offshore developer', audience: 'backend owners preparing large customer exports', decision: 'whether records stream within a declared resource budget', evidence: 'representative row counts, heap profiles, stream events, and checksums', edge: 'a client disconnect between buffered chunks' },
  { slug: 'offshore-developer-localization-fallback-testing-2026-09-02', title: 'A localization fallback test plan for an offshore frontend developer', audience: 'frontend leads expanding supported languages', decision: 'which translation wins when locale data is unavailable', evidence: 'locale matrices, missing-key logs, rendered views, and plural fixtures', edge: 'a regional locale with one missing namespace and a different plural rule' },
  { slug: 'offshore-developer-audit-log-integrity-checklist-2026-09-02', title: 'An audit-log integrity checklist for offshore backend work', audience: 'security teams reviewing accountable events', decision: 'which actions create durable and trustworthy audit events', evidence: 'event schemas, synthetic actions, denied cases, ordering checks, and access controls', edge: 'an action succeeding while the audit destination is unavailable' },
  { slug: 'offshore-developer-payment-idempotency-review-2026-09-02', title: 'How to review payment idempotency with an offshore developer', audience: 'commerce teams preventing duplicate operations', decision: 'how repeated requests map to one business result', evidence: 'idempotency keys, provider fixtures, ledger records, and concurrent tests', edge: 'two identical requests arriving before the first result is persisted' },
  { slug: 'offshore-developer-search-ranking-regression-2026-09-02', title: 'A search-ranking regression brief for an offshore developer', audience: 'product teams tuning search', decision: 'which representative queries improve, regress, or remain unchanged', evidence: 'versioned query sets, labeled results, rank diffs, and zero-result checks', edge: 'a rare exact identifier displaced by popular partial matches' },
  { slug: 'offshore-developer-file-upload-quarantine-2026-09-02', title: 'How to scope file-upload quarantine for offshore development', audience: 'application owners accepting untrusted files', decision: 'when an upload may leave isolated storage', evidence: 'file-type fixtures, scan outcomes, storage policies, and release events', edge: 'a scan timing out after upload acknowledgement' },
  { slug: 'offshore-developer-rate-limit-client-testing-2026-09-02', title: 'A rate-limit client testing routine for an offshore developer', audience: 'client teams using capacity-limited APIs', decision: 'how the client delays, retries, and informs users', evidence: 'response headers, controlled clocks, retry traces, and concurrent callers', edge: 'multiple workers retrying together at the same reset time' },
  { slug: 'offshore-developer-schema-validation-boundary-2026-09-02', title: 'Define a schema-validation boundary before offshore implementation', audience: 'API teams changing structured contracts', decision: 'which layer rejects malformed or semantically invalid values', evidence: 'versioned schemas, negative fixtures, boundary values, and error responses', edge: 'a valid payload whose fields form an impossible business state' },
  { slug: 'offshore-developer-cache-warming-runbook-2026-09-02', title: 'A cache-warming runbook for an offshore developer', audience: 'platform teams reducing cold-start load', decision: 'which keys are safe and useful to populate', evidence: 'key inventories, request traces, load limits, hit rates, and expiry checks', edge: 'a warm-up job running against data changing during deployment' },
  { slug: 'offshore-developer-soft-delete-recovery-review-2026-09-02', title: 'How to review soft-delete recovery with an offshore developer', audience: 'data owners designing reversible deletion', decision: 'what is hidden, retained, restored, or permanently removed', evidence: 'state transitions, related-record fixtures, authorization tests, and audit events', edge: 'a restore after a unique value is claimed by a new record' },
] as const;

const headings = ['Name the acceptance decision', 'Trace the complete path', 'Build the evidence pack', 'Exercise the boundary case', 'Keep authority explicit', 'Write the next-window handoff'];

export const september2BlogBatch: readonly BlogPost[] = entries.map((entry) => ({
  slug: entry.slug,
  title: entry.title,
  excerpt: `A practical guide for ${entry.audience}, using focused tests, a difficult boundary case, and explicit review ownership.`,
  minutes: 7,
  datePublished: '2026-09-02',
  dateModified: '2026-09-02',
  revision: `daily-batch-2026-09-02-${entry.slug}`,
  keyTakeaways: [`Resolve ${entry.decision}.`, `Collect ${entry.evidence}.`, 'Leave accepted risk with the internal owner.'],
  sections: [
    `Frame one acceptance decision: ${entry.decision}. This article is for ${entry.audience}. Give the Philippines-based developer a fixed revision, approved environment, observable result, and reviewer who can accept the outcome.`,
    `Follow inputs through validation, transformation, storage, dependencies, permissions, and visible output. Use ${entry.evidence}. Label observations, assumptions, and missing evidence separately.`,
    'Prepare a normal fixture, invalid or denied fixture, repeated action, and recovery fixture. Record setup, expected and observed results, time, revision, and cleanup. Keep customer data and production credentials outside the evidence pack.',
    `Test the uncomfortable case: ${entry.edge}. Hold the nearest passing fixture constant and change one condition at a time. Capture the first divergence and consequence.`,
    'The developer may reproduce behavior, implement a bounded correction, add regression coverage, and document tradeoffs. Internal owners keep authority over protected data, production access, irreversible actions, external communication, and residual risk.',
    'Hand off starting and ending revisions, changed paths, fixtures, commands, passed and skipped checks, evidence links, limitations, rollback notes, reviewer, and next authorized action.',
  ].map((body, index) => ({ heading: headings[index], body: [body] })),
  table: { title: 'Acceptance evidence record', columns: ['Checkpoint', 'Evidence', 'Owner'], rows: [['Decision', entry.decision, 'Internal reviewer'], ['Boundary', entry.edge, 'Developer and reviewer'], ['Handoff', 'Revisions, checks, limits, and next action', 'Named next owner']] },
  quote: { text: 'A technical handoff is useful when the next owner can see the result, its boundary, and the decision still open.', by: 'Developer Offshore editorial team', role: 'Operational guidance', sourceUrl: 'https://developeroffshore.com/services' },
  relatedLinks: [{ label: 'Developer services', href: '/services', note: 'Review supported lanes.' }, { label: 'Research library', href: '/research', note: 'Inspect evidence-led reports.' }, { label: 'Contact', href: '/contact-us', note: 'Discuss a bounded role.' }],
  faqs: [{ question: 'What work can the offshore developer own?', answer: 'They can reproduce, implement, test, and document the approved slice. Internal owners retain protected access, exceptions, release approval, and accepted risk.' }, { question: 'What should the reviewer receive?', answer: `Fixtures and results for ${entry.edge}, plus revisions, limitations, rollback notes, and the next decision.` }],
  sources: [{ name: 'NIST Secure Software Development Framework', url: 'https://csrc.nist.gov/pubs/sp/800/218/final' }, { name: 'OWASP Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' }, { name: 'Google Engineering Practices', url: 'https://google.github.io/eng-practices/review/' }],
}));
