import type { ResearchPost } from './fleet-data';

const studies = [
  ['offshore-developer-cache-stampede-study-2026-09-04','When does cache expiration create a request stampede?','one cached key under controlled concurrent demand','origin requests, waiter latency, lock ownership, and stale responses','a low average origin rate can conceal a damaging burst at expiry',['Cloudflare: Cache stampede','https://blog.cloudflare.com/sometimes-i-cache/'],['AWS Builders Library: Challenges with distributed systems','https://aws.amazon.com/builders-library/challenges-with-distributed-systems/']],
  ['offshore-developer-token-refresh-rotation-study-2026-09-04','What evidence shows refresh-token rotation detects reuse?','one synthetic account and token family','token lineage, redemption times, revocation events, and resulting sessions','network retry can resemble malicious reuse',['OAuth 2.0 Security Best Current Practice','https://www.rfc-editor.org/rfc/rfc9700.html'],['OWASP Session Management Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html']],
  ['offshore-developer-cdn-cache-variant-study-2026-09-04','Can a CDN cache key preserve every response variant?','one route with a declared request-variant matrix','cache keys, Vary values, response hashes, ages, and purge results','two correct isolated responses can still collide in shared cache',['HTTP Caching (RFC 9111)','https://www.rfc-editor.org/rfc/rfc9111.html'],['MDN: Vary header','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Vary']],
  ['offshore-developer-outbox-delivery-study-2026-09-04','What does an outbox pattern actually guarantee?','one database transaction and its downstream message','commit records, outbox rows, relay attempts, consumer effects, and duplicates','atomic persistence does not imply exactly-once downstream behavior',['AWS Prescriptive Guidance: Transactional outbox pattern','https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html'],['Microservices.io: Transactional outbox','https://microservices.io/patterns/data/transactional-outbox.html']],
  ['offshore-developer-clock-skew-expiry-study-2026-09-04','How much clock skew can an expiry check tolerate?','one signed artifact checked across controlled clocks','issuer time, verifier time, validity bounds, leeway, and rejection reasons','generous leeway can hide broken synchronization while widening acceptance',['NIST Internet Time Service','https://www.nist.gov/pml/time-and-frequency-division/time-distribution/internet-time-service-its'],['JWT (RFC 7519)','https://www.rfc-editor.org/rfc/rfc7519.html']],
] as const;

const related = [{title:'Research library',href:'/research'},{title:'Developer services',href:'/services'},{title:'Daily developer guides',href:'/blog'}] as const;

export const september4ResearchBatch: readonly ResearchPost[] = studies.map(([slug,title,unit,signals,counter,s1,s2]) => ({
  slug, title, published:'2026-09-04', excerpt:`A source-backed research method for ${unit}, separating measured behavior from inference and operational approval.`,
  keyStats:['1 bounded unit of analysis','5 evidence classes compared','2 primary or authoritative technical references'],
  takeaways:[`Measure ${signals}.`,`Challenge the result: ${counter}.`,'Treat the conclusion as bounded evidence, not a universal guarantee.'],
  sections:[
    {heading:'Research question and scope',body:[`This report asks: ${title} The unit is ${unit}, tied to a named revision, environment, workload, and observation window. It does not certify the wider platform or predict every future workload. The goal is a decision that another reviewer can reproduce.`]},
    {heading:'Method',body:[`Create synthetic normal, boundary, repeated, interrupted, and recovery cases. Record ${signals}. Preserve raw observations before interpreting them, keep time sources explicit, and rerun the nearest passing case whenever a variable changes.`]},
    {heading:'What public guidance contributes',body:[`${s1[0]} and ${s2[0]} describe relevant mechanisms and controls. They help shape the test, but they cannot prove local behavior. Only evidence from the declared system revision supports a claim about that system.`]},
    {heading:'Counterevidence',body:[`Actively test the competing explanation that ${counter}. Vary concurrency, identity, timing, and failure state separately. Report disagreeing signals instead of averaging them into a reassuring headline.`]},
    {heading:'Decision and ownership',body:[`A Philippines-based offshore developer can prepare fixtures, run approved comparisons, add focused instrumentation, and document a reversible correction. Internal system, security, privacy, and release owners retain sensitive access, policy exceptions, production changes, and acceptance of residual risk.`]},
    {heading:'Limitations and conclusion',body:[`A controlled observation cannot cover every dependency delay, historical state, client implementation, or future traffic shape. The evidence supports only ${unit}. State missing cases, measurement error, and the condition that would falsify the conclusion before choosing to correct, observe longer, revert, or escalate.`]},
  ],
  sources:[{name:s1[0],url:s1[1]},{name:s2[0],url:s2[1]},{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],
  faqs:[{question:'Does this research establish a universal threshold?',answer:'No. It provides a reproducible method and bounded evidence for the declared unit and observation window.'},{question:'Who approves production action?',answer:'The accountable internal owner approves production access, exceptions, release action, and residual risk.'}], related,
}));
