import type { ResearchPost } from './fleet-data';

const studies = [
  ['offshore-developer-postgresql-transaction-retry-study-2026-09-08','Which PostgreSQL transaction failures are safe to retry?','one synthetic transaction under controlled serialization failures','SQLSTATE, attempt number, transaction boundaries, side-effect count, row versions, and latency','a database retry can still duplicate work performed outside the transaction',['PostgreSQL: Transaction Isolation','https://www.postgresql.org/docs/current/transaction-iso.html'],['PostgreSQL: Error Codes','https://www.postgresql.org/docs/current/errcodes-appendix.html']],
  ['offshore-developer-kubernetes-termination-grace-study-2026-09-08','How much Kubernetes termination grace does a worker need?','one worker deployment processing jobs with declared duration bands','termination time, pod conditions, active jobs, acknowledgement time, exit code, and redelivery count','a clean process exit does not prove that an in-flight job was acknowledged',['Kubernetes: Pod Lifecycle','https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/'],['Kubernetes: Termination of Pods','https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination-flow']],
  ['offshore-developer-http-cache-vary-study-2026-09-08','Does the HTTP Vary header prevent the wrong response from being reused?','one cacheable endpoint tested with a fixed set of request-header variants','request headers, cache status, Age, Vary, response hash, and origin request count','a correct origin response says nothing about a previously stored intermediary entry',['RFC 9111: HTTP Caching','https://www.rfc-editor.org/rfc/rfc9111.html'],['MDN: Vary header','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Vary']],
  ['offshore-developer-opentelemetry-context-loss-study-2026-09-08','Where does trace context disappear in an asynchronous job?','one request-to-queue-to-worker path in a controlled environment','trace and span IDs, propagation headers, producer links, consumer spans, timestamps, and sampling decisions','a missing parent may result from sampling rather than failed propagation',['OpenTelemetry: Context propagation','https://opentelemetry.io/docs/concepts/context-propagation/'],['W3C Trace Context','https://www.w3.org/TR/trace-context/']],
  ['offshore-developer-browser-bfcache-state-study-2026-09-08','What application state returns from the browser back-forward cache?','one authenticated page across a declared browser and navigation matrix','navigation type, page lifecycle events, memory state, network requests, auth state, and rendered values','a restored page can display stale state even when the next API request is current',['web.dev: Back/forward cache','https://web.dev/articles/bfcache'],['MDN: Window pageshow event','https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event']],
] as const;
const related = [{title:'Research library',href:'/research'},{title:'Developer services',href:'/services'},{title:'Daily developer guides',href:'/blog'}] as const;
export const september8ResearchBatch: readonly ResearchPost[] = studies.map(([slug,title,scope,signals,rival,sourceOne,sourceTwo], index) => ({
  slug, title, published:'2026-09-08', excerpt:`A small, reproducible study of ${scope}. The report separates observed behavior from inference and records what the test cannot establish.`,
  keyStats:['1 declared unit of analysis',`${6 + (index % 2)} recorded signal classes`,'2 mechanism-specific primary references'],
  takeaways:[`Capture ${signals}.`,`Check the competing explanation that ${rival}.`,'Treat the finding as local to the recorded revision, workload, environment, and observation window.'],
  sections:[
    {heading:'Research question and scope',body:[`The question is: ${title} The unit of analysis is ${scope}. The protocol fixes the code revision, configuration, workload, identities, and observation window before a run begins.`]},
    {heading:'Method',body:[`Create baseline, boundary, repeated, interrupted, and recovery runs with synthetic data. Record ${signals}. Preserve raw output before adding notes, identify the clock behind each timestamp, and repeat the closest passing run after every isolated change.`]},
    {heading:'How the sources inform the protocol',body:[`${sourceOne[0]} defines the main mechanism used in the test. ${sourceTwo[0]} provides a second standards or implementation view. They determine what the fixtures should exercise, but neither source proves how this particular system behaves.`]},
    {heading:'Counterevidence and inference limits',body:[`Try to overturn the first explanation by testing whether ${rival}. Change identity, timing, failure state, and load separately. A correlation between two signals is not a causal result unless the controlled runs exclude the credible alternatives recorded here.`]},
    {heading:'Ownership and review',body:[`A Philippines-based offshore developer may build fixtures, run approved experiments, add focused instrumentation, and prepare a reversible patch. Internal data, security, platform, and release owners control sensitive access, production action, exceptions, and acceptance of remaining risk.`]},
    {heading:'Limitations',body:[`This study covers only ${scope}. It does not represent every client version, dependency delay, historical record, regional path, or future workload. The report must list missing cases, measurement uncertainty, failed runs, and the observation that would change the conclusion.`]},
  ],
  sources:[{name:sourceOne[0],url:sourceOne[1]},{name:sourceTwo[0],url:sourceTwo[1]},{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],
  faqs:[{question:'Does the result apply to the whole platform?',answer:'No. It applies to the declared unit, revision, workload, environment, and observation window.'},{question:'Who approves a production change based on this study?',answer:'The accountable internal owner reviews the raw evidence, inference limits, and remaining risk before authorizing production action.'}], related,
}));
