import type { BlogPost } from './data';

const topics = [
['offshore-developer-http-cache-vary-review-2026-09-10','Audit a Vary header before it fragments your cache','web teams troubleshooting uneven CDN hit rates','show which request headers produce distinct stored responses','request headers, cache key, Age, Vary, response hash, and cache status','a harmless high-cardinality header enters the cache key'],
['offshore-developer-postgresql-transaction-id-wraparound-check-2026-09-10','Check PostgreSQL transaction ID age before maintenance becomes urgent','database teams responsible for tables with uneven write patterns','rank tables by transaction age and confirm vacuum can advance their frozen horizon','relfrozenxid age, database age, vacuum history, blockers, table size, and alert threshold','an idle transaction prevents cleanup on the oldest table'],
['offshore-developer-oauth-device-code-polling-review-2026-09-10','Keep OAuth device-code polling inside the protocol limits','identity teams supporting input-constrained clients','verify interval changes, expiry, denial, and successful authorization without a busy loop','device code, user-code state, poll interval, error response, expiry, and token result','the server returns slow_down twice before the user approves'],
['offshore-developer-nextjs-route-cache-tag-audit-2026-09-10','Trace a stale Next.js page back to its cache tags','Next.js teams using on-demand revalidation','connect each mutation to the tags and routes whose rendered data must change','build ID, route, data request, cache tag, mutation time, invalidation call, and rendered value','two pages share data but only one route is revalidated'],
['offshore-developer-kubernetes-pod-termination-drain-2026-09-10','Drain Kubernetes traffic before a pod exits','platform teams deploying services with long-lived requests','measure the sequence from termination notice to endpoint removal and process exit','deletion time, readiness, EndpointSlice state, open requests, signals, grace period, and exit code','a request begins just before the pod receives SIGTERM'],
['offshore-developer-typescript-project-reference-build-2026-09-10','Diagnose a stale TypeScript project-reference build','monorepo teams using composite TypeScript projects','prove which declaration output and build metadata a downstream package consumed','source revision, tsconfig references, build-info file, declaration hash, command, and import result','an upstream type changes without refreshed declarations'],
['offshore-developer-redis-stream-pending-entry-recovery-2026-09-10','Recover a Redis Stream pending entry without double-processing it','event teams using Redis consumer groups','separate an abandoned delivery from work still owned by a slow consumer','stream ID, consumer, idle time, delivery count, claim result, side-effect key, and acknowledgement','the first consumer finishes an external write after another claims the entry'],
['offshore-developer-webauthn-counter-anomaly-review-2026-09-10','Handle a WebAuthn signature-counter anomaly without guessing','authentication teams evaluating authenticator clone signals','record authenticator capabilities and apply policy to a non-increasing counter','credential ID, authenticator data, stored and returned counters, backup flags, result, and policy action','a multi-device credential always returns a zero counter'],
['offshore-developer-cors-preflight-cache-debug-2026-09-10','Debug a CORS preflight result after a configuration change','API teams changing allowed origins, methods, or headers','reproduce the browser decision with the exact origin and preflight cache conditions','browser version, top-level site, origin, method, requested headers, max-age, and network trace','the policy changes while the browser holds a successful preflight result'],
['offshore-developer-github-actions-concurrency-cancel-review-2026-09-10','Review what GitHub Actions cancels in a concurrency group','delivery teams preventing obsolete builds from deploying','map workflow and job concurrency keys to the runs they queue or cancel','event, ref, workflow, group expression, run ID, job state, cancellation time, and deployment state','a manual hotfix shares a group with an automatic branch run'],
['offshore-developer-sqlite-wal-checkpoint-investigation-2026-09-10','Investigate a SQLite WAL file that keeps growing','application teams embedding SQLite under concurrent reads','identify which readers delay checkpoints and what each checkpoint mode completes','journal mode, WAL frames, reader start, checkpoint result, busy count, file size, and latency','a long report transaction overlaps many short writes'],
['offshore-developer-grpc-deadline-propagation-audit-2026-09-10','Carry a gRPC deadline across service boundaries','service teams tracing requests through several RPC hops','confirm that each hop receives a smaller remaining budget and stops work on expiry','start time, timeout header, remaining budget, hop latency, status, cancellation, and cleanup','an intermediate service retries after most of the caller budget is gone'],
] as const;

export const september10BlogBatch: readonly BlogPost[] = topics.map(([slug,title,audience,decision,evidence,edge],index)=>({
slug,title,excerpt:`A practical review for ${audience}. It defines a replayable check, the evidence to retain, and the decision that stays with the system owner.`,minutes:10+(index%3),datePublished:'2026-09-10',dateModified:'2026-09-10',revision:`daily-blog-2026-09-10-${slug}`,
keyTakeaways:[`Write the question plainly: ${decision}.`,`Keep ${evidence}.`,`Include the uncomfortable case where ${edge}.`],
sections:[
{heading:'Name the behavior under review',body:[`This review is for ${audience}. Start with one observable claim: ${decision}. Record the repository revision, environment, test identity, time source, and reviewer.`,`Keep the first run small. A teammate in another time zone should be able to repeat it without reconstructing assumptions from chat.`]},
{heading:'Capture an ordinary run',body:[`Save ${evidence}. Use synthetic or approved test data and avoid broad production access. The baseline is useful only when its inputs and expected outcome are written down.`,`If the baseline fails, repair the fixture or narrow the question before adding timing, load, or failure conditions.`]},
{heading:'Exercise the boundary case',body:[`Test the case most likely to expose a bad assumption: ${edge}. Change one condition, preserve raw output, and timestamp both the trigger and result.`,`Repeat the nearest passing case after the failure. That comparison is more useful than a pile of unrelated logs.`]},
{heading:'Make the smallest supported correction',body:[`Trace the evidence to the first boundary that violates the stated behavior. Add a focused regression check, prepare a reversible correction, and rerun both cases.`,`Record adjacent risks separately, with an owner and a reason they remain outside this change.`]},
{heading:'Hand off the decision',body:[`An offshore developer can design fixtures, inspect code, prepare a patch, and assemble evidence. The internal owner retains protected credentials, sensitive data, exceptions, and production release authority.`,`The handoff names revisions, changed files, commands, passed and skipped checks, rollback, remaining uncertainty, and the next owner.`]},
],
table:{title:'Review record',columns:['Checkpoint','Evidence','Owner'],rows:[['Baseline',evidence,'Assigned reviewer'],['Boundary case',edge,'Technical owner'],['Release','Checks, limits, and rollback note','Internal release owner']]},
relatedLinks:[{label:'Developer services',href:'/services',note:'Choose a bounded engineering lane.'},{label:'Research library',href:'/research',note:'Use a measured protocol.'},{label:'Contact',href:'/contact-us',note:'Define the first outcome.'}],
faqs:[{question:'Can an offshore developer run this review?',answer:'Yes, with scoped access, approved fixtures, a fixed revision, and a named reviewer.'},{question:'Who approves production?',answer:'The accountable internal owner reviews the evidence, limits, and rollback plan.'}],
sources:index%3===0?[{name:'MDN Web Docs',url:'https://developer.mozilla.org/en-US/docs/Web'},{name:'IETF Datatracker',url:'https://datatracker.ietf.org/'}]:index%3===1?[{name:'PostgreSQL documentation',url:'https://www.postgresql.org/docs/current/'},{name:'Kubernetes documentation',url:'https://kubernetes.io/docs/'}]:[{name:'GitHub documentation',url:'https://docs.github.com/en'},{name:'Google Engineering Practices',url:'https://google.github.io/eng-practices/review/'}],
}));
