import type { BlogPost } from './data';

type Topic = { slug:string; title:string; reader:string; result:string; inputs:string; edge:string; service:string; serviceLabel:string; source:{name:string;url:string} };

const topics: readonly Topic[] = [
  {slug:'offshore-developer-first-30-days-plan',title:'First 30 Days Plan for an Offshore Developer',reader:'engineering managers onboarding a Philippines-based developer',result:'move from a reproducible setup to one reviewed production-shaped change without widening access too early',inputs:'a role brief, repository map, supported setup, starter tickets, review owners, and access expiry dates',edge:'the starter ticket depends on undocumented environment state or a decision nobody owns',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'GitLab handbook: onboarding',url:'https://handbook.gitlab.com/handbook/people-group/general-onboarding/'}},
  {slug:'offshore-developer-codebase-tour-checklist',title:'Codebase Tour Checklist for an Offshore Developer',reader:'technical leads introducing a distributed contributor to an unfamiliar application',result:'explain the paths, runtime boundaries, ownership, and verification commands needed for a safe first change',inputs:'entry points, dependency boundaries, data flows, test commands, deploy path, and named maintainers',edge:'the tour lists folders but never demonstrates how a request becomes a tested response',service:'/services/next-js-application-development',serviceLabel:'Next.js application development',source:{name:'GitHub Docs: About READMEs',url:'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes'}},
  {slug:'offshore-developer-ticket-readiness-checklist',title:'Ticket Readiness Checklist for Offshore Development Work',reader:'product and engineering leads preparing asynchronous tickets',result:'give a developer enough context to begin safely while making missing decisions visible',inputs:'the user outcome, current behavior, acceptance examples, affected system, constraints, and decision owner',edge:'acceptance criteria prescribe an implementation but omit the business behavior that must remain true',service:'/services/react-frontend-development',serviceLabel:'React frontend development',source:{name:'Atlassian: user stories',url:'https://www.atlassian.com/agile/project-management/user-stories'}},
  {slug:'offshore-developer-overlap-hours-plan',title:'How to Plan Overlap Hours With a Philippines Development Team',reader:'managers coordinating Philippine and North American or European workdays',result:'reserve live overlap for decisions and use written handoffs for normal delivery',inputs:'both local work windows, decision latency, meeting load, reviewer availability, and escalation routes',edge:'a recurring meeting forces permanent night work but still lacks an empowered decision maker',service:'/services/devops-release-support',serviceLabel:'DevOps release support',source:{name:'GitLab handbook: asynchronous communication',url:'https://handbook.gitlab.com/handbook/company/culture/all-remote/asynchronous/'}},
  {slug:'offshore-developer-definition-of-done',title:'Definition of Done for an Offshore Development Team',reader:'delivery leads whose completed tickets return for missing tests, notes, or approvals',result:'create a shared completion gate covering behavior, evidence, review, release notes, and follow-up ownership',inputs:'acceptance checks, test expectations, review rules, documentation, release gates, and operational evidence',edge:'a pull request is merged even though the customer behavior was never checked in a production-shaped environment',service:'/services/qa-automation-engineering',serviceLabel:'QA automation engineering',source:{name:'Scrum Guide',url:'https://scrumguides.org/scrum-guide.html'}},
  {slug:'offshore-developer-branch-protection-setup',title:'Branch Protection Setup for Offshore Developer Contributions',reader:'repository administrators granting a new external contributor write access',result:'protect important branches with review and status checks while preserving a usable contribution path',inputs:'branch inventory, required checks, reviewer groups, bypass roles, merge method, and emergency procedure',edge:'an administrator bypass becomes the normal way to merge because required checks are unreliable',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'GitHub Docs: protected branches',url:'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches'}},
  {slug:'offshore-developer-environment-access-matrix',title:'Environment Access Matrix for Offshore Developers',reader:'engineering and security owners separating local, test, staging, and production permissions',result:'match each task to named access, approval, duration, logging, and removal requirements',inputs:'environments, job duties, data classes, identity controls, approvers, logs, and offboarding triggers',edge:'staging contains copied customer data and is treated as a low-risk shared environment',service:'/services/devops-release-support',serviceLabel:'DevOps release support',source:{name:'NIST: least privilege',url:'https://csrc.nist.gov/glossary/term/least_privilege'}},
  {slug:'offshore-developer-reviewer-capacity-plan',title:'Reviewer Capacity Plan for an Offshore Development Team',reader:'engineering managers adding delivery capacity without adding review capacity',result:'forecast review demand, assign coverage, and prevent completed work from waiting across time zones',inputs:'expected pull request volume, change size, reviewer specialties, overlap windows, service levels, and absence cover',edge:'several developers depend on one reviewer who is also the only incident responder',service:'/services/operations-support',serviceLabel:'Development operations support',source:{name:'Google Engineering Practices: code review speed',url:'https://google.github.io/eng-practices/review/reviewer/speed.html'}},
  {slug:'offshore-developer-escalation-matrix',title:'Escalation Matrix for Offshore Software Development',reader:'distributed teams that lose a workday when risk or ownership is unclear',result:'route technical, product, security, access, and production questions to an accountable owner with a safe default',inputs:'issue classes, severity examples, primary and backup owners, response targets, channels, and stop rules',edge:'a developer treats silence as approval for a change that affects customer data or production availability',service:'/services/operations-support',serviceLabel:'Development operations support',source:{name:'Google SRE Workbook: incident response',url:'https://sre.google/workbook/incident-response/'}},
  {slug:'offshore-developer-knowledge-transfer-plan',title:'Knowledge Transfer Plan for an Offshore Developer',reader:'application owners transferring a recurring engineering lane without creating a single point of failure',result:'turn demonstrations into reproducible tasks, reviewed evidence, and shared operational ownership',inputs:'task inventory, frequency, prerequisites, examples, failure cases, runbooks, and backup operators',edge:'knowledge transfer ends after a screen recording that nobody has replayed from a clean starting point',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'Atlassian: knowledge sharing',url:'https://www.atlassian.com/work-management/knowledge-sharing'}},
  {slug:'offshore-developer-weekly-delivery-report',title:'Weekly Delivery Report for an Offshore Development Team',reader:'buyers who need an accurate view of outcomes, waiting time, quality, and next decisions',result:'summarize shipped outcomes and delivery constraints without turning activity counts into performance claims',inputs:'accepted tickets, deployment evidence, review latency, defects, blocked hours, risks, and next decisions',edge:'the report celebrates commits and hours while the highest-value item is still waiting for acceptance',service:'/services/operations-support',serviceLabel:'Development operations support',source:{name:'DORA: software delivery performance',url:'https://dora.dev/guides/dora-metrics-four-keys/'}},
  {slug:'offshore-developer-offboarding-checklist',title:'Offboarding Checklist for an Offshore Developer',reader:'engineering, security, and delivery leads closing or changing an external assignment',result:'remove access, transfer work and knowledge, preserve evidence, and confirm ownership without disrupting releases',inputs:'identity records, repository teams, secrets, devices, open work, documentation, environments, and vendor contacts',edge:'the account is disabled but deploy keys, personal access tokens, or shared credentials remain valid',service:'/services/admin-support',serviceLabel:'Engineering admin support',source:{name:'CISA: identity and access management',url:'https://www.cisa.gov/resources-tools/services/identity-and-access-management'}},
];

const sharedSources = [
  {name:'GitHub Docs: pull requests',url:'https://docs.github.com/en/pull-requests'},
  {name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/Projects/ssdf'},
] as const;

function makePost(t:Topic, index:number):BlogPost {
  const owner = index % 3 === 0 ? 'engineering lead' : index % 3 === 1 ? 'delivery lead' : 'system owner';
  return {slug:t.slug,title:t.title,excerpt:`A practical Philippines-focused guide for ${t.reader}. Set a bounded outcome, usable evidence, accountable decisions, and safe access before work begins.`,minutes:12+(index%3),datePublished:'2026-09-19',revision:`daily-blog-2026-09-19-${t.slug}`,
    keyTakeaways:[`Define the result first: ${t.result}.`,`Prepare the smallest useful input set: ${t.inputs}.`,'Keep business priority, sensitive access, accepted risk, and release approval with named client-side owners.'],
    sections:[
      {heading:'Begin with the decision this work must support',body:[`This guide is for ${t.reader}. Start by writing the decision or operational result the team needs, not a broad instruction to “take ownership.” The target here is to ${t.result}. A specific result lets a Philippines-based developer plan a useful sequence and lets the buyer team decide whether the work is actually complete.`,`Name the ${owner} who accepts the result, the reviewer who checks it, and the safest action while either person is unavailable. Record the repository, environment, fixed revision, expected completion window, and customer impact. Those details make asynchronous work faster because uncertainty appears as a question instead of becoming an invisible assumption.`]},
      {heading:'Prepare a bounded starting packet',body:[`Provide ${t.inputs}. Link durable records instead of pasting secrets or large log extracts into a ticket. Use synthetic examples where customer information is not required, and identify the exact environment in which each example was observed. A developer should be able to reproduce the starting state without borrowing somebody else’s account or machine.`,`The packet should say what is outside scope as clearly as what is included. Separate optional cleanup from the required outcome, list known constraints, and identify decisions already made. If a necessary input is missing, assign an owner and due time. Do not fill the gap with an invented company rule, unsupported customer claim, or guessed production behavior.`]},
      {heading:'Turn the outcome into reviewable slices',body:[`Split the lane into discovery, proposal, implementation, verification, and handoff. Discovery confirms the current state. The proposal identifies the smallest useful change and its tradeoffs. Implementation stays within approved files and access. Verification repeats the baseline and one relevant failure case. The handoff asks for a specific decision and links the evidence.`,`Keep each slice small enough that a reviewer can understand it during one focused session. Avoid combining dependency upgrades, formatting, architecture changes, and product behavior unless they are inseparable. Put adjacent work in a follow-up list with impact and owner. This reduces review delay and gives the team a practical rollback boundary.`]},
      {heading:'Set access and approval boundaries',body:[`Use named accounts, least privilege, and the company’s existing approval path. Give access only to repositories, boards, documentation, and non-production systems required for the current slice. Record who approved it, when it expires, and how it will be removed. Production credentials, billing changes, security exceptions, and final releases should remain controlled by accountable internal owners.`,`If broader access appears necessary, first ask whether an internal owner can run a protected command, provide a sanitized extract, or review a proposed change. Expanding access may be reasonable, but it should follow a recorded decision rather than a password sent through chat. Stop when the next action would expose sensitive data, create spend, or change live behavior without approval.`]},
      {heading:'Test the uncomfortable case',body:[`The important edge case is when ${t.edge}. Model it with a safe fixture or reproduce it in an approved non-production environment. Capture the trigger, expected result, observed result, and first boundary that behaves differently. Then run the nearest passing case so the reviewer can distinguish a real control from a permanently failing check.`,`Do not convert a test into an uncontrolled live experiment. State any skipped check and the reason; silence is not proof that a condition passed. When a boundary cannot be tested safely, prepare the command, expected signal, recovery step, and decision request for the internal owner who is authorized to run it.`]},
      {heading:'Make the evidence easy to review',body:[`Create a compact review packet containing the ticket, immutable revision, changed files, test commands, meaningful results, screenshots or logs where helpful, and remaining uncertainty. Explain the user or operational behavior before listing implementation details. Keep raw output in the approved system and redact tokens, personal information, and unrelated customer records.`,`Put the requested action near the top: approve the next slice, answer one named question, or reject the proposal with a reason. Include the consequence of waiting and the safest default. This structure helps a distributed reviewer respond quickly and prevents a delayed reply from being mistaken for approval.`]},
      {heading:'Use a sustainable daily handoff',body:[`Choose one short overlap window for decisions that truly need conversation and one written handoff cutoff. Before the cutoff, the developer posts current state, evidence links, blockers, and the next proposed action. During overlap, resolve the few questions that cannot be answered asynchronously. Afterward, each side can work in its normal local day without permanent night shifts.`,`Track completed outcomes, decision latency, review latency, reopened work, escaped defects, and blocked time. Do not rank people by messages, commits, keystrokes, or visible online hours. When delivery slows, examine ticket readiness, permissions, reviewer capacity, and dependency ownership before attributing the delay to an individual.`]},
      {heading:'Close the loop before expanding the lane',body:[`At completion, compare the evidence with the original result. Confirm that follow-ups have owners, temporary permissions have expiry or removal evidence, documentation reflects the operating path, and the internal owner has recorded approval or rejection. Preserve enough context for another team member to repeat the work from a clean starting point.`,`If your team needs this kind of bounded engineering support, review ${t.serviceLabel.toLowerCase()} or share the stack, first outcome, schedule, and review owner through the contact page. Developer Offshore can use that scope to discuss a Philippines-based role while your organization retains architecture, priority, security exceptions, sensitive credentials, and production decisions.`]},
    ],
    table:{title:'Implementation and handoff checklist',columns:['Checkpoint','Required evidence','Accountable owner'],rows:[['Scope',`Written outcome and ${t.inputs}`,owner],['Baseline','Fixed revision, environment, and reproducible starting result','Assigned reviewer'],['Boundary',t.edge,'System owner'],['Completion','Acceptance evidence, open risks, follow-ups, and access status','Internal delivery owner']]},
    relatedLinks:[{label:t.serviceLabel,href:t.service,note:'Review the closest bounded engineering service lane.'},{label:'Offshore development services',href:'/services',note:'Compare available role and delivery lanes.'},{label:'Discuss the first outcome',href:'/contact',note:'Share the stack, scope, schedule, and review owner.'}],
    faqs:[{question:'Can an offshore developer own this workflow?',answer:'They can own the scoped preparation, implementation, verification, and written handoff. Client-side owners should retain sensitive access, accepted risk, priority, and production approval.'},{question:'What should the first assignment contain?',answer:`Use one bounded result, a fixed revision, a named reviewer, approved access, and ${t.inputs}.`},{question:'How should the team handle a blocked decision?',answer:'Record the evidence, impact, safest default, decision owner, and response time. Stop at customer-data, security, spending, and production boundaries until an authorized owner responds.'}],sources:[t.source,...sharedSources]};
}

export const september19BlogBatch: readonly BlogPost[] = topics.map(makePost);
