import type { ResearchPost } from './fleet-data';

const studies = [
['offshore-developer-http-priority-scheduling-study-2026-09-10','Does HTTP priority change resource scheduling in this browser path?','one controlled page load in a declared browser and HTTP protocol environment','request discovery time, Priority headers, connection, transfer start, completion, initiator, and visual milestone','parser discovery order or server scheduling may explain the order without the priority hint',['RFC 9218: Extensible Prioritization Scheme for HTTP','https://www.rfc-editor.org/rfc/rfc9218.html'],['MDN fetchpriority reference','https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/fetchpriority']],
['offshore-developer-postgresql-plan-cache-study-2026-09-10','When does a PostgreSQL prepared statement choose a generic plan?','one prepared query tested against a fixed PostgreSQL version, schema, statistics snapshot, and parameter set','plan type, planning time, execution time, row estimates, parameters, custom-plan count, and generic-plan count','warming effects or changed statistics may explain the timing difference rather than plan selection',['PostgreSQL PREPARE','https://www.postgresql.org/docs/current/sql-prepare.html'],['PostgreSQL Plan Cache Mode','https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-PLAN-CACHE-MODE']],
['offshore-developer-kubernetes-topology-spread-study-2026-09-10','How does a topology spread constraint place pods when a zone is tight?','one synthetic Kubernetes workload scheduled onto a declared node and zone inventory','Pod conditions, scheduler events, node labels, taints, chosen nodes, skew, and pending duration','resource pressure, affinity, or taints may bind placement instead of topology spread',['Kubernetes Pod Topology Spread Constraints','https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/'],['Kubernetes Scheduler Configuration','https://kubernetes.io/docs/reference/scheduling/config/']],
['offshore-developer-browser-bfcache-eligibility-study-2026-09-10','Which page behavior prevents a back-forward cache restore?','one same-tab navigation sequence in a declared browser build using a fixed page revision','navigation type, persisted events, lifecycle events, blocker diagnostics, network activity, state restoration, and timing','an extension, memory pressure, or browser policy may change eligibility outside the page code',['HTML Standard: Page Lifecycle','https://html.spec.whatwg.org/multipage/browsing-the-web.html'],['web.dev Back/forward cache','https://web.dev/articles/bfcache']],
['offshore-developer-otel-tail-sampling-study-2026-09-10','Which traces survive an OpenTelemetry tail-sampling policy?','one synthetic trace corpus sent through a pinned collector configuration','trace attributes, span count, completion time, policy match, decision, late-span handling, and exported trace ID','upstream head sampling or transport loss may remove spans before the tail sampler sees them',['OpenTelemetry Collector tail sampling processor','https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor'],['OpenTelemetry Sampling','https://opentelemetry.io/docs/concepts/sampling/']],
] as const;

const related=[{title:'Research library',href:'/research'},{title:'Developer services',href:'/services'},{title:'Daily developer guides',href:'/blog'}] as const;
export const september10ResearchBatch: readonly ResearchPost[] = studies.map(([slug,title,scope,signals,rival,sourceOne,sourceTwo],index)=>({
slug,title,published:'2026-09-10',excerpt:`A reproducible protocol for ${scope}. It keeps observations separate from interpretation and states where the finding stops.`,
keyStats:['1 declared unit of analysis',`${7+(index%2)} recorded signal classes`,'2 mechanism-specific primary references'],
takeaways:[`Retain ${signals}.`,`Test whether ${rival}.`,'Apply results only to the pinned revision, configuration, workload, environment, and observation window.'],
sections:[
{heading:'Research question and scope',body:[`Research question: ${title} The unit of analysis is ${scope}. The study does not sample users, organizations, or unrelated configurations.`,`Before testing, pin code and dependency revisions, configuration, fixture identities, workload, network path, clock, and observation window.`]},
{heading:'Methodology',body:[`Run a baseline, target condition, repeated target, interrupted run, and recovery run with synthetic data. Record ${signals}. Preserve raw output before annotation.`,`Change one independent condition per comparison. Use the same warm-up, run count, timeout, and collection commands. Log failed and excluded runs with a reason.`]},
{heading:'Source basis and protocol choices',body:[`${sourceOne[0]} defines the mechanism under test. ${sourceTwo[0]} supplies a second standards or implementation reference for fixture and field selection.`,`The references shape the protocol but do not establish the local result. Measurements must support every claim about this system.`]},
{heading:'Inference boundaries',body:[`The primary inference compares recorded behavior inside the fixed test matrix. Timing alone does not prove causation. Try to disconfirm it by testing whether ${rival}.`,`Do not generalize to other versions, regions, workloads, or implementations. Keep unexpected results as observations until a controlled run separates the explanations.`]},
{heading:'Limitations',body:[`This protocol covers ${scope}. It cannot measure unobserved production traffic, every external failure, all implementations, or behavior after an upgrade. Clock precision, warm caches, background load, and instrumentation may affect measurements.`,`Report missing cases, uncertainty, the raw-data location, excluded runs, and the observation that would overturn the provisional conclusion.`]},
{heading:'Ownership and review',body:[`An offshore developer may prepare fixtures, run the approved protocol, add focused instrumentation, and draft a reversible correction. Internal security, data, platform, and release owners control sensitive access and production action.`,`A reviewer should reproduce one baseline and one boundary run from the recorded commands before accepting a conclusion.`]},
{heading:'References',body:[`Primary protocol references: ${sourceOne[0]} and ${sourceTwo[0]}. Their URLs appear below. Record the exact version or retrieval date used during execution.`]},
],
sources:[{name:sourceOne[0],url:sourceOne[1]},{name:sourceTwo[0],url:sourceTwo[1]},{name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],
faqs:[{question:'Does this result apply to the whole platform?',answer:'No. It applies only to the declared unit, pinned revisions, configuration, workload, environment, and observation window.'},{question:'What would change the conclusion?',answer:`A controlled run showing that ${rival}, or another recorded explanation, accounts for the observation would require a new conclusion.`}],related,
}));
