import type {ResearchPost} from './fleet-data';

const rows=[
  {id:'code-scanning-alert-triage-pilot',title:'Can an Offshore Developer Triage Code-Scanning Alerts Safely?',choice:'code-scanning alert triage',question:'Can a developer reproduce, classify, and propose a bounded fix for code-scanning alerts without dismissing risk or expanding access?',signals:'alert rule and configuration, affected branch, data-flow path, reproduction, proposed fix, targeted tests, reviewer decision, and dismissal authority',method:'Select a stratified sample of open alerts across severity, language, and application path. Freeze the scanner configuration and repository revision. Ask the developer to reproduce each alert, trace the relevant flow, propose a focused correction, and state uncertainty. A client security reviewer independently checks the same sample and alone decides dismissal or accepted risk.',inference:'Agreement on a small alert sample supports a narrow triage assignment under the tested scanner configuration. It does not prove the scanner is complete, that every alert is exploitable, or that a candidate may accept security risk.',failure:'bulk dismissal, severity-only ordering, unrecorded autofix, missing affected-branch context, tests that omit the reported flow, or developer authority to accept residual risk',source1:'GitHub Docs: Manage code scanning alerts',url1:'https://docs.github.com/en/code-security/how-tos/manage-security-alerts/manage-code-scanning-alerts',source2:'NIST Secure Software Development Framework',url2:'https://csrc.nist.gov/pubs/sp/800/218/final',service:'/services/devops-release-support'},
  {id:'postgres-query-plan-review-pilot',title:'What Can a PostgreSQL Query-Plan Review Prove Before Hiring?',choice:'database query-review scope',question:'Can a developer explain a representative PostgreSQL plan and improve the target workload without relying on unsafe production experimentation?',signals:'query fingerprint, schema revision, statistics state, plan nodes, estimated and actual rows, buffers, runtime distribution, locks, data scale, proposed index or rewrite, regression checks, and rollback',method:'Choose one recurring slow query and two control queries. Reproduce them on approved representative data, record the PostgreSQL version and statistics state, inspect EXPLAIN first, and use EXPLAIN ANALYZE only where execution is safe. Change one hypothesis at a time, repeat runs, and have the client database owner review write amplification, lock, storage, and rollback consequences.',inference:'A better bounded plan and repeatable latency distribution show competence on the sampled workload. They do not predict production behavior under different data, caches, concurrency, parameters, or statistics.',failure:'production EXPLAIN ANALYZE without approval, a single warm run, invented representative data, cost treated as milliseconds, missing write-side impact, or an index added without an owner and rollback',source1:'PostgreSQL Documentation: Using EXPLAIN',url1:'https://www.postgresql.org/docs/current/using-explain.html',source2:'PostgreSQL Documentation: Routine Vacuuming',url2:'https://www.postgresql.org/docs/current/routine-vacuuming.html',service:'/services/data-pipeline-development'},
  {id:'telemetry-context-boundary-pilot',title:'Testing Telemetry Context Boundaries With an Offshore Developer',choice:'telemetry context-propagation work',question:'Can a developer preserve useful trace correlation while preventing untrusted or sensitive context from crossing the wrong service boundary?',signals:'trust-boundary map, propagator configuration, incoming and outgoing headers, baggage allowlist, sanitization, trace linkage, sampled logs, third-party calls, failure behavior, and owner approval',method:'Map one request across first-party and third-party hops. Use synthetic identifiers and a pinned OpenTelemetry configuration. Test absent, valid, oversized, forged, and sensitive baggage; observe trace continuity and outbound headers. Require a reviewer to reproduce one internal correlation case and one blocked external-propagation case.',inference:'The exercise supports only the tested propagation routes, libraries, and configuration. Correlated spans do not prove baggage integrity, and sanitized sample values do not prove every instrumentation path is safe.',failure:'customer identifiers in fixtures, automatic propagation assumed safe, forged context trusted for authorization, third-party egress omitted, broken traces hidden, or an allowlist changed without client review',source1:'OpenTelemetry: Context propagation',url1:'https://opentelemetry.io/docs/concepts/context-propagation/',source2:'OpenTelemetry: Baggage',url2:'https://opentelemetry.io/docs/concepts/signals/baggage/',service:'/services/node-js-api-development'},
  {id:'mobile-release-signing-custody-pilot',title:'A Mobile Release-Signing Custody Test for Offshore Development',choice:'mobile release-signing responsibility',question:'Can a developer produce a release candidate and verifiable handoff while client owners retain custody of distribution identity and approval?',signals:'bundle identifier, build revision, version, signing mode, certificate or upload-key fingerprint, CI identity, artifact digest, test result, store role, approval event, expiry, revocation, and recovery rehearsal',method:'Use a non-production or internal-test lane with organization-owned accounts. Inventory each signing asset and role without exporting private keys. Build from a pinned revision, record the unsigned and signed artifact digests, submit through the least-privileged lane, then rehearse loss or revocation using the platform-supported recovery path. The client release owner performs final approval.',inference:'A successful internal submission shows that one configured lane can create an attributable artifact. It does not authorize production release, prove private-key safety elsewhere, or cover another platform, store, team, or certificate lifecycle.',failure:'shared personal accounts, exported distribution certificates, secrets pasted into tickets, unclear Apple team or Android key identity, developer-only release approval, missing artifact digest, or no recovery owner',source1:'Android Developers: Sign your app',url1:'https://developer.android.com/studio/publish/app-signing',source2:'Apple Developer: Certificates overview',url2:'https://developer.apple.com/help/account/certificates/certificates-overview',service:'/services/mobile-app-development'},
  {id:'ai-assisted-code-verification-pilot',title:'How Should a Team Verify AI-Assisted Offshore Development?',choice:'AI-assisted development controls',question:'Can a developer disclose and verify AI-assisted changes so a reviewer can judge the code rather than trusting the generation process?',signals:'approved tool and data boundary, task input class, generated-change extent, dependency and license changes, tests, security scans, reviewer findings, corrected defects, provenance notes, and final human decision',method:'Choose two representative synthetic tasks, one ordinary and one with an adversarial or ambiguous requirement. Declare allowed tools and prohibited data before work. Preserve the final diff and verification evidence rather than private prompts. Compare the same risk-based acceptance checks used for human-written code, add targeted abuse cases, and require an accountable reviewer to explain the final decision.',inference:'Passing the declared checks supports one change under one tool and policy. It does not establish model reliability, authorship, originality, confidentiality, future behavior, or suitability for unsupervised work.',failure:'secrets or customer code sent to an unapproved tool, AI output treated as a source, generated tests that only mirror generated behavior, undocumented dependencies, license assumptions, superficial review, or automated merge authority',source1:'NIST AI 600-1: Generative AI Profile',url1:'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf',source2:'NIST AI Risk Management Framework',url2:'https://www.nist.gov/itl/ai-risk-management-framework',service:'/services/next-js-application-development'},
] as const;

const protocol=`Pre-register the staffing decision, research question, unit, 14-day window, inclusion rules, stop conditions, and threshold before viewing results. Assign stable identifiers and preserve raw records separately from commentary. Record repository revision, environment identity, clock and offset, participant role, assistance, interruption, and missing evidence. A second reviewer must reproduce one ordinary case and one boundary case from the written procedure. Report negative, abandoned, and incomplete work beside successful work. Do not silently remove an inconvenient case or reconstruct a favorable timeline after the event. Compare like with like, vary one condition where practical, and retain counterexamples. This protocol studies whether a narrow responsibility is reviewable; it does not rank countries, promise individual performance, or replace client judgment.`;
const evidence=`Create an evidence dictionary before collection. For every field, name the owner, source system, format, sensitivity, retention period, and link to the decision it informs. Use synthetic or explicitly approved non-production data. Keep original artifacts and link transformed measures to source events. A screenshot or dashboard without inspectable inputs is supporting context, not sufficient evidence. Check completeness before calculation: count eligible cases, completed cases, stopped cases, exclusions, and missing records. Preserve denominators with every rate. Record assistance when it occurs so independent completion is not confused with coached completion. Hash exports when later edits are possible. Restrict the evidence package to what the reviewer needs and remove temporary credentials and fixtures under the declared retention rule.`;
const analysis=`Label every conclusion as observation, calculation, interpretation, or recommendation. An observation links to an artifact. A calculation states its denominator, exclusions, and treatment of incomplete work. An interpretation names at least one plausible rival explanation. A recommendation names an accountable owner, a reversible next step, and a review date. Do not turn a small operational sample into a population claim, a country comparison, or a promise about a person. If one case materially changes the result, show that sensitivity rather than presenting a stable-looking average. Standards and product documentation define methods and controls; they do not prove the local implementation follows them. The output is a bounded hiring or scope decision with uncertainty, not a certification.`;
const operations=`Before day one, name the client decision owner, technical reviewer, access owner, data owner, developer, and backup reviewer. Write the ticket set, acceptance criteria, repository revision, permitted tools, working hours, response window, escalation route, and conditions that pause work. Confirm each participant can identify the decision they own. During the study, use an event log containing an immutable identifier, timestamp with offset, actor, action, object, result, linked artifact, and next owner. Capture the first attempt before coaching changes the condition. At the end of each day, reconcile broken links and missing identifiers while participants can still recover them. Keep messages that change scope or acceptance with the ticket. Operational activity is not evidence of acceptable output unless it connects to the stated question.`;
const review=`At review, begin with evidence completeness rather than performance. Inspect the chronological path for an ordinary case, the slowest or most disputed case, one failure, and one boundary test. Compare narrative claims with artifacts. Separate delay caused by the developer from waiting on access, clarification, environment, or client review because each requires a different correction. Ask the same qualitative questions of each case: Was the desired outcome explicit? Could another person reproduce the evidence? Was a control bypassed? Was uncertainty disclosed before approval? Did the handoff name its next owner? Translate vague judgments such as communication or quality into observable behavior: an early blocking question, executable verification, risk raised before approval, or correction completed after review.`;
const roles=`The developer may prepare scoped work, fixtures, reproducible evidence, and a proposed correction. The client owns architecture, production and customer data, protected branches, credential and store administration, legal interpretation, risk acceptance, and final release. Automation can collect evidence but cannot accept risk. Pause on undeclared data, credentials, production impact, security or privacy interpretation, or out-of-scope change. Record who paused, why, what evidence is required, and who may resume. A reviewer should not approve their own exception. Commercial urgency must not silently change acceptance. When evidence is mixed, preserve the smaller safe scope while testing the disputed assumption.`;
const limitations=`A short pilot is sensitive to task selection, reviewer availability, codebase familiarity, data representativeness, environment stability, holidays, and chance. It cannot establish retention, incident behavior, performance under another manager, or results in another stack. A successful result may depend on coaching that will not exist later; an unsuccessful result may reflect a broken client workflow. Authoritative sources were used for method and control claims, but local findings require local evidence. The study does not estimate salary, employment classification, vendor quality, return on investment, or legal compliance. Repeat the boundary test after a material tool, dependency, policy, team, or platform change.`;
const decision=`The client technical owner records one outcome: continue unchanged, continue with a named correction, pause for specified evidence, or stop and revoke access. The record includes reason, contrary evidence, uncertainty, owner, due date, and review date. With mixed evidence, add only the next smallest responsibility and repeat the failure test. Close by exporting the evidence inventory, calculations, exclusions, decision, residual risks, and open actions. Revoke temporary access and verify revocation in the source system rather than relying on a request. Preserve the original boundary in a new record if scope expands so later success cannot rewrite an early failure and early success cannot become permanent authorization.`;

export const september19ResearchBatch:readonly ResearchPost[]=rows.map(r=>({
  slug:`offshore-developer-${r.id}-study-2026-09-19`,title:r.title,published:'2026-09-19',
  excerpt:`A decision-grade, reproducible study for evaluating ${r.choice} in a Philippines-based developer pilot.`,
  keyStats:['1 declared staffing decision','14-day bounded observation window','3 authoritative sources'],
  takeaways:[r.question,`Retain ${r.signals}.`,r.failure],
  sections:[
    {heading:'Decision and research question',body:[`Decision: ${r.choice}. Research question: ${r.question}`,`The unit is one developer, the named client reviewer, representative work, and the declared 14-day window. Define success before work begins. Findings apply only to this unit, revision, environment, access boundary, and observation period.`]},
    {heading:'Why this matters for offshore development',body:[`DeveloperOffshore.com serves buyers considering Philippines-based software developers. The practical decision is not whether location predicts skill. It is whether a specific responsibility can be bounded, observed, reviewed, and safely expanded inside the client’s operating system. This study supports ${r.service} by testing a real decision path before broader access or autonomy is granted.`,`Distributed delivery increases the value of durable evidence because the reviewer may be offline when work occurs. Written acceptance, reproducible checks, explicit uncertainty, and a named next owner let the client evaluate output without continuous supervision. They also reveal client-side bottlenecks that hiring alone cannot fix.`]},
    {heading:'Methodology',body:[r.method,protocol]},
    {heading:'Evidence plan',body:[`Collect ${r.signals}.`,evidence]},
    {heading:'Execution procedure',body:[operations,`Use a representative task rather than a toy example, but remove customer and production data. Keep the normal tools and review path stable. When help is given, record its timing and content. Test the expected path, an invalid or denied path, an interruption, and recovery. Require the reviewer to follow the evidence links from result back to source instead of relying on the developer's summary.`]},
    {heading:'Analysis and inference boundaries',body:[r.inference,analysis]},
    {heading:'Roles, controls, and escalation',body:[roles,`This topic-specific study must never enlarge permissions merely to make the pilot easier. The developer can recommend a reversible change but may not bypass a control, conceal a failed attempt, approve an exception, or redefine acceptance after seeing the result.`]},
    {heading:'Failure and counterevidence tests',body:[`Invalidate the result when there is ${r.failure}.`, `Actively seek a case that overturns the preferred conclusion. Repeat one case after changing only the suspected cause. Inspect missing evidence and exclusions. Ask a reviewer who did not author the procedure to reproduce the result. A defensible stop is more useful than a polished but irreproducible success.`]},
    {heading:'Review worksheet',body:[review,`For each reviewed case, record expected outcome, actual outcome, evidence link, control result, uncertainty, reviewer decision, correction, and next owner. Then compare cases using counts and distributions appropriate to the question. Do not collapse a severe boundary failure into an average. A single unauthorized action can outweigh several fast completions because the staffing decision concerns both capability and safe operation.`]},
    {heading:'Limitations',body:[limitations,`No result supports claims about DeveloperOffshore.com customers, pricing, locations, or outcomes, or about every Philippines-based developer or client. Public sources describe controls and product behavior, not the performance of the participant.`]},
    {heading:'Decision rule and closeout',body:[decision,`Expand staffing scope only when the evidence remains reviewable, the client owner can reproduce the critical boundary, and unresolved risk has an explicit owner. If the workflow itself prevents a fair test, correct the workflow and run a new study rather than blaming or approving the developer without evidence.`]},
    {heading:'Sources and checked dates',body:[`Sources were checked 2026-09-19. They inform the method but do not establish local findings.`,`${r.source1}: ${r.url1}`,`${r.source2}: ${r.url2}`,`NIST Secure Software Development Framework: https://csrc.nist.gov/pubs/sp/800/218/final`]},
  ],
  sources:[{name:`${r.source1} (checked 2026-09-19)`,url:r.url1},{name:`${r.source2} (checked 2026-09-19)`,url:r.url2},{name:'NIST Secure Software Development Framework (checked 2026-09-19)',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],
  faqs:[{question:'Does this study prove the developer will succeed?',answer:'No. It supplies bounded evidence for one workflow, responsibility, and review decision.'},{question:'Who accepts the remaining risk?',answer:'The named client owner; the developer and automation may provide evidence but do not accept risk.'}],
  related:[{title:'Relevant developer service',href:r.service},{title:'Research library',href:'/research'},{title:'Discuss a role',href:'/contact'}],
}));
