import type { BlogPost } from './data';

type Topic = { slug:string; title:string; family:string; reader:string; decision:string; deliverable:string; scenario:string; measures:string; service:string; serviceLabel:string; source:{name:string;url:string} };

const topics: readonly Topic[] = [
  {slug:'offshore-developer-cost-estimate-template',title:'Offshore Developer Cost Estimate: A Buyer’s Planning Template',family:'commercial planning',reader:'software leaders building a defensible budget before speaking with a provider',decision:'compare the full cost of a Philippines-based developer with an internal hire or a project vendor',deliverable:'a twelve-month estimate that separates recurring labor, onboarding, management, tooling, recruiting, and contingency',scenario:'a low monthly rate appears attractive but excludes the senior review time and paid tools required to ship safely',measures:'planned versus actual monthly cost, internal review hours, productive capacity, and unplanned spend',service:'/services',serviceLabel:'Offshore development services',source:{name:'U.S. SBA: calculate startup costs',url:'https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs'}},
  {slug:'offshore-developer-paid-trial-project',title:'How to Design a Paid Trial Project for an Offshore Developer',family:'hiring evaluation',reader:'engineering managers who want job-relevant evidence before making a longer commitment',decision:'test collaboration and technical judgment without asking candidates for unpaid production work',deliverable:'a time-boxed, paid exercise with the same brief, access, rubric, and review path for every candidate',scenario:'the exercise quietly becomes free feature delivery or exposes a candidate to customer data and production credentials',measures:'requirement questions, solution quality, verification evidence, written handoff, and reviewer confidence',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'U.S. EEOC: employment tests and selection procedures',url:'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures'}},
  {slug:'staff-augmentation-vs-project-outsourcing-software',title:'Staff Augmentation vs Project Outsourcing for Software Delivery',family:'engagement model',reader:'buyers deciding whether they need individual capacity or an accountable project outcome',decision:'choose an engagement model based on ownership, specification stability, review capacity, and change risk',deliverable:'a comparison that assigns scope, architecture, staffing, acceptance, delivery risk, and change control',scenario:'a buyer purchases staff augmentation but expects the provider to absorb fixed-price project risk without authority over scope',measures:'decision latency, accepted throughput, change requests, internal management load, and outcome predictability',service:'/services',serviceLabel:'Offshore development services',source:{name:'UK Government: outsourcing playbook',url:'https://www.gov.uk/government/publications/the-outsourcing-playbook'}},
  {slug:'offshore-software-vendor-due-diligence-checklist',title:'Offshore Software Vendor Due Diligence Checklist',family:'vendor selection',reader:'technical and procurement leads validating a delivery partner before granting system access',decision:'separate verifiable operating controls from sales claims',deliverable:'an evidence request covering ownership, staffing, security, delivery, business continuity, references, and exit readiness',scenario:'a polished proposal names standards and tools but supplies no evidence showing how the proposed team actually works',measures:'verified controls, unresolved exceptions, named owners, evidence age, and remediation dates',service:'/services',serviceLabel:'Offshore development services',source:{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}},
  {slug:'technical-interview-scorecard-offshore-developer',title:'Technical Interview Scorecard for an Offshore Developer',family:'hiring evaluation',reader:'interview panels that need consistent evidence across remote candidates',decision:'evaluate job-relevant reasoning, communication, implementation, and verification against a shared standard',deliverable:'a structured scorecard with anchored ratings, independent notes, and a recorded hiring decision',scenario:'interviewers reward familiarity with trivia while overlooking whether the candidate can clarify and verify real work',measures:'evidence coverage, rating consistency, work-sample performance, decision confidence, and later calibration',service:'/services/next-js-application-development',serviceLabel:'Next.js application development',source:{name:'U.S. Office of Personnel Management: structured interviews',url:'https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/'}},
  {slug:'offshore-developer-rate-card-comparison',title:'How to Compare Offshore Developer Rate Cards',family:'commercial planning',reader:'buyers comparing proposals that use different currencies, inclusions, seniority labels, and billing rules',decision:'normalize proposals to the same unit and expose assumptions that change effective cost',deliverable:'a comparison sheet for productive hours, fees, taxes, leave, equipment, overtime, currency, notice, and replacement terms',scenario:'the lowest headline hourly rate becomes the highest effective rate after minimums, fees, and uncovered leave are included',measures:'effective monthly cost, productive-hour assumption, variance exposure, included services, and exit cost',service:'/services',serviceLabel:'Offshore development services',source:{name:'U.S. GSA: independent government cost estimate guide',url:'https://www.gsa.gov/system/files/Independent%20Government%20Cost%20Estimate%20Guide%20and%20Template.pdf'}},
  {slug:'offshore-development-ip-data-contract-checklist',title:'IP and Data Contract Checklist for Offshore Development',family:'contract readiness',reader:'buyers preparing a commercial and security review with qualified legal counsel',decision:'identify the software, data, access, and exit questions that must be assigned before work begins',deliverable:'a counsel-ready issue list covering ownership, pre-existing materials, open source, confidentiality, processing, incidents, subcontractors, return, and deletion',scenario:'a contract promises ownership broadly but does not identify background tools, repository control, or data return evidence',measures:'open issues, accountable reviewers, approved exceptions, evidence obligations, and exit-test results',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'UK ICO: contracts and liabilities between controllers and processors',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/contracts-and-liabilities-between-controllers-and-processors/'}},
  {slug:'philippines-development-team-time-zone-coverage-plan',title:'Philippines Development Team Time-Zone Coverage Plan',family:'distributed delivery',reader:'North American and European managers designing coverage without normalizing overnight work',decision:'assign synchronous decisions, asynchronous production, on-call boundaries, and handoff ownership across local workdays',deliverable:'a weekly coverage map showing local time, daylight-saving changes, response classes, and backup owners',scenario:'a calendar says there is four-hour overlap, but recurring meetings and daylight-saving shifts leave no review window',measures:'decision response time, handoff completion, after-hours work, blocked hours, and missed escalation targets',service:'/services/devops-release-support',serviceLabel:'DevOps release support',source:{name:'GitLab handbook: how to communicate effectively in a remote team',url:'https://handbook.gitlab.com/handbook/company/culture/all-remote/how-to-communicate-effectively-in-a-remote-team/'}},
  {slug:'offshore-development-team-composition',title:'How to Choose an Offshore Development Team Composition',family:'team design',reader:'product and engineering leaders deciding which roles to add first',decision:'match developers, QA, delivery, design, and platform support to the actual constraint in the delivery system',deliverable:'a role map tied to backlog shape, architecture ownership, review capacity, release risk, and customer feedback',scenario:'several developers are added while the only reviewer, tester, or product decision maker remains overloaded',measures:'queue time by stage, review demand, escaped defects, deployment frequency, and accepted outcomes',service:'/services/qa-automation-engineering',serviceLabel:'QA automation engineering',source:{name:'Google Cloud: DORA capabilities',url:'https://cloud.google.com/architecture/devops/devops-capabilities'}},
  {slug:'offshore-developer-replacement-continuity-plan',title:'Replacement and Continuity Plan for an Offshore Developer',family:'continuity planning',reader:'buyers who need delivery to survive absence, turnover, or a change of provider',decision:'define what must remain transferable before a critical contributor becomes unavailable',deliverable:'a tested continuity packet with access ownership, work state, runbooks, backup coverage, and a recovery rehearsal',scenario:'documentation exists, but only the departing developer can access the account or explain the latest production change',measures:'recovery time, runbook replay success, access transfer, unowned work, and backup readiness',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'NIST SP 800-34: contingency planning guide',url:'https://csrc.nist.gov/pubs/sp/800/34/r1/upd1/final'}},
  {slug:'offshore-development-invoice-review-checklist',title:'Offshore Development Invoice Review Checklist',family:'commercial operations',reader:'engineering and finance owners approving recurring offshore delivery invoices',decision:'connect billed units and approved exceptions to accepted work without measuring people by visible activity',deliverable:'a monthly review packet for contracted capacity, approved changes, leave, overtime, expenses, currency, tax, and credits',scenario:'an invoice matches the rate card but includes unapproved overtime or capacity that the delivery owner could not use',measures:'contract-to-invoice variance, disputed amount, approval cycle time, unused capacity, and recurring exceptions',service:'/services/admin-support',serviceLabel:'Engineering admin support',source:{name:'U.S. Department of Defense: contract closeout guidebook',url:'https://www.acquisition.gov/sites/default/files/page_file_uploads/Contract%20Closeout%20Guidebook.pdf'}},
  {slug:'offshore-developer-90-day-scorecard',title:'90-Day Scorecard for an Offshore Developer Engagement',family:'engagement governance',reader:'buyers deciding whether to expand, adjust, or stop an initial offshore development lane',decision:'review delivery health using outcomes and system constraints rather than activity surveillance',deliverable:'a baseline, three review points, evidence definitions, decision thresholds, and named improvement owners',scenario:'a team reports many tickets and commits while review queues grow and the intended customer outcome remains unreleased',measures:'accepted outcomes, lead time, review latency, escaped defects, blocked time, forecast accuracy, and knowledge spread',service:'/services/operations-support',serviceLabel:'Development operations support',source:{name:'DORA: a history of DORA metrics',url:'https://dora.dev/guides/dora-metrics/'}},
];

const sharedSources = [
  {name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/Projects/ssdf'},
  {name:'GitHub Docs: About pull request reviews',url:'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'},
] as const;

function makePost(t:Topic, index:number):BlogPost {
  const buyerOwner = index % 2 === 0 ? 'engineering manager' : 'delivery owner';
  return {slug:t.slug,title:t.title,excerpt:`A practical buyer guide for ${t.reader}. Build ${t.deliverable} before committing budget, access, or delivery expectations.`,minutes:13+(index%3),datePublished:'2026-09-22',revision:`daily-blog-2026-09-22-${t.slug}`,
    keyTakeaways:[`Frame the decision explicitly: ${t.decision}.`,`Require a concrete output: ${t.deliverable}.`,'Keep priority, sensitive access, accepted risk, commercial approval, and production authority with named buyer-side owners.'],
    sections:[
      {heading:'Start with the buying decision',body:[`This guide is for ${t.reader}. The immediate decision is whether and how to ${t.decision}. Write that decision at the top of the working document, name the deadline, and identify who can approve it. A provider can supply facts and options, but the buyer should retain the final judgment about budget, architecture, security exceptions, and production risk.`,`Describe the business outcome and the delivery constraint separately. A need for more accepted product changes is not automatically a need for more programmers. The limiting factor may be unclear priorities, slow review, fragile releases, missing test coverage, or unavailable product decisions. Record the current baseline before comparing options so a confident proposal does not replace evidence.`]},
      {heading:'Build the minimum evidence packet',body:[`The useful deliverable is ${t.deliverable}. Give every provider or candidate the same factual starting point: stack, application boundaries, expected work, working hours, required experience, review path, environments, data sensitivity, and proposed start window. Mark estimates as estimates, and distinguish confirmed requirements from preferences that can change during discovery.`,`Ask for evidence that can be checked: a redacted example, a walkthrough of an operating process, named responsibility, or a reference who observed comparable work. Do not treat a certification logo, tool list, or generic case study as proof that the proposed team follows the claimed practice. Note the evidence date and whether it describes the actual assigned people or only the wider company.`]},
      {heading:'Normalize the options before ranking them',body:[`Put alternatives into one comparison table. Use the same time period, currency date, capacity assumption, service boundary, and definition of completion. State who supplies management, product decisions, code review, quality checks, equipment, licenses, security administration, and release approval. An apparently expensive option may include a control or role that another proposal leaves with the buyer.`,`Create three views: expected case, plausible high case, and exit case. The expected case supports planning. The high case exposes overtime, exchange movement, additional review, rework, or scope change. The exit case shows notice, knowledge transfer, access removal, data return, and unfinished work. This is scenario planning, not a prediction; the value is making assumptions available for challenge.`]},
      {heading:'Assign ownership at each boundary',body:[`Use a simple responsible-and-approving map for scope, architecture, access, implementation, verification, acceptance, deployment, incidents, invoicing, and offboarding. The ${buyerOwner} should know which decisions cannot be delegated. Provider ownership must be paired with the authority, inputs, and response path needed to perform the work; otherwise the contract assigns responsibility without a workable operating model.`,`Write safe defaults for silence. Routine implementation can continue inside an accepted design and approved environment. Work should stop when the next step exposes customer data, expands privilege, creates unapproved spend, changes a contractual commitment, or alters production without the required approval. Name a primary and backup decision maker so a time-zone gap does not become implied consent.`]},
      {heading:'Test the failure case before commitment',body:[`Model this uncomfortable case: ${t.scenario}. Ask what signal reveals the problem, who notices it, which work stops, how evidence is preserved, and who chooses recovery. A useful answer names a control and produces an artifact. “We communicate closely” is not a recovery plan unless the channel, response expectation, backup, and authority are defined.`,`Run a tabletop using a realistic but sanitized example. Follow the proposed workflow from request through approval, access, delivery, review, acceptance, and handoff. Introduce one missing owner or failed check and observe whether the process produces a safe pause. Record gaps as pre-start actions, accepted risks with expiry dates, or reasons not to proceed.`]},
      {heading:'Measure the delivery system, not online activity',body:[`For this decision, track ${t.measures}. Define the start and end event for every measure, where the record comes from, and what action a threshold triggers. Compare trends with the baseline and with changes in scope or team composition. Small samples need context; one difficult release should prompt investigation rather than a claim about long-term performance.`,`Avoid screenshots, keystrokes, message counts, and raw commit totals as performance proxies. Those signals reward visibility instead of accepted value and can punish careful discovery, review, or incident prevention. Use work-system evidence to find queues and missing inputs, then discuss individual coaching privately with relevant examples and an opportunity to respond.`]},
      {heading:'Set a review and exit path on day one',body:[`Schedule an early operating review and a later commercial review. The operating review checks access, ticket readiness, review capacity, evidence quality, and handoffs. The commercial review compares actual use and outcomes with the assumptions in the decision record. Give improvements an owner and a date, then state what evidence will show that the correction worked.`,`Prepare continuity before it is urgent. Buyer-controlled repositories and identities, current work state, documented environment setup, named backups, and periodic access reviews reduce dependence on one person or vendor. The exit path should cover notice, accepted work, open defects, credentials, devices, confidential information, invoices, and confirmation that copies were returned or deleted where required.`]},
      {heading:'Turn the comparison into a bounded first step',body:[`Choose the smallest paid step that can retire the largest uncertainty. It may be a discovery session, a work sample, a backlog and architecture review, or one production-shaped change in a controlled environment. Define the output, time box, reviewers, access, acceptance evidence, and stopping point. Do not label an open-ended engagement a pilot merely because it starts small.`,`At the decision meeting, record proceed, revise, or stop; the supporting evidence; unresolved risks; and the next owner. If your team wants help shaping the lane, review ${t.serviceLabel.toLowerCase()} or use the contact page to share the stack, intended outcome, working hours, review owner, and target start. Developer Offshore can discuss a Philippines-based delivery role while your organization retains its core product, security, commercial, and production decisions.`]},
    ],
    table:{title:'Buyer decision record',columns:['Decision point','Evidence to request','Owner'],rows:[['Outcome',`Decision statement and ${t.deliverable}`,buyerOwner],['Operating model','Scope, access, review, acceptance, and escalation map','Delivery owner'],['Failure test',t.scenario,'System owner'],['Review',`Baseline and ${t.measures}`,'Buyer sponsor']]},
    relatedLinks:[{label:t.serviceLabel,href:t.service,note:'Review the closest service lane for this decision.'},{label:'Compare offshore development services',href:'/services',note:'See the available engineering and delivery lanes.'},{label:'Discuss a bounded first outcome',href:'/contact',note:'Share the stack, scope, schedule, and review owner.'}],
    faqs:[{question:'Should the provider make this decision for the buyer?',answer:'The provider can supply evidence, options, and implementation detail. The buyer should retain final authority for business priority, budget, sensitive access, accepted risk, and production changes.'},{question:'What should be documented before work starts?',answer:`Record the decision, owner, assumptions, boundaries, review date, and ${t.deliverable}.`},{question:'How should an unresolved risk be handled?',answer:'Name the risk, evidence, potential impact, owner, due date, and safe default. Do not treat silence or a sales assurance as acceptance.'}],sources:[t.source,...sharedSources]};
}

export const september22BlogBatch: readonly BlogPost[] = topics.map(makePost);
