import type { BlogPost } from './data';

export type DailyBlogTopic = { slug:string; title:string; family:string; reader:string; decision:string; deliverable:string; scenario:string; measures:string; service:string; serviceLabel:string; source:{name:string;url:string} };

const topics: readonly DailyBlogTopic[] = [
  {slug:'nextjs-server-client-boundary-review',title:'Next.js Server and Client Component Boundary Review',family:'Next.js delivery',reader:'application leads assigning App Router work to a Philippines-based developer',decision:'place data access, interactivity, secrets, and browser-only behavior on the correct side of the rendering boundary',deliverable:'a route-level boundary map with bundle, cache, loading, error, and authorization evidence',scenario:'a small interactive change moves a large subtree to the client, exposes server assumptions, and increases shipped JavaScript',measures:'client bundle change, server render time, cache behavior, error-state coverage, and reviewer findings',service:'/services/next-js-application-development',serviceLabel:'Next.js application development',source:{name:'Next.js Docs: Server and Client Components',url:'https://nextjs.org/docs/app/getting-started/server-and-client-components'}},
  {slug:'react-component-accessibility-handoff',title:'React Component Accessibility Handoff for an Offshore Developer',family:'React delivery',reader:'frontend leads delegating reusable component work across time zones',decision:'define accessibility behavior as part of the component contract rather than a final visual check',deliverable:'a component handoff covering semantics, keyboard flow, focus, names, errors, states, and assistive-technology evidence',scenario:'a component matches the design at one viewport but its keyboard order, focus state, or accessible name fails in real use',measures:'keyboard-path completion, automated findings, manual review findings, state coverage, and remediation time',service:'/services/react-frontend-development',serviceLabel:'React frontend development',source:{name:'W3C: Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'}},
  {slug:'node-api-error-contract',title:'Node.js API Error Contract for Distributed Development',family:'API delivery',reader:'backend leads handing endpoint work to an offshore Node.js developer',decision:'standardize how validation, authorization, dependency, conflict, and unexpected failures appear to clients and operators',deliverable:'an error catalog with status, stable code, safe message, retry rule, log fields, and contract tests',scenario:'two endpoints represent the same failure differently, causing unsafe retries and leaking internal detail to clients',measures:'contract-test coverage, unknown error codes, retryable-failure rate, support ambiguity, and time to diagnosis',service:'/services/node-js-api-development',serviceLabel:'Node.js API development',source:{name:'IETF RFC 9457: Problem Details for HTTP APIs',url:'https://www.rfc-editor.org/rfc/rfc9457.html'}},
  {slug:'shopify-theme-performance-budget',title:'Shopify Theme Performance Budget for Offshore Development',family:'commerce delivery',reader:'commerce teams assigning theme changes without sacrificing storefront responsiveness',decision:'set measurable page and asset limits before a developer changes templates, scripts, apps, or media',deliverable:'a page-type performance budget with test conditions, baseline, thresholds, evidence, and an exception path',scenario:'a visually small merchandising feature adds third-party code to every page and slows the main purchase path',measures:'Core Web Vitals field data, lab measurements, script weight, image weight, and budget exceptions',service:'/services/shopify-theme-development',serviceLabel:'Shopify theme development',source:{name:'Shopify: Theme performance best practices',url:'https://shopify.dev/docs/storefronts/themes/best-practices/performance'}},
  {slug:'wordpress-plugin-update-staging-plan',title:'WordPress Plugin Update and Staging Plan for an Offshore Developer',family:'WordPress maintenance',reader:'site owners delegating plugin maintenance while retaining production approval',decision:'separate inventory, compatibility review, backup, staging verification, release, and rollback responsibilities',deliverable:'a repeatable update record with versions, dependency notes, backup evidence, test scope, approval, and rollback trigger',scenario:'an automatic update succeeds technically but breaks a checkout, form, editor workflow, or cached public page',measures:'updates reviewed, staging failures, escaped regressions, rollback time, and overdue security updates',service:'/services/wordpress-engineering',serviceLabel:'WordPress engineering',source:{name:'WordPress Developer Resources: Plugins',url:'https://developer.wordpress.org/plugins/'}},
  {slug:'qa-flaky-test-triage-playbook',title:'Flaky Test Triage Playbook for an Offshore QA Engineer',family:'QA automation',reader:'engineering teams losing confidence in automated test results',decision:'classify, contain, reproduce, repair, and restore unreliable checks without normalizing ignored failures',deliverable:'a flake record containing frequency, environment, ownership, quarantine rule, root-cause evidence, and exit criteria',scenario:'a failing check is rerun until green, hiding both product regressions and defects in the test itself',measures:'flake rate, quarantined-test age, rerun count, false-failure time, and restored coverage',service:'/services/qa-automation-engineering',serviceLabel:'QA automation engineering',source:{name:'Playwright Docs: Test retries',url:'https://playwright.dev/docs/test-retries'}},
  {slug:'deployment-rollback-ownership-matrix',title:'Deployment and Rollback Ownership Matrix for Offshore DevOps Support',family:'release operations',reader:'platform leads delegating release preparation across organizational boundaries',decision:'assign who prepares, approves, executes, observes, pauses, and reverses each production change',deliverable:'a release ownership matrix tied to health signals, stop conditions, communication, and tested recovery steps',scenario:'a release degrades one customer journey while every participant assumes someone else can authorize rollback',measures:'decision latency, failed-deployment recovery time, rollback success, missing evidence, and after-hours escalations',service:'/services/devops-release-support',serviceLabel:'DevOps release support',source:{name:'Google Cloud Architecture Center: Deployment strategies',url:'https://cloud.google.com/architecture/application-deployment-and-testing-strategies'}},
  {slug:'data-pipeline-schema-change-plan',title:'Data Pipeline Schema Change Plan for an Offshore Developer',family:'data engineering',reader:'data owners coordinating producer and consumer changes with a distributed developer',decision:'change a field, type, constraint, or event without silently corrupting downstream reports and jobs',deliverable:'a compatibility plan covering contracts, sample data, backfill, dual reads or writes, validation, cutover, and retirement',scenario:'a producer deploys a valid new value that an unlisted consumer drops or interprets incorrectly',measures:'contract violations, rejected records, reconciliation difference, backfill progress, and legacy-field usage',service:'/services/data-pipeline-development',serviceLabel:'Data pipeline development',source:{name:'Google Cloud Pub/Sub: Schema evolution',url:'https://cloud.google.com/pubsub/docs/schemas-valid'}},
  {slug:'mobile-app-release-signing-handoff',title:'Mobile App Release Signing Handoff for Offshore Development',family:'mobile delivery',reader:'mobile leads separating build work from ownership of signing identities and store release authority',decision:'let a distributed developer prepare verifiable releases without sharing long-lived signing secrets casually',deliverable:'a signing and release map for identities, protected storage, build provenance, approvals, recovery, and rotation',scenario:'one contributor holds the only usable signing credential or uploads an unreviewed binary from an untrusted workstation',measures:'reproducible-build checks, signing exceptions, credential age, rejected submissions, and recovery-test results',service:'/services/mobile-app-development',serviceLabel:'Mobile app development',source:{name:'Android Developers: Sign your app',url:'https://developer.android.com/studio/publish/app-signing'}},
  {slug:'legacy-app-characterization-test-plan',title:'Characterization Test Plan for Offshore Legacy Application Work',family:'legacy modernization',reader:'maintainers assigning changes in poorly documented code',decision:'capture current observable behavior before refactoring a risky module',deliverable:'a behavior inventory and focused test seam that records representative inputs, outputs, side effects, and known defects',scenario:'a cleanup removes behavior that looked accidental but is required by a customer, integration, or monthly operation',measures:'behaviors captured, uncovered branches, regression findings, change failure rate, and reviewer uncertainty',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'Martin Fowler: Characterization Test',url:'https://martinfowler.com/bliki/CharacterizationTest.html'}},
  {slug:'ai-automation-human-review-plan',title:'Human Review Plan for Offshore AI Automation Development',family:'AI automation',reader:'product owners adding model-assisted classification, drafting, or workflow decisions',decision:'decide which outputs may proceed automatically and which require evidence-based human review',deliverable:'a review matrix for impact, confidence, sensitive data, override, logging, fallback, and appeal',scenario:'a plausible model output triggers a customer-facing or irreversible action without a qualified reviewer seeing the source evidence',measures:'override rate, sampled error rate, harmful-action prevention, review latency, and fallback usage',service:'/services',serviceLabel:'Offshore development services',source:{name:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'}},
  {slug:'database-migration-rehearsal-plan',title:'Database Migration Rehearsal Plan for an Offshore Developer',family:'database delivery',reader:'engineering leads assigning production-shaped schema changes to a distributed contributor',decision:'prove that a migration, application rollout, data verification, and recovery sequence fits the operating window',deliverable:'a rehearsal record with representative volume, timings, locks, compatibility checks, validation queries, and rollback limits',scenario:'a migration passes on a small development database but blocks writes or exceeds the available production window',measures:'rehearsal duration, lock time, rows validated, rollback duration, and unexplained reconciliation difference',service:'/services/legacy-application-maintenance',serviceLabel:'Legacy application maintenance',source:{name:'PostgreSQL Documentation: ALTER TABLE',url:'https://www.postgresql.org/docs/current/sql-altertable.html'}},
];

const sharedSources = [
  {name:'NIST Secure Software Development Framework',url:'https://csrc.nist.gov/Projects/ssdf'},
  {name:'GitHub Docs: About pull request reviews',url:'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews'},
] as const;

export function makeDailyBlogPost(t:DailyBlogTopic, index:number, publicationDate = '2026-09-23'):BlogPost {
  const buyerOwner = index % 2 === 0 ? 'engineering manager' : 'delivery owner';
  return {slug:t.slug,title:t.title,excerpt:`A practical buyer guide for ${t.reader}. Build ${t.deliverable} before committing budget, access, or delivery expectations.`,minutes:13+(index%3),datePublished:publicationDate,revision:`daily-blog-${publicationDate}-${t.slug}`,
    keyTakeaways:[`Frame the decision explicitly: ${t.decision}.`,`Require a concrete output: ${t.deliverable}.`,'Keep priority, sensitive access, accepted risk, commercial approval, and production authority with named buyer-side owners.'],
    sections:[
      {heading:'Start with the buying decision',body:[`This guide is for ${t.reader}. The immediate decision is whether and how to ${t.decision}. Write that decision at the top of the working document, name the deadline, and identify who can approve it. A provider can supply facts and options, but the buyer should retain the final judgment about budget, architecture, security exceptions, and production risk.`,`Describe the business outcome and the delivery constraint separately. A need for more accepted product changes is not automatically a need for more programmers. The limiting factor may be unclear priorities, slow review, fragile releases, missing test coverage, or unavailable product decisions. Record the current baseline before comparing options so a confident proposal does not replace evidence.`]},
      {heading:'Build the minimum evidence packet',body:[`The useful deliverable is ${t.deliverable}. Give every provider or candidate the same factual starting point: stack, application boundaries, expected work, working hours, required experience, review path, environments, data sensitivity, and proposed start window. Mark estimates as estimates, and distinguish confirmed requirements from preferences that can change during discovery.`,`Ask for evidence that can be checked: a redacted example, a walkthrough of an operating process, named responsibility, or a reference who observed comparable work. Do not treat a certification logo, tool list, or generic case study as proof that the proposed team follows the claimed practice. Note the evidence date and whether it describes the actual assigned people or only the wider company.`]},
      {heading:'Normalize the options before ranking them',body:[`Put alternatives into one comparison table. Use the same time period, currency date, capacity assumption, service boundary, and definition of completion. State who supplies management, product decisions, code review, quality checks, equipment, licenses, security administration, and release approval. An apparently expensive option may include a control or role that another proposal leaves with the buyer.`,`Create three views: expected case, plausible high case, and exit case. The expected case supports planning. The high case exposes overtime, exchange movement, additional review, rework, or scope change. The exit case shows notice, knowledge transfer, access removal, data return, and unfinished work. This is scenario planning, not a prediction; the value is making assumptions available for challenge.`]},
      {heading:'Assign ownership at each boundary',body:[`Use a simple responsible-and-approving map for scope, architecture, access, implementation, verification, acceptance, deployment, incidents, invoicing, and offboarding. The ${buyerOwner} should know which decisions cannot be delegated. Provider ownership must be paired with the authority, inputs, and response path needed to perform the work; otherwise the contract assigns responsibility without a workable operating model.`,`Write safe defaults for silence. Routine implementation can continue inside an accepted design and approved environment. Work should stop when the next step exposes customer data, expands privilege, creates unapproved spend, changes a contractual commitment, or alters production without the required approval. Name a primary and backup decision maker so a time-zone gap does not become implied consent.`]},
      {heading:'Test the failure case before commitment',body:[`Model this uncomfortable case: ${t.scenario}. Ask what signal reveals the problem, who notices it, which work stops, how evidence is preserved, and who chooses recovery. A useful answer names a control and produces an artifact. “We communicate closely” is not a recovery plan unless the channel, response expectation, backup, and authority are defined.`,`Run a tabletop using a realistic but sanitized example. Follow the proposed workflow from request through approval, access, delivery, review, acceptance, and handoff. Introduce one missing owner or failed check and observe whether the process produces a safe pause. Record gaps as pre-start actions, accepted risks with expiry dates, or reasons not to proceed.`]},
      {heading:'Measure the delivery system, not online activity',body:[`For this decision, track ${t.measures}. Define the start and end event for every measure, where the record comes from, and what action a threshold triggers. Compare trends with the baseline and with changes in scope or team composition. Small samples need context; one difficult release should prompt investigation rather than a claim about long-term performance.`,`Avoid screenshots, keystrokes, message counts, and raw commit totals as performance proxies. Those signals reward visibility instead of accepted value and can punish careful discovery, review, or incident prevention. Use work-system evidence to find queues and missing inputs, then discuss individual coaching privately with relevant examples and an opportunity to respond.`]},
      {heading:'Set a review and exit path on day one',body:[`Schedule an early operating review and a later commercial review. The operating review checks access, ticket readiness, review capacity, evidence quality, and handoffs. The commercial review compares actual use and outcomes with the assumptions in the decision record. Give improvements an owner and a date, then state what evidence will show that the correction worked.`,`Prepare continuity before it is urgent. Buyer-controlled repositories and identities, current work state, documented environment setup, named backups, and periodic access reviews reduce dependence on one person or vendor. The exit path should cover notice, accepted work, open defects, credentials, devices, confidential information, invoices, and confirmation that copies were returned or deleted where required.`]},
      {heading:'Turn the comparison into a bounded first step',body:[`Choose the smallest paid step that can retire the largest uncertainty. It may be a discovery session, a work sample, a backlog and architecture review, or one production-shaped change in a controlled environment. Define the output, time box, reviewers, access, acceptance evidence, and stopping point. Do not label an open-ended engagement a pilot merely because it starts small.`,`At the decision meeting, record proceed, revise, or stop; the supporting evidence; unresolved risks; and the next owner. If your team wants help shaping the lane, review ${t.serviceLabel.toLowerCase()} or use the contact page to share the stack, intended outcome, working hours, review owner, and target start. Developer Offshore can discuss a Philippines-based delivery role while your organization retains its core product, security, commercial, and production decisions.`]},
    ],
    table:{title:'Buyer decision record',columns:['Decision point','Evidence to request','Owner'],rows:[['Outcome',`Decision statement and ${t.deliverable}`,buyerOwner],['Operating model','Scope, access, review, acceptance, and escalation map','Delivery owner'],['Failure test',t.scenario,'System owner'],['Review',`Baseline and ${t.measures}`,'Buyer sponsor']]},
    relatedLinks:[{label:t.serviceLabel,href:t.service,note:'Review the closest service lane for this decision.'},{label:'Compare offshore development services',href:'/services',note:'See the available engineering and delivery lanes.'},{label:'Discuss a bounded first outcome',href:'/contact',note:'Share the stack, scope, schedule, and review owner.'}],
    faqs:[{question:'Should the provider make this decision for the buyer?',answer:'The provider can supply evidence, options, and implementation detail. The buyer should retain final authority for business priority, budget, sensitive access, accepted risk, and production changes.'},{question:'What should be documented before work starts?',answer:`Record the decision, owner, assumptions, boundaries, review date, and ${t.deliverable}.`},{question:'How should an unresolved risk be handled?',answer:'Name the risk, evidence, potential impact, owner, due date, and safe default. Do not treat silence or a sales assurance as acceptance.'}],sources:[t.source,...sharedSources]};
}

export const september23BlogBatch: readonly BlogPost[] = topics.map((topic, index) => makeDailyBlogPost(topic, index));


