import type {ResearchPost} from './fleet-data';
import {september19ResearchBatch} from './sep19-research-batch';

const base=september19ResearchBatch[0].sections;
const common=[base[2].body[1],base[3].body[1],base[4].body[0],base[5].body[1],base[6].body[0],base[8].body[0],base[9].body[0],base[10].body[0]];
const rows=[
 ['github-branch-ruleset-drift-pilot','Can an Offshore Developer Audit GitHub Branch-Rule Drift?','branch-ruleset review','Can a developer detect and explain a meaningful change in repository merge controls without receiving administration authority?','repository and ruleset identifiers, target pattern, enforcement state, bypass actors, required reviews, status checks, signed-commit setting, change event, comparison time, and administrator decision','Select one production repository and a synthetic control repository. Record the effective rules at a declared time, test an ordinary pull request and a deliberately noncompliant pull request, then introduce one approved change only in the control. The developer reports the effective difference and impact; an administrator independently verifies the result and alone changes production settings.','Detection supports a recurring read-only audit for the sampled repositories. It does not prove every control is correct, that a change was malicious, or that the developer should administer rules.','granting administration to inspect rules, checking names instead of effective enforcement, omitting bypass actors, changing production during the test, or treating a successful merge as proof every check ran','GitHub Docs: About rulesets','https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets','GitHub Docs: Available rules for rulesets','https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets','/services/devops-release-support'],
 ['kubernetes-resource-boundary-pilot','Testing Kubernetes Resource Boundaries Before Assigning Offshore Support','Kubernetes workload resource tuning','Can a developer diagnose a constrained workload and propose bounded CPU and memory changes without hiding application faults or risking production?','workload revision, namespace, image digest, requests, limits, node capacity, throttling, working set, OOM events, restarts, latency, load profile, proposed change, rollback, and platform-owner decision','Clone one representative service into an approved non-production namespace with a fixed image and repeatable load. Establish a baseline, then exercise one CPU-constrained and one memory-constrained case. Change a single request or limit at a time, retain application error evidence, and have the platform owner review scheduling, quota, cost, and rollback effects.','A reproducible diagnosis supports narrow non-production tuning on the tested workload and cluster. It does not predict production demand, justify removing limits, or authorize cluster-wide changes.','testing in production, changing load and resources together, using averages without throttling or OOM evidence, ignoring quotas, concealing restarts, or applying a recommendation without a rollback owner','Kubernetes: Resource Management for Pods and Containers','https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/','Kubernetes: Resource Quotas','https://kubernetes.io/docs/concepts/policy/resource-quotas/','/services/devops-release-support'],
 ['graphql-schema-deprecation-pilot','A GraphQL Schema-Deprecation Pilot for Offshore API Work','GraphQL field deprecation and removal planning','Can a developer produce evidence for a safe field deprecation without assuming that schema validity proves client readiness?','schema revision, field and reason, known consumers, operation signatures, observation window, usage counts, persisted queries, replacement coverage, removal gate, rollback, and API-owner decision','Choose one low-risk field with a supported replacement. Mark it deprecated in a non-production schema, inventory known operations and persisted queries, run representative clients, and observe approved telemetry for a declared window. Seed a synthetic legacy consumer to prove detection. The API owner assesses unknown-client risk and sets any removal date.','Detection of known and seeded consumers supports the mechanism, not immediate removal. Unobserved use is not proof of zero use, and results do not transfer automatically to another gateway or client population.','removing before a declared observation window, logging sensitive variables, ignoring persisted queries or mobile clients, treating introspection as usage evidence, or letting the implementer approve removal','GraphQL Specification: Deprecation','https://spec.graphql.org/October2021/#sec-Deprecation','GraphQL.org: Versioning','https://graphql.org/learn/best-practices/#versioning','/services/node-js-api-development'],
 ['web-accessibility-name-pilot','Can an Offshore Frontend Developer Verify Accessible Names Reliably?','accessible-name regression work','Can a developer identify and correct accessible-name failures in a representative React flow while preserving visible labels and product meaning?','component revision, browser and assistive-technology version, computed name, visible label, role, description, focus order, automated finding, manual announcement, localization state, reviewer result, and exception owner','Select a form, dialog, and icon-only control from an approved test build. Record the accessibility tree and keyboard path, add cases with a missing label, conflicting label, hidden text, and localized visible label, then make focused corrections. Use automation as a repeatable signal and have an accessibility reviewer manually confirm name, role, state, and task meaning.','Correct results support work on the tested components and stack. They do not certify WCAG conformance, prove usability for every assistive technology, or permit automation to replace manual review.','adding aria-label where visible text should be used, hiding the only meaningful label, testing only DOM attributes, ignoring localization, changing terminology without approval, or declaring conformance from a scanner','W3C: Accessible Name and Description Computation 1.2','https://www.w3.org/TR/accname-1.2/','WCAG 2.2: Name, Role, Value','https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html','/services/react-frontend-development'],
 ['object-storage-retention-pilot','Testing Object-Storage Retention Controls With an Offshore Developer','object-storage retention implementation','Can a developer demonstrate that retention behavior matches a declared policy without using customer data or gaining authority to shorten protected retention?','bucket and object identifiers, provider and region, versioning state, retention mode, retain-until time, legal hold, lifecycle rule, actor, attempted action, response, audit event, clock source, cleanup owner, and security-owner decision','Use an isolated non-production bucket and synthetic objects. Pin the provider configuration, enable versioning where required, and exercise unprotected, retained, expired, and legal-hold cases with separate named identities. Attempt permitted and denied actions, inspect authoritative metadata and audit events, then have the security owner verify that the developer cannot weaken the protected case.','The exercise demonstrates behavior only for the tested provider, identity, mode, and configuration. It does not establish legal compliance, prove every replica follows policy, or authorize production retention changes.','using customer records, confusing lifecycle expiry with immutable retention, relying on screenshots, testing with an owner identity, omitting version IDs, or leaving retained fixtures without a cleanup owner','Amazon S3: Locking objects with Object Lock','https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html','NIST SP 800-53 Rev. 5','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final','/services/data-pipeline-development'],
] as const;

export const september22ResearchBatch:readonly ResearchPost[]=rows.map(r=>{const [id,title,choice,question,signals,method,inference,failure,s1,u1,s2,u2,service]=r;return {
 slug:`offshore-developer-${id}-study-2026-09-22`,title,published:'2026-09-22',excerpt:`A source-backed, reproducible study for evaluating ${choice} in a Philippines-based developer pilot.`,keyStats:['1 declared staffing decision','14-day bounded observation window','3 authoritative sources'],takeaways:[question,`Retain ${signals}.`,failure],
 sections:[
  {heading:'Decision and research question',body:[`Decision: ${choice}. Research question: ${question}`,`The unit is one developer, one named client reviewer, representative work, and a declared 14-day window. Define success and stop conditions before work begins. Findings apply only to this unit, revision, environment, access boundary, and period.`]},
  {heading:'Why this matters for offshore development',body:[`DeveloperOffshore.com serves buyers considering Philippines-based software developers. The useful question is whether a specific responsibility can be bounded, observed, reviewed, and safely expanded inside the client’s operating system. This study connects that decision to ${service}.`,`Distributed work benefits from durable evidence because implementer and reviewer may not be online together. Reproducible checks, explicit uncertainty, and a named decision owner allow careful review without granting broad authority or using activity as a proxy for quality.`]},
  {heading:'Methodology',body:[method,common[0]]},{heading:'Evidence plan',body:[`Collect ${signals}.`,common[1]]},{heading:'Execution procedure',body:[common[2],`Use synthetic or approved non-production inputs. Keep revision, configuration, identity, and window stable while varying one intended condition. Capture the first attempt, record assistance, test the expected path and a denied or failure path, and require a second person to trace the conclusion to original evidence.`]},
  {heading:'Analysis and inference boundaries',body:[inference,common[3]]},{heading:'Roles, controls, and escalation',body:[common[4],`The developer may prepare fixtures, run approved checks, document uncertainty, and propose a reversible change. The client retains production access, risk acceptance, exception approval, and final release. Pause when scope, data classification, permissions, or production impact differs from the brief.`]},
  {heading:'Failure and counterevidence tests',body:[`Invalidate or narrow the result when there is ${failure}.`,`Seek a case that could overturn the preferred conclusion. Repeat one disputed case after changing only the suspected cause. Inspect exclusions and missing records. A defensible stop is more valuable than an attractive result another reviewer cannot reproduce.`]},
  {heading:'Review worksheet',body:[common[5],`For each case, record expected outcome, actual outcome, evidence link, control result, uncertainty, reviewer decision, correction, and next owner. Do not average away a severe boundary failure. The staffing decision concerns safe operation as well as completion.`]},
  {heading:'Limitations',body:[common[6],`This report does not establish results for every Philippines-based developer, customer, stack, provider, or client. It makes no claim about DeveloperOffshore.com customers, pricing, locations, or outcomes. Public sources define methods and controls; only local evidence describes the tested implementation.`]},
  {heading:'Decision rule and closeout',body:[common[7],`Expand scope only when evidence remains reviewable, the client owner can reproduce the critical boundary, and unresolved risk has an explicit owner. If the client workflow prevents a fair test, correct it and run a new study rather than approving or rejecting the developer without evidence.`]},
  {heading:'Sources and checked dates',body:[`Sources were checked 2026-09-22. They inform method and control claims but do not establish local findings.`,`${s1}: ${u1}`,`${s2}: ${u2}`,'NIST Secure Software Development Framework: https://csrc.nist.gov/pubs/sp/800/218/final']},
 ],sources:[{name:`${s1} (checked 2026-09-22)`,url:u1},{name:`${s2} (checked 2026-09-22)`,url:u2},{name:'NIST Secure Software Development Framework (checked 2026-09-22)',url:'https://csrc.nist.gov/pubs/sp/800/218/final'}],faqs:[{question:'Does this study prove the developer will succeed?',answer:'No. It provides bounded evidence for one workflow, responsibility, and accountable review decision.'},{question:'Who accepts remaining risk?',answer:'The named client owner. The developer and automation may provide evidence but do not accept risk.'}],related:[{title:'Relevant developer service',href:service},{title:'Research library',href:'/research'},{title:'Discuss a role',href:'/contact'}]};});
