import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {articleThumbnail} from '../../article-thumbnails';
import {Header,Footer} from '../../components';
import {researchPosts,ResearchPost} from '../../fleet-data';
import {site} from '../../data';

export function generateStaticParams(){return researchPosts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const post=researchPosts.find(p=>p.slug===slug);if(!post)return{};const thumbnail=articleThumbnail('research',post.slug,post.title);const baseUrl=`https://${site.domain.toLowerCase()}`;const url=`${baseUrl}/research/${post.slug}`;return{title:post.title,description:post.excerpt,alternates:{canonical:url},openGraph:{title:post.title,description:post.excerpt,url,type:'article',images:[{url:`${baseUrl}${thumbnail.src}`,alt:thumbnail.alt}]}}}
export default async function ResearchArticle({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post:ResearchPost|undefined=researchPosts.find(p=>p.slug===slug);if(!post)notFound();const thumbnail=articleThumbnail('research',post.slug,post.title);return <><Header/><main><article className="section"><div className="container article-shell"><p className="eyebrow">{site.brand} research</p><h1>{post.title}</h1><p className="lead">{post.excerpt}</p><img className="article-featured-image" src={thumbnail.src} alt={thumbnail.alt}/><section className="card"><h2>Key Stats</h2><ul>{post.keyStats.map(stat=><li key={stat}>{stat}</li>)}</ul></section><section className="card"><h2>Key Takeaways</h2><ul>{post.takeaways.map(takeaway=><li key={takeaway}>{takeaway}</li>)}</ul></section>{post.sections.map(s=><section className="card" key={s.heading}><h2>{s.heading}</h2>{s.body.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</section>)}<section className="card"><h2>Frequently asked questions</h2>{post.faqs.map(faq=><div key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></div>)}</section>{post.sources?.length?<section className="card"><h2>Sources</h2><ol>{post.sources.map(s=><li key={s.url}><a href={s.url} rel="noreferrer">{s.name}</a></li>)}</ol></section>:null}<section className="card"><h2>Related Research</h2><ul>{post.related.map(link=><li key={link.href}><a href={link.href}>{link.title}</a></li>)}</ul></section><aside className="card"><h2>Apply the findings</h2><p>Turn this research into a bounded role, review owner, and first-week routine for your team.</p><p><a className="btn primary" href="/contact-us">Discuss a role</a> <a className="btn secondary" href="/blog">Read related blog guides</a></p></aside></div></article></main><Footer/></>}
